const crypto=require('crypto');
const {ownerId:authenticatedOwnerId}=require('./owner-auth-service');
module.exports=function registerBusinessRoutes(app,pool){
 const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
 const password=s=>crypto.scryptSync(String(s),String(process.env.BUSINESS_PASSWORD_SALT||'cepqar-business-v1'),64).toString('hex');
 const token=()=>crypto.randomBytes(32).toString('hex');
 const fs=require('fs'),path=require('path');
 const uploadDir=process.env.BUSINESS_UPLOAD_DIR||'/opt/heycar/uploads/business';try{fs.mkdirSync(uploadDir,{recursive:true});}catch(e){console.error('upload dir',e);}
 app.get('/uploads/business/:name',(req,res)=>{const n=path.basename(String(req.params.name||''));if(!/^[a-f0-9-]+\.(jpg|jpeg|png|webp)$/i.test(n))return res.status(404).end();res.sendFile(path.join(uploadDir,n));});
 app.post('/api/business/media',async(req,res)=>{const account=await auth(req,res);if(!account)return;try{const body=req.body||{},raw=String(body.data||''),kind=String(body.kind||'campaign');const m=raw.match(/^data:image\/(jpeg|jpg|png|webp);base64,(.+)$/);if(!m)return res.status(400).json({error:'INVALID_IMAGE'});const buf=Buffer.from(m[2],'base64');if(!buf.length||buf.length>2500000)return res.status(413).json({error:'IMAGE_TOO_LARGE'});const ext=m[1]==='jpeg'?'jpg':m[1],name=crypto.randomUUID()+'.'+ext;fs.writeFileSync(path.join(uploadDir,name),buf,{mode:0o644});const base=String(process.env.PUBLIC_API_BASE_URL||'https://cepqar.com').replace(/\/$/,'');res.status(201).json({ok:true,url:base+'/uploads/business/'+name,kind});}catch(e){console.error('business media',e);res.status(500).json({error:'UPLOAD_FAILED'});}});

 async function auth(req,res){const raw=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!raw){res.status(401).json({error:'AUTH_REQUIRED'});return null;}const q=await pool.query("SELECT a.id FROM business_sessions s JOIN business_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>now()",[hash(raw)]);if(!q.rowCount){res.status(401).json({error:'INVALID_SESSION'});return null;}return q.rows[0].id;}
 app.post('/api/business/address-candidates',async(req,res)=>{try{const {street,houseNumber,district,city}=req.body||{};if(!street||!houseNumber||!city)return res.status(400).json({error:'INVALID_ADDRESS'});const key=process.env.GEOAPIFY_API_KEY;if(!key)return res.status(503).json({error:'GEOCODING_UNAVAILABLE'});const text=[street,'No: '+houseNumber,district,city,'Türkiye'].filter(Boolean).join(', ');const url='https://api.geoapify.com/v1/geocode/search?text='+encodeURIComponent(text)+'&limit=5&filter=countrycode:tr&lang=tr&apiKey='+encodeURIComponent(key);const gr=await fetch(url);const gj=await gr.json();const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]/g,'');const wantedStreet=norm(street),wantedHouse=norm(houseNumber),wantedDistrict=norm(district),wantedCity=norm(city);const rows=(gj.features||[]).map(f=>f.properties||{}).map(p=>{const confidence=Number(p.rank&&p.rank.confidence||0);const streetOk=norm(p.street)===wantedStreet;const houseOk=norm(p.housenumber)===wantedHouse;const area=[p.suburb,p.district,p.city,p.county,p.state].map(norm);const districtOk=!wantedDistrict||area.some(x=>x.includes(wantedDistrict)||wantedDistrict.includes(x));const cityOk=!wantedCity||area.some(x=>x.includes(wantedCity)||wantedCity.includes(x));const score=(streetOk?4:0)+(houseOk?3:0)+(districtOk?2:0)+(cityOk?2:0)+confidence;return {formatted:p.formatted,latitude:Number(p.lat),longitude:Number(p.lon),confidence,streetOk,houseOk,districtOk,cityOk,score};}).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)).sort((a,b)=>b.score-a.score);res.json({ok:true,candidates:rows});}catch(e){console.error('address candidates',e);res.status(503).json({error:'GEOCODING_FAILED'});}});
 app.post('/api/business/auth/register',async(req,res)=>{try{let {email,password:pw,name,category,services,phone,address,street,houseNumber,district,city,latitude,longitude,openingHours,logoUrl}=req.body||{};if(!email||!pw||String(pw).length<8||!name||!category)return res.status(400).json({error:'INVALID_INPUT'});
  if(address&&(!Number.isFinite(Number(latitude))||!Number.isFinite(Number(longitude)))){
   try{
    const key=process.env.GEOAPIFY_API_KEY;
    if(!key)return res.status(503).json({error:'GEOCODING_UNAVAILABLE'});
    const structured=street&&houseNumber;
    const url=structured
     ? 'https://api.geoapify.com/v1/geocode/search?housenumber='+encodeURIComponent(houseNumber)+'&street='+encodeURIComponent(street)+(district?'&suburb='+encodeURIComponent(district):'')+(city?'&city='+encodeURIComponent(city):'')+'&country='+encodeURIComponent('Türkiye')+'&limit=1&filter=countrycode:tr&apiKey='+encodeURIComponent(key)
     : 'https://api.geoapify.com/v1/geocode/search?text='+encodeURIComponent(String(address)+', Türkiye')+'&limit=1&filter=countrycode:tr&apiKey='+encodeURIComponent(key);
    const gr=await fetch(url);const gj=await gr.json();const p=gj&&gj.features&&gj.features[0]&&gj.features[0].properties;
    if(!p||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lon)))return res.status(400).json({error:'ADDRESS_NOT_FOUND'});
    const conf=Number(p.rank&&p.rank.confidence||0);if(conf<0.7)return res.status(409).json({error:'ADDRESS_CONFIRM_REQUIRED'});
    latitude=Number(p.lat);longitude=Number(p.lon);
   }catch(e){console.error('business geocode',e);return res.status(503).json({error:'GEOCODING_FAILED'});}
  }
  const client=await pool.connect();try{await client.query('BEGIN');const a=await client.query('INSERT INTO business_accounts(email,password_hash) VALUES(lower($1),$2) RETURNING id',[email,password(pw)]);const b=await client.query('INSERT INTO businesses(account_id,name,category,phone,address,latitude,longitude,opening_hours,logo_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[a.rows[0].id,name,category,phone||null,address||null,Number.isFinite(Number(latitude))?Number(latitude):null,Number.isFinite(Number(longitude))?Number(longitude):null,openingHours||null,logoUrl||null]);const raw=token();await client.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),a.rows[0].id]);await client.query('COMMIT');res.status(201).json({ok:true,token:raw,business:b.rows[0]});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({error:'EMAIL_EXISTS'});throw e;}finally{client.release();}}catch(e){console.error('business register',e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/business/auth/login',async(req,res)=>{try{const {email,password:pw}=req.body||{};const q=await pool.query('SELECT id,password_hash FROM business_accounts WHERE email=lower($1)',[email||'']);if(!q.rowCount||q.rows[0].password_hash!==password(pw||''))return res.status(401).json({error:'INVALID_CREDENTIALS'});const raw=token();await pool.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),q.rows[0].id]);res.json({ok:true,token:raw});}catch(e){res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/business/me',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT * FROM businesses WHERE account_id=$1',[id]);res.json({ok:true,business:q.rows[0]||null});});
 app.get('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT c.* FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1 ORDER BY c.created_at DESC',[id]);res.json({ok:true,campaigns:q.rows});});
 app.post('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {title,description,badge,couponCode,startsAt,endsAt,dailyLimit,totalLimit,offerType,regularPrice,offerPrice,discountPercent,imageUrl}=req.body||{};if(!title||!startsAt||!endsAt)return res.status(400).json({error:'INVALID_INPUT'});const type=['discount','special_price','gift'].includes(offerType)?offerType:'discount';const q=await pool.query('INSERT INTO business_campaigns(business_id,title,description,badge,coupon_code,starts_at,ends_at,daily_limit,total_limit,offer_type,regular_price,offer_price,discount_percent,image_url) SELECT id,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14 FROM businesses WHERE account_id=$1 RETURNING *',[id,title,description||'',badge||'',couponCode||null,startsAt,endsAt,dailyLimit||null,totalLimit||null,type,Number.isFinite(Number(regularPrice))?Number(regularPrice):null,Number.isFinite(Number(offerPrice))?Number(offerPrice):null,Number.isInteger(Number(discountPercent))?Number(discountPercent):null,imageUrl||null]);res.status(201).json({ok:true,campaign:q.rows[0]});}catch(e){res.status(400).json({error:'CAMPAIGN_INVALID'});}});
 app.patch('/api/business/me',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {name,category,phone,address,latitude,longitude,openingHours,description,logoUrl}=req.body||{};const q=await pool.query(`UPDATE businesses SET name=COALESCE($2,name),category=COALESCE($3,category),phone=$4,address=$5,latitude=$6,longitude=$7,opening_hours=$8,description=$9,logo_url=$10,updated_at=now() WHERE account_id=$1 RETURNING *`,[id,name||null,category||null,phone||null,address||null,Number.isFinite(Number(latitude))?Number(latitude):null,Number.isFinite(Number(longitude))?Number(longitude):null,openingHours||null,description||null,logoUrl||null]);res.json({ok:true,business:q.rows[0]});}catch(e){res.status(400).json({error:'BUSINESS_INVALID'});}});
 app.patch('/api/business/campaigns/:campaignId',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {title,description,badge,couponCode,startsAt,endsAt,dailyLimit,totalLimit,isActive}=req.body||{};const q=await pool.query(`UPDATE business_campaigns c SET title=COALESCE($3,c.title),description=COALESCE($4,c.description),badge=COALESCE($5,c.badge),coupon_code=$6,starts_at=COALESCE($7,c.starts_at),ends_at=COALESCE($8,c.ends_at),daily_limit=$9,total_limit=$10,is_active=COALESCE($11,c.is_active),updated_at=now() FROM businesses b WHERE c.business_id=b.id AND b.account_id=$1 AND c.id=$2 RETURNING c.*`,[id,req.params.campaignId,title||null,description??null,badge??null,couponCode||null,startsAt||null,endsAt||null,dailyLimit||null,totalLimit||null,typeof isActive==='boolean'?isActive:null]);if(!q.rowCount)return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true,campaign:q.rows[0]});}catch(e){res.status(400).json({error:'CAMPAIGN_INVALID'});}});
 app.delete('/api/business/campaigns/:campaignId',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query(`UPDATE business_campaigns c SET is_active=false,updated_at=now() FROM businesses b WHERE c.business_id=b.id AND b.account_id=$1 AND c.id=$2 RETURNING c.id`,[id,req.params.campaignId]);if(!q.rowCount)return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true});});
 app.post('/api/business/auth/logout',async(req,res)=>{const raw=String(req.headers.authorization||'').replace(/^Bearer\\s+/i,'');if(raw)await pool.query('DELETE FROM business_sessions WHERE token_hash=$1',[hash(raw)]);res.json({ok:true});});
 app.get('/api/business/stats',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query(`SELECT count(*)::int campaigns,count(*) FILTER(WHERE c.is_active AND now() BETWEEN c.starts_at AND c.ends_at)::int active_campaigns,COALESCE(sum(c.redemption_count),0)::int redemptions,COALESCE((SELECT sum(r.platform_fee) FROM offer_redemptions r JOIN business_campaigns c2 ON c2.id=r.campaign_id JOIN businesses b2 ON b2.id=c2.business_id WHERE b2.account_id=$1 AND r.status='redeemed'),0)::numeric platform_fees FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1`,[id]);res.json({ok:true,stats:q.rows[0]});});
 app.get('/api/offers/nearby',async(req,res)=>{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'INVALID_LOCATION'});const q=await pool.query(`SELECT c.id,c.title,c.description,c.badge,c.coupon_code,c.ends_at,c.offer_type,c.regular_price,c.offer_price,c.discount_percent,c.image_url,b.id AS business_id,b.name,b.logo_url,b.category,b.category AS services,b.opening_hours,b.address,b.latitude,b.longitude,(6371000*2*asin(sqrt(power(sin(radians(b.latitude-$1)/2),2)+cos(radians($1))*cos(radians(b.latitude))*power(sin(radians(b.longitude-$2)/2),2)))) distance_m FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.is_active=true AND c.is_active=true AND now() BETWEEN c.starts_at AND c.ends_at AND b.latitude IS NOT NULL AND b.longitude IS NOT NULL ORDER BY distance_m LIMIT 50`,[lat,lon]);const ids=q.rows.map(x=>x.business_id);let sums={};if(ids.length){const s=await pool.query(`SELECT c.business_id,round(avg(r.rating)::numeric,1) rating,count(r.id)::int review_count FROM offer_reviews r JOIN business_campaigns c ON c.id=r.campaign_id WHERE c.business_id=ANY($1::uuid[]) GROUP BY c.business_id`,[ids]);for(const x of s.rows)sums[x.business_id]=x;}for(const x of q.rows){const s=sums[x.business_id]||{};x.rating=s.rating||null;x.review_count=s.review_count||0;}res.json({ok:true,offers:q.rows.filter(x=>Number(x.distance_m)<=10000)});});

 // --- Offer usage / favorites / verified reviews ---
 const ownerId=req=>authenticatedOwnerId(req);
 const usageCode=()=>crypto.randomBytes(4).toString('hex').toUpperCase();

 app.get('/api/offers/favorites',async(req,res)=>{try{const owner=ownerId(req);if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});const q=await pool.query('SELECT campaign_id FROM offer_favorites WHERE owner_id=$1 ORDER BY created_at DESC',[owner]);res.json({ok:true,favorites:q.rows.map(x=>x.campaign_id)});}catch(e){console.error('favorites list',e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/offers/:campaignId/favorite',async(req,res)=>{try{const owner=ownerId(req);if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});await pool.query('INSERT INTO offer_favorites(owner_id,campaign_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[owner,req.params.campaignId]);res.json({ok:true,favorite:true});}catch(e){res.status(400).json({error:'INVALID_OFFER'});}});
 app.delete('/api/offers/:campaignId/favorite',async(req,res)=>{try{const owner=ownerId(req);if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});await pool.query('DELETE FROM offer_favorites WHERE owner_id=$1 AND campaign_id=$2',[owner,req.params.campaignId]);res.json({ok:true,favorite:false});}catch(e){res.status(400).json({error:'INVALID_OFFER'});}});

 app.get('/api/offers/:campaignId/redemption',async(req,res)=>{try{const owner=ownerId(req);if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});const q=await pool.query("SELECT id,usage_code,plate,status,created_at,redeemed_at FROM offer_redemptions WHERE owner_id=$1 AND campaign_id=$2 ORDER BY created_at DESC LIMIT 1",[owner,req.params.campaignId]);res.json({ok:true,redemption:q.rows[0]||null});}catch(e){res.status(400).json({error:'INVALID_OFFER'});}});
 app.post('/api/offers/:campaignId/redeem',async(req,res)=>{try{const owner=ownerId(req),plate=String((req.body||{}).plate||'').trim().toUpperCase().replace(/\\s+/g,'');if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});if(!plate)return res.status(400).json({error:'PLATE_REQUIRED'});
  const valid=await pool.query('SELECT id FROM business_campaigns WHERE id=$1 AND is_active=true AND now() BETWEEN starts_at AND ends_at',[req.params.campaignId]);if(!valid.rowCount)return res.status(404).json({error:'OFFER_NOT_AVAILABLE'});
  const old=await pool.query("SELECT id,usage_code,plate,status,created_at,redeemed_at FROM offer_redemptions WHERE owner_id=$1 AND campaign_id=$2 AND status='pending' ORDER BY created_at DESC LIMIT 1",[owner,req.params.campaignId]);if(old.rowCount)return res.json({ok:true,redemption:old.rows[0]});
  let code;for(let i=0;i<5;i++){code=usageCode();try{const q=await pool.query("INSERT INTO offer_redemptions(owner_id,campaign_id,plate,usage_code,status) VALUES($1,$2,$3,$4,'pending') RETURNING id,usage_code,plate,status,created_at",[owner,req.params.campaignId,plate,code]);return res.status(201).json({ok:true,redemption:q.rows[0]});}catch(e){if(e.code!=='23505')throw e;}}
  res.status(503).json({error:'CODE_GENERATION_FAILED'});
 }catch(e){console.error('offer redeem',e);res.status(400).json({error:'REDEEM_FAILED'});}});

 app.post('/api/business/redemptions/verify',async(req,res)=>{const account=await auth(req,res);if(!account)return;const code=String((req.body||{}).code||'').trim().toUpperCase(),plate=String((req.body||{}).plate||'').trim().toUpperCase().replace(/\\s+/g,'');if(!code||!plate)return res.status(400).json({error:'CODE_AND_PLATE_REQUIRED'});const client=await pool.connect();try{await client.query('BEGIN');const q=await client.query(`SELECT r.id,r.campaign_id,r.plate,r.status,c.title FROM offer_redemptions r JOIN business_campaigns c ON c.id=r.campaign_id JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1 AND r.usage_code=$2 AND r.plate=$3 FOR UPDATE`,[account,code,plate]);if(!q.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'CODE_NOT_FOUND'});}const row=q.rows[0];if(row.status!=='pending'){await client.query('ROLLBACK');return res.status(409).json({error:'ALREADY_USED'});}await client.query("UPDATE offer_redemptions r SET status='redeemed',redeemed_at=now(),platform_fee=c.platform_fee FROM business_campaigns c WHERE r.id=$1 AND c.id=r.campaign_id",[row.id]);await client.query('UPDATE business_campaigns SET redemption_count=redemption_count+1,updated_at=now() WHERE id=$1',[row.campaign_id]);await client.query('COMMIT');res.json({ok:true,redemption:{...row,status:'redeemed'}});}catch(e){await client.query('ROLLBACK');console.error('verify redemption',e);res.status(500).json({error:'VERIFY_FAILED'});}finally{client.release();}});
 app.get('/api/business/redemptions',async(req,res)=>{const account=await auth(req,res);if(!account)return;const q=await pool.query(`SELECT r.id,r.plate,r.usage_code,r.status,r.created_at,r.redeemed_at,c.title FROM offer_redemptions r JOIN business_campaigns c ON c.id=r.campaign_id JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1 ORDER BY r.created_at DESC LIMIT 100`,[account]);res.json({ok:true,redemptions:q.rows});});

 app.post('/api/offers/:campaignId/review',async(req,res)=>{try{const owner=ownerId(req),rating=Number((req.body||{}).rating),comment=String((req.body||{}).comment||'').trim();if(!owner)return res.status(401).json({error:'OWNER_REQUIRED'});if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:'INVALID_RATING'});const used=await pool.query("SELECT r.id,c.business_id FROM offer_redemptions r JOIN business_campaigns c ON c.id=r.campaign_id WHERE r.owner_id=$1 AND r.campaign_id=$2 AND r.status='redeemed' ORDER BY r.redeemed_at DESC LIMIT 1",[owner,req.params.campaignId]);if(!used.rowCount)return res.status(403).json({error:'REDEMPTION_REQUIRED'});const q=await pool.query('INSERT INTO offer_reviews(owner_id,campaign_id,redemption_id,rating,comment) VALUES($1,$2,$3,$4,$5) ON CONFLICT(owner_id,campaign_id) DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment,updated_at=now() RETURNING *',[owner,req.params.campaignId,used.rows[0].id,rating,comment]);res.json({ok:true,review:q.rows[0]});}catch(e){console.error('offer review',e);res.status(400).json({error:'REVIEW_FAILED'});}});
 app.get('/api/offers/:campaignId/reviews',async(req,res)=>{try{const q=await pool.query(`SELECT r.rating,r.comment,r.created_at FROM offer_reviews r JOIN business_campaigns c0 ON c0.id=$1 JOIN business_campaigns c ON c.business_id=c0.business_id WHERE r.campaign_id=c.id ORDER BY r.created_at DESC LIMIT 50`,[req.params.campaignId]);const s=await pool.query(`SELECT round(avg(r.rating)::numeric,1) rating,count(r.id)::int review_count FROM offer_reviews r JOIN business_campaigns c0 ON c0.id=$1 JOIN business_campaigns c ON c.business_id=c0.business_id WHERE r.campaign_id=c.id`,[req.params.campaignId]);res.json({ok:true,reviews:q.rows,rating:s.rows[0]?.rating||null,reviewCount:s.rows[0]?.review_count||0});}catch(e){res.status(400).json({error:'INVALID_OFFER'});}});

};