const crypto=require('crypto');
module.exports=function registerBusinessRoutes(app,pool){
 const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
 const password=s=>crypto.scryptSync(String(s),String(process.env.BUSINESS_PASSWORD_SALT||'cepqar-business-v1'),64).toString('hex');
 const token=()=>crypto.randomBytes(32).toString('hex');
 async function auth(req,res){const raw=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!raw){res.status(401).json({error:'AUTH_REQUIRED'});return null;}const q=await pool.query("SELECT a.id FROM business_sessions s JOIN business_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>now()",[hash(raw)]);if(!q.rowCount){res.status(401).json({error:'INVALID_SESSION'});return null;}return q.rows[0].id;}
 app.post('/api/business/address-candidates',async(req,res)=>{try{const {street,houseNumber,district,city}=req.body||{};if(!street||!houseNumber||!city)return res.status(400).json({error:'INVALID_ADDRESS'});const key=process.env.GEOAPIFY_API_KEY;if(!key)return res.status(503).json({error:'GEOCODING_UNAVAILABLE'});const text=[street,'No: '+houseNumber,district,city,'Türkiye'].filter(Boolean).join(', ');const url='https://api.geoapify.com/v1/geocode/search?text='+encodeURIComponent(text)+'&limit=5&filter=countrycode:tr&lang=tr&apiKey='+encodeURIComponent(key);const gr=await fetch(url);const gj=await gr.json();const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]/g,'');const wantedStreet=norm(street),wantedHouse=norm(houseNumber),wantedDistrict=norm(district),wantedCity=norm(city);const rows=(gj.features||[]).map(f=>f.properties||{}).map(p=>{const confidence=Number(p.rank&&p.rank.confidence||0);const streetOk=norm(p.street)===wantedStreet;const houseOk=norm(p.housenumber)===wantedHouse;const area=[p.suburb,p.district,p.city,p.county,p.state].map(norm);const districtOk=!wantedDistrict||area.some(x=>x.includes(wantedDistrict)||wantedDistrict.includes(x));const cityOk=!wantedCity||area.some(x=>x.includes(wantedCity)||wantedCity.includes(x));const score=(streetOk?4:0)+(houseOk?3:0)+(districtOk?2:0)+(cityOk?2:0)+confidence;return {formatted:p.formatted,latitude:Number(p.lat),longitude:Number(p.lon),confidence,streetOk,houseOk,districtOk,cityOk,score};}).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)).sort((a,b)=>b.score-a.score);res.json({ok:true,candidates:rows});}catch(e){console.error('address candidates',e);res.status(503).json({error:'GEOCODING_FAILED'});}});
 app.post('/api/business/auth/register',async(req,res)=>{try{let {email,password:pw,name,category,phone,address,street,houseNumber,district,city,latitude,longitude}=req.body||{};if(!email||!pw||String(pw).length<8||!name||!category)return res.status(400).json({error:'INVALID_INPUT'});
  if(address&&(!Number.isFinite(Number(latitude))||!Number.isFinite(Number(longitude)))){
   try{
    const key=process.env.GEOAPIFY_API_KEY;
    if(!key)return res.status(503).json({error:'GEOCODING_UNAVAILABLE'});
    const structured=street&&houseNumber;
    const url=structured
     ? 'https://api.geoapify.com/v1/geocode/search?housenumber='+encodeURIComponent(houseNumber)+'&street='+encodeURIComponent(street)+(district?'&suburb='+encodeURIComponent(district):'')+(city?'&city='+encodeURIComponent(city):'')+'&country='+encodeURIComponent('Türkiye')+'&limit=1&filter=countrycode:tr&apiKey='+encodeURIComponent(key)
     : 'https://api.geoapify.com/v1/geocode/search?text='+encodeURIComponent(String(address)+', Türkiye')+'&limit=1&filter=countrycode:tr&apiKey='+encodeURIComponent(key);
    const gr=await fetch(url);const gj=await gr.json();const p=gj&&gj.features&&gj.features[0]&&gj.features[0].properties;
    if(!p||!Number.isFinite(Number(p.lat))||!Number.isFinite(Number(p.lon)))return res.status(400).json({error:'ADDRESS_NOT_FOUND'});
    const conf=Number(p.rank&&p.rank.confidence||0);if(conf<0.7)return res.status(409).json({error:'ADDRESS_CONFIRM_REQUIRED'});
    latitude=Number(p.lat);longitude=Number(p.lon);
   }catch(e){console.error('business geocode',e);return res.status(503).json({error:'GEOCODING_FAILED'});}
  }
  const client=await pool.connect();try{await client.query('BEGIN');const a=await client.query('INSERT INTO business_accounts(email,password_hash) VALUES(lower($1),$2) RETURNING id',[email,password(pw)]);const b=await client.query('INSERT INTO businesses(account_id,name,category,phone,address,latitude,longitude) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[a.rows[0].id,name,category,phone||null,address||null,Number.isFinite(Number(latitude))?Number(latitude):null,Number.isFinite(Number(longitude))?Number(longitude):null]);const raw=token();await client.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),a.rows[0].id]);await client.query('COMMIT');res.status(201).json({ok:true,token:raw,business:b.rows[0]});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({error:'EMAIL_EXISTS'});throw e;}finally{client.release();}}catch(e){console.error('business register',e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/business/auth/login',async(req,res)=>{try{const {email,password:pw}=req.body||{};const q=await pool.query('SELECT id,password_hash FROM business_accounts WHERE email=lower($1)',[email||'']);if(!q.rowCount||q.rows[0].password_hash!==password(pw||''))return res.status(401).json({error:'INVALID_CREDENTIALS'});const raw=token();await pool.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),q.rows[0].id]);res.json({ok:true,token:raw});}catch(e){res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/business/me',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT * FROM businesses WHERE account_id=$1',[id]);res.json({ok:true,business:q.rows[0]||null});});
 app.get('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT c.* FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1 ORDER BY c.created_at DESC',[id]);res.json({ok:true,campaigns:q.rows});});
 app.post('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {title,description,badge,couponCode,startsAt,endsAt,dailyLimit,totalLimit}=req.body||{};if(!title||!startsAt||!endsAt)return res.status(400).json({error:'INVALID_INPUT'});const q=await pool.query('INSERT INTO business_campaigns(business_id,title,description,badge,coupon_code,starts_at,ends_at,daily_limit,total_limit) SELECT id,$2,$3,$4,$5,$6,$7,$8,$9 FROM businesses WHERE account_id=$1 RETURNING *',[id,title,description||'',badge||'',couponCode||null,startsAt,endsAt,dailyLimit||null,totalLimit||null]);res.status(201).json({ok:true,campaign:q.rows[0]});}catch(e){res.status(400).json({error:'CAMPAIGN_INVALID'});}});
 app.patch('/api/business/me',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {name,category,phone,address,latitude,longitude,openingHours,description,logoUrl}=req.body||{};const q=await pool.query(`UPDATE businesses SET name=COALESCE($2,name),category=COALESCE($3,category),phone=$4,address=$5,latitude=$6,longitude=$7,opening_hours=$8,description=$9,logo_url=$10,updated_at=now() WHERE account_id=$1 RETURNING *`,[id,name||null,category||null,phone||null,address||null,Number.isFinite(Number(latitude))?Number(latitude):null,Number.isFinite(Number(longitude))?Number(longitude):null,openingHours||null,description||null,logoUrl||null]);res.json({ok:true,business:q.rows[0]});}catch(e){res.status(400).json({error:'BUSINESS_INVALID'});}});
 app.patch('/api/business/campaigns/:campaignId',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {title,description,badge,couponCode,startsAt,endsAt,dailyLimit,totalLimit,isActive}=req.body||{};const q=await pool.query(`UPDATE business_campaigns c SET title=COALESCE($3,c.title),description=COALESCE($4,c.description),badge=COALESCE($5,c.badge),coupon_code=$6,starts_at=COALESCE($7,c.starts_at),ends_at=COALESCE($8,c.ends_at),daily_limit=$9,total_limit=$10,is_active=COALESCE($11,c.is_active),updated_at=now() FROM businesses b WHERE c.business_id=b.id AND b.account_id=$1 AND c.id=$2 RETURNING c.*`,[id,req.params.campaignId,title||null,description??null,badge??null,couponCode||null,startsAt||null,endsAt||null,dailyLimit||null,totalLimit||null,typeof isActive==='boolean'?isActive:null]);if(!q.rowCount)return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true,campaign:q.rows[0]});}catch(e){res.status(400).json({error:'CAMPAIGN_INVALID'});}});
 app.delete('/api/business/campaigns/:campaignId',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query(`UPDATE business_campaigns c SET is_active=false,updated_at=now() FROM businesses b WHERE c.business_id=b.id AND b.account_id=$1 AND c.id=$2 RETURNING c.id`,[id,req.params.campaignId]);if(!q.rowCount)return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true});});
 app.post('/api/business/auth/logout',async(req,res)=>{const raw=String(req.headers.authorization||'').replace(/^Bearer\\s+/i,'');if(raw)await pool.query('DELETE FROM business_sessions WHERE token_hash=$1',[hash(raw)]);res.json({ok:true});});
 app.get('/api/business/stats',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query(`SELECT count(*)::int campaigns,count(*) FILTER(WHERE c.is_active AND now() BETWEEN c.starts_at AND c.ends_at)::int active_campaigns,COALESCE(sum(c.redemption_count),0)::int redemptions FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1`,[id]);res.json({ok:true,stats:q.rows[0]});});
 app.get('/api/offers/nearby',async(req,res)=>{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'INVALID_LOCATION'});const q=await pool.query(`SELECT c.id,c.title,c.description,c.badge,c.coupon_code,c.ends_at,b.name,b.category,b.address,b.latitude,b.longitude,(6371000*2*asin(sqrt(power(sin(radians(b.latitude-$1)/2),2)+cos(radians($1))*cos(radians(b.latitude))*power(sin(radians(b.longitude-$2)/2),2)))) distance_m FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.is_active=true AND c.is_active=true AND now() BETWEEN c.starts_at AND c.ends_at AND b.latitude IS NOT NULL AND b.longitude IS NOT NULL ORDER BY distance_m LIMIT 50`,[lat,lon]);res.json({ok:true,offers:q.rows.filter(x=>Number(x.distance_m)<=10000)});});
};