const crypto=require('crypto');
module.exports=function registerBusinessRoutes(app,pool){
 const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
 const password=s=>crypto.scryptSync(String(s),String(process.env.BUSINESS_PASSWORD_SALT||'cepqar-business-v1'),64).toString('hex');
 const token=()=>crypto.randomBytes(32).toString('hex');
 async function auth(req,res){const raw=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!raw){res.status(401).json({error:'AUTH_REQUIRED'});return null;}const q=await pool.query("SELECT a.id FROM business_sessions s JOIN business_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>now()",[hash(raw)]);if(!q.rowCount){res.status(401).json({error:'INVALID_SESSION'});return null;}return q.rows[0].id;}
 app.post('/api/business/auth/register',async(req,res)=>{try{const {email,password:pw,name,category,phone,address,latitude,longitude}=req.body||{};if(!email||!pw||String(pw).length<8||!name||!category)return res.status(400).json({error:'INVALID_INPUT'});const client=await pool.connect();try{await client.query('BEGIN');const a=await client.query('INSERT INTO business_accounts(email,password_hash) VALUES(lower($1),$2) RETURNING id',[email,password(pw)]);const b=await client.query('INSERT INTO businesses(account_id,name,category,phone,address,latitude,longitude) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[a.rows[0].id,name,category,phone||null,address||null,Number.isFinite(Number(latitude))?Number(latitude):null,Number.isFinite(Number(longitude))?Number(longitude):null]);const raw=token();await client.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),a.rows[0].id]);await client.query('COMMIT');res.status(201).json({ok:true,token:raw,business:b.rows[0]});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({error:'EMAIL_EXISTS'});throw e;}finally{client.release();}}catch(e){console.error('business register',e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/business/auth/login',async(req,res)=>{try{const {email,password:pw}=req.body||{};const q=await pool.query('SELECT id,password_hash FROM business_accounts WHERE email=lower($1)',[email||'']);if(!q.rowCount||q.rows[0].password_hash!==password(pw||''))return res.status(401).json({error:'INVALID_CREDENTIALS'});const raw=token();await pool.query("INSERT INTO business_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[hash(raw),q.rows[0].id]);res.json({ok:true,token:raw});}catch(e){res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/business/me',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT * FROM businesses WHERE account_id=$1',[id]);res.json({ok:true,business:q.rows[0]||null});});
 app.get('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;const q=await pool.query('SELECT c.* FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.account_id=$1 ORDER BY c.created_at DESC',[id]);res.json({ok:true,campaigns:q.rows});});
 app.post('/api/business/campaigns',async(req,res)=>{const id=await auth(req,res);if(!id)return;try{const {title,description,badge,couponCode,startsAt,endsAt,dailyLimit,totalLimit}=req.body||{};if(!title||!startsAt||!endsAt)return res.status(400).json({error:'INVALID_INPUT'});const q=await pool.query('INSERT INTO business_campaigns(business_id,title,description,badge,coupon_code,starts_at,ends_at,daily_limit,total_limit) SELECT id,$2,$3,$4,$5,$6,$7,$8,$9 FROM businesses WHERE account_id=$1 RETURNING *',[id,title,description||'',badge||'',couponCode||null,startsAt,endsAt,dailyLimit||null,totalLimit||null]);res.status(201).json({ok:true,campaign:q.rows[0]});}catch(e){res.status(400).json({error:'CAMPAIGN_INVALID'});}});
 app.get('/api/offers/nearby',async(req,res)=>{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'INVALID_LOCATION'});const q=await pool.query(`SELECT c.id,c.title,c.description,c.badge,c.coupon_code,c.ends_at,b.name,b.category,b.address,b.latitude,b.longitude,(6371000*2*asin(sqrt(power(sin(radians(b.latitude-$1)/2),2)+cos(radians($1))*cos(radians(b.latitude))*power(sin(radians(b.longitude-$2)/2),2)))) distance_m FROM business_campaigns c JOIN businesses b ON b.id=c.business_id WHERE b.is_active=true AND c.is_active=true AND now() BETWEEN c.starts_at AND c.ends_at AND b.latitude IS NOT NULL AND b.longitude IS NOT NULL ORDER BY distance_m LIMIT 50`,[lat,lon]);res.json({ok:true,offers:q.rows.filter(x=>Number(x.distance_m)<=10000)});});
};