const crypto = require('crypto');

function normalizeTrMobile(raw) {
  let d=String(raw||'').replace(/\D/g,'');
  if(d.startsWith('90')&&d.length===12)d=d.slice(2); else if(d.startsWith('0')&&d.length===11)d=d.slice(1);
  return /^5\d{9}$/.test(d)?`+90${d}`:null;
}
module.exports=function registerDriverRoutes(app,pool){
 async function schema(){await pool.query(`
 CREATE TABLE IF NOT EXISTS vehicle_driver_invites(id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL,owner_id TEXT NOT NULL,token TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,accepted_by TEXT,accepted_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS vehicle_drivers(vehicle_id TEXT NOT NULL,owner_id TEXT NOT NULL,driver_user_id TEXT NOT NULL,driver_name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(vehicle_id,driver_user_id));
 ALTER TABLE vehicle_active_drivers ADD COLUMN IF NOT EXISTS driver_user_id TEXT;
 ALTER TABLE vehicle_notifications ADD COLUMN IF NOT EXISTS recipient_user_id TEXT;
 CREATE INDEX IF NOT EXISTS idx_vehicle_notifications_recipient ON vehicle_notifications(recipient_user_id,created_at DESC);
 `);}
 async function owned(ownerId,vehicleId){const r=await pool.query('SELECT id FROM vehicles WHERE id=$1 AND owner_id=$2',[vehicleId,ownerId]);return r.rows[0];}
 app.post('/api/owner/vehicles/:vehicleId/driver-invites',async(req,res)=>{const o=String(req.headers['x-owner-id']||'').trim();if(!o)return res.status(401).json({error:'OWNER_REQUIRED'});try{await schema();if(!await owned(o,req.params.vehicleId))return res.status(404).json({error:'NOT_FOUND'});const id=crypto.randomUUID(),token=crypto.randomBytes(24).toString('hex');await pool.query(`INSERT INTO vehicle_driver_invites(id,vehicle_id,owner_id,token,expires_at) VALUES($1,$2,$3,$4,NOW()+INTERVAL '7 days')`,[id,req.params.vehicleId,o,token]);return res.status(201).json({ok:true,token,inviteUrl:`https://queensho.github.io/HeyCar/?driverInvite=${token}`,expiresInDays:7});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/driver/invites/:token',async(req,res)=>{try{await schema();const r=await pool.query(`SELECT i.token,i.expires_at,i.accepted_at,v.plate,v.make,v.model,u.display_name owner_name FROM vehicle_driver_invites i JOIN vehicles v ON v.id=i.vehicle_id JOIN users u ON u.id=i.owner_id WHERE i.token=$1 LIMIT 1`,[req.params.token]);if(!r.rows.length)return res.status(404).json({error:'NOT_FOUND'});const x=r.rows[0];if(x.accepted_at)return res.status(410).json({error:'INVITE_USED'});if(new Date(x.expires_at)<=new Date())return res.status(410).json({error:'INVITE_EXPIRED'});res.json({ok:true,invite:x});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/driver/invites/:token/accept',async(req,res)=>{const phone=normalizeTrMobile(req.body?.phone),password=String(req.body?.password||''),name=String(req.body?.displayName||'').trim().slice(0,80);if(!phone||password.length<6||!name)return res.status(400).json({error:'INVALID_INPUT'});const c=await pool.connect();try{await schema();await c.query('BEGIN');const ir=await c.query(`SELECT * FROM vehicle_driver_invites WHERE token=$1 AND accepted_at IS NULL AND expires_at>NOW() FOR UPDATE`,[req.params.token]);if(!ir.rows.length){await c.query('ROLLBACK');return res.status(410).json({error:'INVITE_INVALID'});}let ur=await c.query(`SELECT id,display_name,status FROM users WHERE phone=$1 AND password_hash=crypt($2,password_hash) LIMIT 1`,[phone,password]);let user;if(ur.rows.length){user=ur.rows[0];if(user.status!=='active'){await c.query('ROLLBACK');return res.status(403).json({error:'USER_SUSPENDED'});}}else{const exists=await c.query('SELECT 1 FROM users WHERE phone=$1',[phone]);if(exists.rows.length){await c.query('ROLLBACK');return res.status(401).json({error:'PASSWORD_INVALID'});}ur=await c.query(`INSERT INTO users(phone,display_name,password_hash,role,status) VALUES($1,$2,crypt($3,gen_salt('bf',12)),'user','active') RETURNING id,display_name,status`,[phone,name,password]);user=ur.rows[0];}const i=ir.rows[0];await c.query(`INSERT INTO vehicle_drivers(vehicle_id,owner_id,driver_user_id,driver_name) VALUES($1,$2,$3,$4) ON CONFLICT(vehicle_id,driver_user_id) DO UPDATE SET driver_name=EXCLUDED.driver_name`,[i.vehicle_id,i.owner_id,user.id,user.display_name||name]);await c.query(`UPDATE vehicle_driver_invites SET accepted_by=$2,accepted_at=NOW() WHERE id=$1`,[i.id,user.id]);await c.query('COMMIT');res.json({ok:true,user:{id:user.id,displayName:user.display_name||name},vehicleId:i.vehicle_id});}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'SERVER_ERROR'});}finally{c.release();}});
 app.get('/api/driver/vehicles',async(req,res)=>{const u=String(req.headers['x-user-id']||'').trim();if(!u)return res.status(401).json({error:'USER_REQUIRED'});try{await schema();const r=await pool.query(`SELECT d.vehicle_id,d.driver_name,v.plate,v.make,v.model,(a.driver_user_id=$1 AND (a.active_until IS NULL OR a.active_until>NOW())) active,a.active_until FROM vehicle_drivers d JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN vehicle_active_drivers a ON a.vehicle_id=d.vehicle_id WHERE d.driver_user_id=$1 ORDER BY d.created_at DESC`,[u]);res.json({ok:true,vehicles:r.rows});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.put('/api/driver/vehicles/:vehicleId/active',async(req,res)=>{const u=String(req.headers['x-user-id']||'').trim(),hours=req.body?.hours===null?null:Number(req.body?.hours);if(!u||!(hours===null||[1,3,6,12,24].includes(hours)))return res.status(400).json({error:'INVALID_REQUEST'});try{await schema();const d=await pool.query(`SELECT owner_id,driver_name FROM vehicle_drivers WHERE vehicle_id=$1 AND driver_user_id=$2`,[req.params.vehicleId,u]);if(!d.rows.length)return res.status(403).json({error:'NOT_AUTHORIZED'});const x=d.rows[0];await pool.query(`INSERT INTO vehicle_active_drivers(vehicle_id,owner_id,driver_name,driver_user_id,active_until) VALUES($1,$2,$3,$4,CASE WHEN $5::int IS NULL THEN NULL ELSE NOW()+($5*INTERVAL '1 hour') END) ON CONFLICT(vehicle_id) DO UPDATE SET owner_id=EXCLUDED.owner_id,driver_name=EXCLUDED.driver_name,driver_user_id=EXCLUDED.driver_user_id,active_until=EXCLUDED.active_until,updated_at=NOW()`,[req.params.vehicleId,x.owner_id,x.driver_name,u,hours]);res.json({ok:true,active:true});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.delete('/api/driver/vehicles/:vehicleId/active',async(req,res)=>{const u=String(req.headers['x-user-id']||'').trim();try{await schema();await pool.query('DELETE FROM vehicle_active_drivers WHERE vehicle_id=$1 AND driver_user_id=$2',[req.params.vehicleId,u]);res.json({ok:true,active:false});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/driver/notifications',async(req,res)=>{const u=String(req.headers['x-user-id']||'').trim();if(!u)return res.status(401).json({error:'USER_REQUIRED'});try{await schema();const r=await pool.query(`SELECT n.*,v.plate,v.make,v.model FROM vehicle_notifications n JOIN vehicles v ON v.id=n.vehicle_id WHERE n.recipient_user_id=$1 ORDER BY n.created_at DESC LIMIT 100`,[u]);res.json({ok:true,notifications:r.rows});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
};
