const express=require('express');
module.exports=function registerMaintenanceRoutes(app,pool){
 const ownerId=req=>String(req.headers['x-owner-id']||'').trim();
 async function vehicle(req,res){const o=ownerId(req),v=String(req.params.vehicleId||'');if(!o){res.status(401).json({error:'OWNER_REQUIRED'});return null;}const r=await pool.query('SELECT id,plate,make,model,owner_id FROM vehicles WHERE id::text=$1 AND owner_id::text=$2 LIMIT 1',[v,o]);if(!r.rows.length){res.status(403).json({error:'FORBIDDEN'});return null;}return r.rows[0];}
 async function premium(o){try{const r=await pool.query(`SELECT COALESCE((to_jsonb(u)->>'premium')::boolean,false) premium FROM users u WHERE id::text=$1 LIMIT 1`,[o]);return r.rows[0]?.premium===true;}catch(_){return false;}}
 app.get('/api/vehicles/:vehicleId/maintenance',async(req,res)=>{try{const v=await vehicle(req,res);if(!v)return;const o=ownerId(req),isPremium=await premium(o);const km=await pool.query('SELECT current_km,updated_at FROM vehicle_maintenance_state WHERE vehicle_id=$1 LIMIT 1',[String(v.id)]);const records=await pool.query(`SELECT id,service_date,mileage,items,notes,total_cost,invoice_url,next_service_km,created_at FROM vehicle_maintenance_records WHERE vehicle_id=$1 ORDER BY mileage DESC,service_date DESC`,[String(v.id)]);const currentKm=Number(km.rows[0]?.current_km||records.rows[0]?.mileage||0);const upcoming=records.rows.filter(x=>Number(x.next_service_km)>0).map(x=>{const remaining=Number(x.next_service_km)-currentKm;return {recordId:x.id,label:Array.isArray(x.items)&&x.items.length?x.items[0]:'Bakım',dueKm:Number(x.next_service_km),remainingKm:remaining,status:remaining<=0?'due':remaining<=1000?'soon':'ok'};}).sort((a,b)=>a.dueKm-b.dueKm);const nearest=upcoming[0];const reminderDays=nearest&&nearest.remainingKm<=1000?15:30;const lastKmUpdate=km.rows[0]?.updated_at||records.rows[0]?.created_at||null;const nextKmReminderAt=lastKmUpdate?new Date(new Date(lastKmUpdate).getTime()+reminderDays*86400000).toISOString():new Date().toISOString();const kmReminderDue=!lastKmUpdate||Date.now()>=new Date(nextKmReminderAt).getTime();res.json({ok:true,premium:isPremium,vehicle:v,currentKm,records:records.rows,upcoming,kmReminder:{due:kmReminderDue,intervalDays:reminderDays,lastUpdatedAt:lastKmUpdate,nextReminderAt:nextKmReminderAt,message:'Güncel kilometren kaç?'}});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.put('/api/vehicles/:vehicleId/maintenance/km',express.json(),async(req,res)=>{try{const v=await vehicle(req,res);if(!v)return;if(!await premium(ownerId(req)))return res.status(402).json({error:'PREMIUM_REQUIRED'});const km=Math.max(0,Math.round(Number(req.body.currentKm||0)));await pool.query(`INSERT INTO vehicle_maintenance_state(vehicle_id,current_km,updated_at) VALUES($1,$2,NOW()) ON CONFLICT(vehicle_id) DO UPDATE SET current_km=EXCLUDED.current_km,updated_at=NOW()`,[String(v.id),km]);res.json({ok:true,currentKm:km});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/vehicles/:vehicleId/maintenance',express.json({limit:'1mb'}),async(req,res)=>{try{const v=await vehicle(req,res);if(!v)return;if(!await premium(ownerId(req)))return res.status(402).json({error:'PREMIUM_REQUIRED'});const mileage=Math.max(0,Math.round(Number(req.body.mileage||0))),items=Array.isArray(req.body.items)?req.body.items.map(x=>String(x).slice(0,80)).slice(0,12):[],interval=Math.max(0,Math.round(Number(req.body.intervalKm||0))),next=interval?mileage+interval:null;if(!mileage||!items.length)return res.status(400).json({error:'REQUIRED_FIELDS_MISSING'});const r=await pool.query(`INSERT INTO vehicle_maintenance_records(vehicle_id,owner_id,service_date,mileage,items,notes,total_cost,invoice_url,next_service_km) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9) RETURNING *`,[String(v.id),ownerId(req),req.body.serviceDate||new Date().toISOString().slice(0,10),mileage,JSON.stringify(items),String(req.body.notes||'').slice(0,1000),Number(req.body.totalCost||0),req.body.invoiceUrl?String(req.body.invoiceUrl).slice(0,1000):null,next]);await pool.query(`INSERT INTO vehicle_maintenance_state(vehicle_id,current_km,updated_at) VALUES($1,$2,NOW()) ON CONFLICT(vehicle_id) DO UPDATE SET current_km=GREATEST(vehicle_maintenance_state.current_km,EXCLUDED.current_km),updated_at=NOW()`,[String(v.id),mileage]);res.status(201).json({ok:true,record:r.rows[0]});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
};
