const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const registerNotificationRoutes = require('./notification-routes');
const { registerOwnerCorrectionRoutes } = require('./correction-routes');
const registerCallRoutes = require('./call-routes');
const registerActiveDriverRoutes = require('./active-driver-routes');
const registerDriverRoutes = require('./driver-routes');
const registerDndRoutes = require('./dnd-routes');
const registerMaintenanceRoutes = require('./maintenance-routes');
const registerVehicleReminderRoutes = require('./vehicle-reminder-routes');
function normalizeToken(raw){return String(raw||'').trim().toUpperCase();}
function validHexColor(value){return /^#[0-9A-Fa-f]{6}$/.test(String(value||''));}
module.exports=function registerQrRoutes(app,pool){
 registerNotificationRoutes(app,pool);registerOwnerCorrectionRoutes(app,pool);registerCallRoutes(app,pool);registerActiveDriverRoutes(app,pool);registerDriverRoutes(app,pool);registerDndRoutes(app,pool);registerMaintenanceRoutes(app,pool);registerVehicleReminderRoutes(app,pool);
 const uploadDir=path.join(__dirname,'uploads','public-themes');fs.mkdirSync(uploadDir,{recursive:true});app.use('/uploads/public-themes',express.static(uploadDir,{maxAge:'7d'}));
 async function ownerCanEdit(vehicleId,ownerId){if(!vehicleId||!ownerId)return false;const c=await pool.query('SELECT 1 FROM vehicles WHERE id=$1 AND owner_id=$2 LIMIT 1',[vehicleId,ownerId]);return c.rows.length>0;}
 app.get('/api/qr/:token',async(req,res)=>{const token=normalizeToken(req.params.token);if(!token)return res.status(400).json({error:'TOKEN_REQUIRED'});try{const r=await pool.query(`SELECT q.token,q.status,q.activated_at,v.id AS vehicle_id,v.plate,v.make,v.model,v.color,t.preset,t.accent_color,t.background_path,t.public_message,t.overlay_strength FROM qr_tags q LEFT JOIN vehicles v ON v.id=q.vehicle_id LEFT JOIN vehicle_public_themes t ON t.vehicle_id=v.id WHERE q.token=$1 LIMIT 1`,[token]);if(!r.rows.length)return res.status(404).json({error:'QR_NOT_FOUND'});const x=r.rows[0];res.json({ok:true,token:x.token,status:x.status,vehicle:x.plate?{id:x.vehicle_id,plate:x.plate,make:x.make,model:x.model,color:x.color}:null,theme:{preset:x.preset||'classic',accentColor:x.accent_color||'#FCA311',backgroundUrl:x.background_path||null,publicMessage:x.public_message||'Numaram gizli, yolun açık.',overlayStrength:Number(x.overlay_strength??.72)},activatedAt:x.activated_at});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.get('/api/vehicles/:vehicleId/public-theme',async(req,res)=>{const v=String(req.params.vehicleId||''),o=String(req.headers['x-owner-id']||'');try{if(!await ownerCanEdit(v,o))return res.status(403).json({error:'FORBIDDEN'});const r=await pool.query('SELECT preset,accent_color,background_path,public_message,overlay_strength FROM vehicle_public_themes WHERE vehicle_id=$1 LIMIT 1',[v]);const x=r.rows[0]||{};res.json({ok:true,theme:{preset:x.preset||'classic',accentColor:x.accent_color||'#FCA311',backgroundUrl:x.background_path||null,publicMessage:x.public_message||'Numaram gizli, yolun açık.',overlayStrength:Number(x.overlay_strength??.72)}});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.put('/api/vehicles/:vehicleId/public-theme',async(req,res)=>{const v=String(req.params.vehicleId||''),o=String(req.headers['x-owner-id']||''),preset=String(req.body.preset||'classic').slice(0,32),accent=validHexColor(req.body.accentColor)?req.body.accentColor.toUpperCase():'#FCA311',msg=String(req.body.publicMessage||'Numaram gizli, yolun açık.').slice(0,120),overlay=Math.max(0,Math.min(1,Number(req.body.overlayStrength??.72)));try{if(!await ownerCanEdit(v,o))return res.status(403).json({error:'FORBIDDEN'});const r=await pool.query(`INSERT INTO vehicle_public_themes(vehicle_id,preset,accent_color,public_message,overlay_strength) VALUES($1,$2,$3,$4,$5) ON CONFLICT(vehicle_id) DO UPDATE SET preset=EXCLUDED.preset,accent_color=EXCLUDED.accent_color,public_message=EXCLUDED.public_message,overlay_strength=EXCLUDED.overlay_strength,updated_at=NOW() RETURNING preset,accent_color,background_path,public_message,overlay_strength`,[v,preset,accent,msg,overlay]);res.json({ok:true,theme:r.rows[0]});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/vehicles/:vehicleId/public-theme/background',express.raw({type:['image/jpeg','image/png','image/webp'],limit:'5mb'}),async(req,res)=>{const v=String(req.params.vehicleId||''),o=String(req.headers['x-owner-id']||'');try{if(!await ownerCanEdit(v,o))return res.status(403).json({error:'FORBIDDEN'});if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).json({error:'IMAGE_REQUIRED'});const type=String(req.headers['content-type']||'').split(';')[0],ext=type==='image/png'?'.png':type==='image/webp'?'.webp':'.jpg',filename=`${v}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}${ext}`;fs.writeFileSync(path.join(uploadDir,filename),req.body);const bg=`/uploads/public-themes/${filename}`;await pool.query(`INSERT INTO vehicle_public_themes(vehicle_id,background_path) VALUES($1,$2) ON CONFLICT(vehicle_id) DO UPDATE SET background_path=EXCLUDED.background_path,updated_at=NOW()`,[v,bg]);res.json({ok:true,backgroundUrl:bg});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.delete('/api/vehicles/:vehicleId/public-theme/background',async(req,res)=>{const v=String(req.params.vehicleId||''),o=String(req.headers['x-owner-id']||'');try{if(!await ownerCanEdit(v,o))return res.status(403).json({error:'FORBIDDEN'});await pool.query(`INSERT INTO vehicle_public_themes(vehicle_id,background_path) VALUES($1,NULL) ON CONFLICT(vehicle_id) DO UPDATE SET background_path=NULL,updated_at=NOW()`,[v]);res.json({ok:true});}catch(e){console.error(e);res.status(500).json({error:'SERVER_ERROR'});}});
 app.post('/api/qr/activate',async(req,res)=>{const token=normalizeToken(req.body.token),o=String(req.body.ownerId||req.headers['x-owner-id']||'').trim(),v=String(req.body.vehicleId||'').trim();if(!token||!v)return res.status(400).json({error:'REQUIRED_FIELDS_MISSING'});if(!o)return res.status(401).json({error:'OWNER_REQUIRED'});const c=await pool.connect();try{await c.query('BEGIN');const vr=await c.query(`SELECT v.id,v.owner_id,v.plate,v.make,v.model,v.color,u.status owner_status FROM vehicles v JOIN users u ON u.id=v.owner_id WHERE v.id=$1 LIMIT 1 FOR UPDATE OF v`,[v]);if(!vr.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'VEHICLE_NOT_FOUND'});}const vehicle=vr.rows[0];if(String(vehicle.owner_id)!==o||vehicle.owner_status!=='active'){await c.query('ROLLBACK');return res.status(403).json({error:'FORBIDDEN'});}const qr=await c.query('SELECT id,token,status,vehicle_id FROM qr_tags WHERE token=$1 FOR UPDATE',[token]);if(!qr.rows.length){await c.query('ROLLBACK');return res.status(404).json({error:'QR_NOT_FOUND'});}const q=qr.rows[0];if(q.status==='disabled'){await c.query('ROLLBACK');return res.status(409).json({error:'QR_DISABLED'});}if(q.vehicle_id||q.status==='active'){await c.query('ROLLBACK');return res.status(409).json({error:'QR_ALREADY_BOUND'});}const ex=await c.query(`SELECT token FROM qr_tags WHERE vehicle_id=$1 AND status='active' LIMIT 1`,[v]);if(ex.rows.length){await c.query('ROLLBACK');return res.status(409).json({error:'VEHICLE_ALREADY_HAS_QR'});}await c.query(`UPDATE qr_tags SET status='active',vehicle_id=$1,activated_at=NOW() WHERE id=$2`,[v,q.id]);await c.query('COMMIT');res.json({ok:true,token,status:'active',vehicle});}catch(e){await c.query('ROLLBACK');console.error(e);res.status(500).json({error:'SERVER_ERROR'});}finally{c.release();}});
};
