import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';

class ActiveDriverCard extends StatefulWidget{const ActiveDriverCard({super.key});@override State<ActiveDriverCard> createState()=>_S();}
class _S extends State<ActiveDriverCard>{static const api='https://heycar-api-185-165-46-213.nip.io';bool loading=false,active=false;String? name;DateTime? until;
String get vehicleId=>QrDraft.vehicleId.trim().isEmpty?OnboardingDraft.vehicleId.trim():QrDraft.vehicleId.trim();String get ownerId=>OnboardingDraft.userId.trim();
@override void initState(){super.initState();load();}
Future<void> load()async{if(vehicleId.isEmpty||ownerId.isEmpty)return;try{final r=await http.get(Uri.parse('$api/api/owner/vehicles/$vehicleId/active-driver'),headers:{'x-owner-id':ownerId});if(r.statusCode==200){final j=jsonDecode(r.body);if(mounted)setState((){active=j['active']==true;name=j['driverName']?.toString();until=DateTime.tryParse(j['activeUntil']?.toString()??'')?.toLocal();});}}catch(_){}}
Future<void> invite()async{setState(()=>loading=true);try{final r=await http.post(Uri.parse('$api/api/owner/vehicles/$vehicleId/driver-invites'),headers:{'Content-Type':'application/json','x-owner-id':ownerId});final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300){final url=j['inviteUrl'].toString();if(!mounted)return;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sürücü daveti hazır',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Bu linki aile üyenle paylaş. Cepqar’da açınca kendi hesabıyla araca katılacak.'),const SizedBox(height:14),SelectableText(url),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){Clipboard.setData(ClipboardData(text:url));ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Davet linki kopyalandı')));},icon:const Icon(Icons.copy),label:const Text('Davet Linkini Kopyala'))),const SizedBox(height:8),const Text('Davet 7 gün geçerlidir.',style:TextStyle(color:Colors.white60))])));}else{throw Exception();}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sürücü daveti oluşturulamadı.')));}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF101A30),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF27355D))),child:Column(children:[Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:const Color(0xFF8B5CFF).withValues(alpha:.16),borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.group_rounded,color:Color(0xFF8B5CFF))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Flexible(child:Text('Şu an kim kullanıyor?',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:15))),const SizedBox(width:7),Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:3),decoration:BoxDecoration(color:const Color(0xFF8B5CFF).withValues(alpha:.2),borderRadius:BorderRadius.circular(8)),child:const Text('PREMIUM',style:TextStyle(color:Color(0xFFB99CFF),fontSize:9,fontWeight:FontWeight.w900)))]),const SizedBox(height:4),Text(active?'Aktif sürücü: ${name??''}${until==null?'':' • ${until!.hour.toString().padLeft(2,'0')}:${until!.minute.toString().padLeft(2,'0')}’a kadar'}':'Aile üyesini davet et; QR bildirimleri aktif sürücüye gitsin.',style:const TextStyle(color:Color(0xFFA7B0C7),fontSize:12))]))]),const SizedBox(height:13),SizedBox(width:double.infinity,height:44,child:FilledButton.icon(onPressed:loading?null:invite,style:FilledButton.styleFrom(backgroundColor:const Color(0xFF8B5CFF),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(14))),icon:const Icon(Icons.person_add_alt_1_rounded),label:Text(loading?'Bekle...':'Sürücü Davet Et',style:const TextStyle(fontWeight:FontWeight.w900))))]));}
