import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';
class ActiveDriverCard extends StatefulWidget{const ActiveDriverCard({super.key});@override State<ActiveDriverCard> createState()=>_S();}
class _S extends State<ActiveDriverCard>{static const api='https://heycar-api-185-165-46-213.nip.io';bool loading=false,active=false;String? name;DateTime? until;List drivers=[];String get vehicleId=>QrDraft.vehicleId.trim().isEmpty?OnboardingDraft.vehicleId.trim():QrDraft.vehicleId.trim();String get ownerId=>OnboardingDraft.userId.trim();@override void initState(){super.initState();load();}
Future<void> load()async{if(vehicleId.isEmpty||ownerId.isEmpty)return;try{final rs=await Future.wait([http.get(Uri.parse('$api/api/owner/vehicles/$vehicleId/active-driver'),headers:{'x-owner-id':ownerId}),http.get(Uri.parse('$api/api/owner/vehicles/$vehicleId/drivers'),headers:{'x-owner-id':ownerId})]);if(mounted)setState((){if(rs[0].statusCode==200){final j=jsonDecode(rs[0].body);active=j['active']==true;name=j['driverName']?.toString();until=DateTime.tryParse(j['activeUntil']?.toString()??'')?.toLocal();}drivers=rs[1].statusCode==200?(jsonDecode(rs[1].body)['drivers']??[]):[];});}catch(_){}}
Future<void> invite()async{setState(()=>loading=true);try{final r=await http.post(Uri.parse('$api/api/owner/vehicles/$vehicleId/driver-invites'),headers:{'Content-Type':'application/json','x-owner-id':ownerId});final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300){final code=j['code'].toString();if(!mounted)return;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sürücü davet kodu',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Bu kodu aile üyenle paylaş. Cepqar giriş ekranında “Davet kodum var” seçeneğinden girebilir.'),const SizedBox(height:18),Center(child:SelectableText(code,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900,letterSpacing:3))),const SizedBox(height:8),const Center(child:Text('Kod 7 gün geçerlidir.',style:TextStyle(color:Color(0xFFA7B0C7)))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){Clipboard.setData(ClipboardData(text:code));ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Davet kodu kopyalandı')));},icon:const Icon(Icons.copy),label:const Text('Kodu Kopyala')))])));}else{throw Exception();}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sürücü daveti oluşturulamadı.')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> choose()async{await load();if(!mounted)return;if(drivers.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Önce bir sürücü davet et.')));return;}final d=await showModalBottomSheet<Map>(context:context,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const ListTile(title:Text('Şu an kim kullanıyor?',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('Araç sahibinin yetkili sürücülerinden birini seç.')),for(final x in drivers)ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(x['driver_name'].toString()),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.pop(c,x))])));if(d==null||!mounted)return;final h=await showModalBottomSheet<dynamic>(context:context,builder:(c)=>SafeArea(child:Wrap(children:[ListTile(title:Text('${d['driver_name']} ne kadar kullanacak?',style:const TextStyle(fontWeight:FontWeight.w900))),for(final x in [1,3,6,12,24])ListTile(title:Text('$x saat'),onTap:()=>Navigator.pop(c,x)),ListTile(title:const Text('Ben kapatana kadar'),onTap:()=>Navigator.pop(c,'forever'))])));if(h==null)return;setState(()=>loading=true);try{final r=await http.put(Uri.parse('$api/api/owner/vehicles/$vehicleId/selected-driver'),headers:{'Content-Type':'application/json','x-owner-id':ownerId},body:jsonEncode({'driverUserId':d['driver_user_id'],'hours':h=='forever'?null:h}));if(r.statusCode<200||r.statusCode>=300)throw Exception();await load();}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Aktif sürücü seçilemedi.')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> stop()async{setState(()=>loading=true);try{await http.delete(Uri.parse('$api/api/owner/vehicles/$vehicleId/selected-driver'),headers:{'x-owner-id':ownerId});await load();}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF101A30),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF27355D))),child:Column(children:[Row(children:[const CircleAvatar(radius:24,child:Icon(Icons.group_rounded)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Şu an kim kullanıyor?  PREMIUM',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(active?'${name??''} aracı kullanıyor${until==null?'':' • ${until!.hour.toString().padLeft(2,'0')}:${until!.minute.toString().padLeft(2,'0')}’a kadar'}':'Araç sahibi aktif sürücüyü seçer.',style:const TextStyle(color:Color(0xFFA7B0C7),fontSize:12))]))]),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:loading?null:invite,icon:const Icon(Icons.person_add),label:const Text('Sürücü Davet Et'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:loading?null:(active?stop:choose),child:Text(active?'Sürüşü Bitir':'Sürücü Seç')))])]));}
