import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';
import 'owner_auth.dart';
class ActiveDriverCard extends StatefulWidget{const ActiveDriverCard({super.key});@override State<ActiveDriverCard> createState()=>_S();}
class _S extends State<ActiveDriverCard>{static const api='https://heycar-api-185-165-46-213.nip.io';bool loading=true,active=false,premium=false;String? name;DateTime? until;List drivers=[];String get vehicleId=>QrDraft.vehicleId.trim().isEmpty?OnboardingDraft.vehicleId.trim():QrDraft.vehicleId.trim();String get ownerId=>OnboardingDraft.userId.trim();@override void initState(){super.initState();load();}
Future<void> load()async{if(ownerId.isEmpty){if(mounted)setState(()=>loading=false);return;}try{final futures=<Future<http.Response>>[OwnerHttp.get(Uri.parse('$api/api/owner/vehicles'),json:false)];if(vehicleId.isNotEmpty){futures.add(OwnerHttp.get(Uri.parse('$api/api/owner/vehicles/$vehicleId/active-driver'),json:false));futures.add(OwnerHttp.get(Uri.parse('$api/api/owner/vehicles/$vehicleId/drivers'),json:false));}final rs=await Future.wait(futures);if(!mounted)return;setState((){if(rs[0].statusCode==200){final u=jsonDecode(rs[0].body);premium=u is Map&&u['premium']==true;}if(rs.length>1&&rs[1].statusCode==200){final j=jsonDecode(rs[1].body);active=j['active']==true;name=j['driverName']?.toString();until=DateTime.tryParse(j['activeUntil']?.toString()??'')?.toLocal();}drivers=rs.length>2&&rs[2].statusCode==200?(jsonDecode(rs[2].body)['drivers']??[]):[];loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
void locked(){showDialog(context:context,builder:(_)=>AlertDialog(backgroundColor:const Color(0xFF101A30),title:const Row(children:[Icon(Icons.lock_rounded,color:Color(0xFF8B5CFF)),SizedBox(width:8),Text('Premium özellik',style:TextStyle(color:Colors.white))]),content:const Text('Yetkili sürücü davet etme ve aktif sürücü seçme Premium üyeler için kullanılabilir.',style:TextStyle(color:Color(0xFFA7B0C7))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Tamam'))]));}
Future<void> invite()async{if(!premium){locked();return;}setState(()=>loading=true);try{final r=await OwnerHttp.post(Uri.parse('$api/api/owner/vehicles/$vehicleId/driver-invites'));final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300){final code=j['code'].toString();if(!mounted)return;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sürücü davet kodu',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Bu kodu aile üyenle paylaş. HeyCar giriş ekranında “Davet kodum var” seçeneğinden girebilir.'),const SizedBox(height:18),Center(child:SelectableText(code,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900,letterSpacing:3))),const SizedBox(height:8),const Center(child:Text('Kod 7 gün geçerlidir.',style:TextStyle(color:Color(0xFFA7B0C7)))),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:(){Clipboard.setData(ClipboardData(text:code));ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sürücü davet kodu kopyalandı')));},icon:const Icon(Icons.copy),label:const Text('Kodu Kopyala')))])));}else{throw Exception();}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sürücü daveti oluşturulamadı.')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> choose()async{if(!premium){locked();return;}await load();if(!mounted)return;if(drivers.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Önce bir sürücü davet et.')));return;}final d=await showModalBottomSheet<Map>(context:context,builder:(c)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const ListTile(title:Text('Şu an kim kullanıyor?',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('Araç sahibinin yetkili sürücülerinden birini seç.')),for(final x in drivers)ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(x['driver_name'].toString()),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.pop(c,x))])));if(d==null||!mounted)return;final h=await showModalBottomSheet<dynamic>(context:context,builder:(c)=>SafeArea(child:Wrap(children:[ListTile(title:Text('${d['driver_name']} ne kadar kullanacak?',style:const TextStyle(fontWeight:FontWeight.w900))),for(final x in [1,3,6,12,24])ListTile(title:Text('$x saat'),onTap:()=>Navigator.pop(c,x)),ListTile(title:const Text('Ben kapatana kadar'),onTap:()=>Navigator.pop(c,'forever'))])));if(h==null)return;setState(()=>loading=true);try{final r=await OwnerHttp.put(Uri.parse('$api/api/owner/vehicles/$vehicleId/selected-driver'),body:jsonEncode({'driverUserId':d['driver_user_id'],'hours':h=='forever'?null:h}));if(r.statusCode<200||r.statusCode>=300)throw Exception();await load();}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Aktif sürücü seçilemedi.')));}finally{if(mounted)setState(()=>loading=false);}}
Future<void> stop()async{if(!premium){locked();return;}setState(()=>loading=true);try{await OwnerHttp.delete(Uri.parse('$api/api/owner/vehicles/$vehicleId/selected-driver'),json:false);await load();}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext c)=>InkWell(onTap:premium?null:locked,borderRadius:BorderRadius.circular(20),child:Container(width:double.infinity,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF6F3DE8),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF8F6BFF))),child:Column(children:[Row(children:[const CircleAvatar(radius:24,backgroundColor:Color(0xFFF3EEFF),child:Icon(Icons.group_rounded,color:Color(0xFF4D347C))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Flexible(child:Text('Şu an kim kullanıyor?',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900))),if(!loading&&!premium)...[const SizedBox(width:7),const Icon(Icons.lock_rounded,color:Colors.white,size:14),const SizedBox(width:3),const Text('Premium',style:TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.w900))]]),const SizedBox(height:4),Text(active&&premium?'${name??''} aracı kullanıyor${until==null?'':' • ${until!.hour.toString().padLeft(2,'0')}:${until!.minute.toString().padLeft(2,'0')}’a kadar'}':'Araç sahibi aktif sürücüyü seçer.',style:const TextStyle(color:Colors.white70,fontSize:12))]))]),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(style:OutlinedButton.styleFrom(foregroundColor:Colors.white,disabledForegroundColor:Colors.white54,side:const BorderSide(color:Colors.white70)),onPressed:loading?null:(premium?invite:locked),icon:Icon(premium?Icons.person_add:Icons.lock_rounded),label:Text(premium?'Sürücü Davet Et':'Premium'))),const SizedBox(width:8),Expanded(child:FilledButton(style:FilledButton.styleFrom(backgroundColor:const Color(0xFF5A4D86),foregroundColor:Colors.white,disabledBackgroundColor:const Color(0xFF5A4D86),disabledForegroundColor:Colors.white54),onPressed:loading?null:(premium?(active?stop:choose):locked),child:Text(premium?(active?'Sürüşü Bitir':'Sürücü Seç'):'Premium')))])])));}
