import 'package:flutter/material.dart';

const _bg=Color(0xFF060A18),_card=Color(0xFF0C1226),_card2=Color(0xFF111A31),_line=Color(0xFF242D49),_muted=Color(0xFF8993AD),_purple=Color(0xFFA72BFF),_green=Color(0xFF28F39A),_blue=Color(0xFF499DFF),_amber=Color(0xFFFFBF55);

Map<String,dynamic> _map(dynamic x)=>x is Map?Map<String,dynamic>.from(x):<String,dynamic>{};
List<Map<String,dynamic>> _list(dynamic x)=>x is List?x.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():<Map<String,dynamic>>[];
double _num(dynamic x)=>x is num?x.toDouble():double.tryParse((x??0).toString())??0;
String _money(dynamic x){final n=_num(x);return '₺'+n.toStringAsFixed(n%1==0?0:2);}
String _date(dynamic raw){if(raw==null||raw.toString().isEmpty)return '-';final d=DateTime.tryParse(raw.toString())?.toLocal();if(d==null)return raw.toString();String p(int n)=>n.toString().padLeft(2,'0');return p(d.day)+'.'+p(d.month)+'.'+d.year.toString()+' '+p(d.hour)+':'+p(d.minute);}
String _status(String s)=>switch(s){'approved'=>'Onaylı','pending'=>'Bekliyor','rejected'=>'Reddedildi','inactive'=>'Pasif','redeemed'=>'Kullanıldı','cancelled'=>'İptal',_=>s};
Color _statusColor(String s)=>switch(s){'approved'||'redeemed'=>_green,'pending'=>_amber,'rejected'||'cancelled'||'inactive'=>Colors.redAccent,_=>_muted};

Widget _hero(String title,String subtitle,IconData icon,Color color)=>Container(
  padding:const EdgeInsets.all(16),
  decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF0C1530),Color(0xFF180A29)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:color.withValues(alpha:.32))),
  child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:color.withValues(alpha:.12),shape:BoxShape.circle),child:Icon(icon,color:color,size:25)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:2),Text(subtitle,style:const TextStyle(color:_muted,fontSize:11.5))]))]),
);
Widget _pill(String text,Color color)=>Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:color.withValues(alpha:.12),borderRadius:BorderRadius.circular(20),border:Border.all(color:color.withValues(alpha:.28))),child:Text(text,style:TextStyle(color:color,fontSize:9.5,fontWeight:FontWeight.w900)));
Widget _metric(String value,String label,IconData icon,Color color)=>Container(height:90,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(17),border:Border.all(color:color.withValues(alpha:.25))),child:Row(children:[Icon(icon,color:color,size:25),const SizedBox(width:9),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(value,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),Text(label,maxLines:2,style:const TextStyle(color:_muted,fontSize:10.5,fontWeight:FontWeight.w700))]))]));
Widget _empty(String text)=>Container(width:double.infinity,padding:const EdgeInsets.symmetric(vertical:42,horizontal:16),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(18),border:Border.all(color:_line)),child:Column(children:[const Icon(Icons.inbox_outlined,color:_muted,size:38),const SizedBox(height:8),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:_muted,fontWeight:FontWeight.w700))]));

class AdminBusinessesPage extends StatelessWidget{
  const AdminBusinessesPage({super.key,required this.data,required this.loading,required this.error,required this.status,required this.onStatus,required this.onUpdate,required this.onRefresh});
  final Map<String,dynamic> data; final bool loading; final String? error; final String status;
  final Future<void> Function(String) onStatus; final Future<void> Function(String,Map<String,dynamic>) onUpdate; final Future<void> Function() onRefresh;
  @override Widget build(BuildContext context){
    final s=_map(data['summary']),items=_list(data['items']);
    if(loading&&data.isEmpty)return const Center(child:CircularProgressIndicator(color:_purple));
    return RefreshIndicator(color:_purple,onRefresh:onRefresh,child:LayoutBuilder(builder:(context,c){final compact=c.maxWidth<760,pad=compact?12.0:18.0,width=c.maxWidth-pad*2,cols=compact?2:5,gap=9.0,mw=(width-gap*(cols-1))/cols;return ListView(physics:const AlwaysScrollableScrollPhysics(),padding:EdgeInsets.fromLTRB(pad,14,pad,28),children:[
      _hero('İşletme Yönetimi','Başvuruları incele, onayla/reddet ve profil bilgilerini kontrol et.',Icons.storefront_rounded,_blue),const SizedBox(height:12),
      Wrap(spacing:gap,runSpacing:gap,children:[SizedBox(width:mw,child:_metric((s['total']??0).toString(),'Toplam',Icons.store_rounded,_blue)),SizedBox(width:mw,child:_metric((s['pending']??0).toString(),'Bekleyen',Icons.hourglass_top_rounded,_amber)),SizedBox(width:mw,child:_metric((s['approved']??0).toString(),'Onaylı',Icons.verified_rounded,_green)),SizedBox(width:mw,child:_metric((s['rejected']??0).toString(),'Reddedildi',Icons.cancel_outlined,Colors.redAccent)),SizedBox(width:mw,child:_metric((s['inactive']??0).toString(),'Pasif',Icons.pause_circle_outline,_muted))]),const SizedBox(height:11),
      Wrap(spacing:7,runSpacing:7,children:[for(final x in const [('all','Tümü'),('pending','Bekliyor'),('approved','Onaylı'),('rejected','Reddedildi'),('inactive','Pasif')])ChoiceChip(label:Text(x.$2),selected:status==x.$1,onSelected:(_)=>onStatus(x.$1))]),const SizedBox(height:10),
      if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),
      if(items.isEmpty)_empty('Bu filtrede işletme yok.') else ...items.map((b)=>_cardView(context,b)),
    ]);}));
  }
  Widget _cardView(BuildContext context,Map<String,dynamic> b){final st=(b['approval_status']??'pending').toString(),active=b['is_active']==true,color=_statusColor(st);return Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(18),border:Border.all(color:color.withValues(alpha:.28))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Row(children:[CircleAvatar(radius:23,backgroundColor:_card2,backgroundImage:(b['logo_url']??'').toString().isNotEmpty?NetworkImage(b['logo_url'].toString()):null,child:(b['logo_url']??'').toString().isEmpty?const Icon(Icons.storefront_rounded,color:_purple):null),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((b['name']??'-').toString(),style:const TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w900)),Text((b['category']??'-').toString()+' • '+(b['email']??'-').toString(),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:_muted,fontSize:10.5))])),_pill(_status(st),color),const SizedBox(width:5),_pill(active?'Aktif':'Pasif',active?_green:Colors.redAccent)]),
    const SizedBox(height:8),Text((b['address']??'Adres girilmemiş').toString(),style:const TextStyle(color:Colors.white70,fontSize:11.5)),const SizedBox(height:6),
    Wrap(spacing:9,runSpacing:4,children:[Text((b['campaign_count']??0).toString()+' kampanya',style:const TextStyle(color:_muted,fontSize:10.5)),Text((b['redeemed_count']??0).toString()+' kullanım',style:const TextStyle(color:_muted,fontSize:10.5)),Text(_money(b['platform_fees'])+' komisyon',style:const TextStyle(color:_green,fontSize:10.5,fontWeight:FontWeight.w800))]),
    if((b['admin_note']??'').toString().isNotEmpty)...[const SizedBox(height:6),Text('Admin notu: '+b['admin_note'].toString(),style:const TextStyle(color:_amber,fontSize:10.5))],const SizedBox(height:9),
    Wrap(spacing:7,runSpacing:7,children:[if(st!='approved')FilledButton.icon(onPressed:()=>onUpdate(b['id'].toString(),{'approvalStatus':'approved','isActive':true}),icon:const Icon(Icons.check_rounded),label:const Text('Onayla'),style:FilledButton.styleFrom(backgroundColor:_green,foregroundColor:Colors.black)),if(st!='rejected')OutlinedButton.icon(onPressed:()=>_reject(context,b),icon:const Icon(Icons.close_rounded),label:const Text('Reddet'),style:OutlinedButton.styleFrom(foregroundColor:Colors.redAccent)),OutlinedButton.icon(onPressed:()=>onUpdate(b['id'].toString(),{'isActive':!active}),icon:Icon(active?Icons.pause_rounded:Icons.play_arrow_rounded),label:Text(active?'Pasife Al':'Aktif Et')),OutlinedButton.icon(onPressed:()=>_edit(context,b),icon:const Icon(Icons.edit_rounded),label:const Text('Adres / Logo'))]),
  ]));}
  Future<void> _reject(BuildContext context,Map<String,dynamic> b)async{final note=TextEditingController(text:(b['admin_note']??'').toString());final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Başvuruyu reddet'),content:TextField(controller:note,maxLines:3,decoration:const InputDecoration(labelText:'Red nedeni')),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Reddet'))]));if(ok==true)await onUpdate(b['id'].toString(),{'approvalStatus':'rejected','isActive':false,'adminNote':note.text.trim()});note.dispose();}
  Future<void> _edit(BuildContext context,Map<String,dynamic> b)async{final address=TextEditingController(text:(b['address']??'').toString()),logo=TextEditingController(text:(b['logo_url']??'').toString()),hours=TextEditingController(text:(b['opening_hours']??'').toString()),note=TextEditingController(text:(b['admin_note']??'').toString());final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text((b['name']??'İşletme').toString()),content:SizedBox(width:460,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:address,maxLines:2,decoration:const InputDecoration(labelText:'Adres')),const SizedBox(height:8),TextField(controller:logo,decoration:const InputDecoration(labelText:'Logo URL')),const SizedBox(height:8),TextField(controller:hours,decoration:const InputDecoration(labelText:'Çalışma saatleri')),const SizedBox(height:8),TextField(controller:note,maxLines:2,decoration:const InputDecoration(labelText:'Admin notu'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Kaydet'))]));if(ok==true)await onUpdate(b['id'].toString(),{'address':address.text.trim(),'logoUrl':logo.text.trim(),'openingHours':hours.text.trim(),'adminNote':note.text.trim()});address.dispose();logo.dispose();hours.dispose();note.dispose();}
}

class AdminCampaignsPage extends StatelessWidget{
  const AdminCampaignsPage({super.key,required this.data,required this.loading,required this.error,required this.status,required this.onStatus,required this.onUpdate,required this.onRefresh});
  final Map<String,dynamic> data; final bool loading; final String? error; final String status;
  final Future<void> Function(String) onStatus; final Future<void> Function(String,Map<String,dynamic>) onUpdate; final Future<void> Function() onRefresh;
  @override Widget build(BuildContext context){final s=_map(data['summary']),items=_list(data['items']);if(loading&&data.isEmpty)return const Center(child:CircularProgressIndicator(color:_purple));return RefreshIndicator(color:_purple,onRefresh:onRefresh,child:LayoutBuilder(builder:(context,c){final compact=c.maxWidth<760,pad=compact?12.0:18.0,width=c.maxWidth-pad*2,cols=compact?2:5,gap=9.0,mw=(width-gap*(cols-1))/cols;return ListView(physics:const AlwaysScrollableScrollPhysics(),padding:EdgeInsets.fromLTRB(pad,14,pad,28),children:[
    _hero('Kampanya Yönetimi','Fırsatları incele, düzenle, onayla veya yayından kaldır.',Icons.campaign_rounded,_purple),const SizedBox(height:12),
    Wrap(spacing:gap,runSpacing:gap,children:[SizedBox(width:mw,child:_metric((s['total']??0).toString(),'Toplam',Icons.campaign_outlined,_purple)),SizedBox(width:mw,child:_metric((s['pending']??0).toString(),'Bekleyen',Icons.hourglass_top_rounded,_amber)),SizedBox(width:mw,child:_metric((s['approved']??0).toString(),'Onaylı',Icons.verified_rounded,_green)),SizedBox(width:mw,child:_metric((s['rejected']??0).toString(),'Reddedildi',Icons.cancel_outlined,Colors.redAccent)),SizedBox(width:mw,child:_metric((s['inactive']??0).toString(),'Yayında Değil',Icons.visibility_off_rounded,_muted))]),const SizedBox(height:11),
    Wrap(spacing:7,runSpacing:7,children:[for(final x in const [('all','Tümü'),('pending','Bekliyor'),('approved','Onaylı'),('rejected','Reddedildi'),('inactive','Yayında Değil')])ChoiceChip(label:Text(x.$2),selected:status==x.$1,onSelected:(_)=>onStatus(x.$1))]),const SizedBox(height:10),
    if(items.isEmpty)_empty('Bu filtrede kampanya yok.')else ...items.map((x)=>_campaignCard(context,x)),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),
  ]);}));}
  Widget _campaignCard(BuildContext context,Map<String,dynamic> x){final st=(x['moderation_status']??'pending').toString(),active=x['is_active']==true,color=_statusColor(st);return Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(18),border:Border.all(color:color.withValues(alpha:.28))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
    Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((x['title']??'-').toString(),style:const TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w900)),Text((x['business_name']??'-').toString(),style:const TextStyle(color:_blue,fontSize:10.5,fontWeight:FontWeight.w800))])),_pill(_status(st),color),const SizedBox(width:5),_pill(active?'Yayında':'Kapalı',active?_green:_muted)]),const SizedBox(height:7),
    Text((x['description']??'').toString(),maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:11.5)),const SizedBox(height:7),
    Wrap(spacing:9,runSpacing:4,children:[Text(_date(x['starts_at'])+' → '+_date(x['ends_at']),style:const TextStyle(color:_muted,fontSize:10.5)),Text('Koşul: '+(x['badge']??'-').toString(),style:const TextStyle(color:_muted,fontSize:10.5)),Text('Komisyon: '+_money(x['platform_fee']),style:const TextStyle(color:_green,fontSize:10.5,fontWeight:FontWeight.w800)),Text((x['redeemed_count']??0).toString()+' kullanım',style:const TextStyle(color:_muted,fontSize:10.5))]),const SizedBox(height:9),
    Wrap(spacing:7,runSpacing:7,children:[if(st!='approved')FilledButton.icon(onPressed:()=>onUpdate(x['id'].toString(),{'moderationStatus':'approved'}),icon:const Icon(Icons.check_rounded),label:const Text('Onayla'),style:FilledButton.styleFrom(backgroundColor:_green,foregroundColor:Colors.black)),if(st!='rejected')OutlinedButton.icon(onPressed:()=>_reject(context,x),icon:const Icon(Icons.close_rounded),label:const Text('Reddet'),style:OutlinedButton.styleFrom(foregroundColor:Colors.redAccent)),OutlinedButton.icon(onPressed:()=>onUpdate(x['id'].toString(),{'isActive':!active}),icon:Icon(active?Icons.visibility_off_rounded:Icons.visibility_rounded),label:Text(active?'Yayından Kaldır':'Yayınla')),OutlinedButton.icon(onPressed:()=>_edit(context,x),icon:const Icon(Icons.edit_rounded),label:const Text('Düzenle'))]),
  ]));}
  Future<void> _reject(BuildContext context,Map<String,dynamic> x)async{final n=TextEditingController(text:(x['admin_note']??'').toString());final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Kampanyayı reddet'),content:TextField(controller:n,maxLines:3,decoration:const InputDecoration(labelText:'Red nedeni')),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Reddet'))]));if(ok==true)await onUpdate(x['id'].toString(),{'moderationStatus':'rejected','isActive':false,'adminNote':n.text.trim()});n.dispose();}
  Future<void> _edit(BuildContext context,Map<String,dynamic> x)async{final title=TextEditingController(text:(x['title']??'').toString()),desc=TextEditingController(text:(x['description']??'').toString()),badge=TextEditingController(text:(x['badge']??'').toString()),start=TextEditingController(text:(x['starts_at']??'').toString()),end=TextEditingController(text:(x['ends_at']??'').toString()),fee=TextEditingController(text:(x['platform_fee']??'').toString()),note=TextEditingController(text:(x['admin_note']??'').toString());final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:const Text('Kampanyayı Düzenle'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Başlık')),const SizedBox(height:8),TextField(controller:desc,maxLines:3,decoration:const InputDecoration(labelText:'Açıklama')),const SizedBox(height:8),TextField(controller:badge,decoration:const InputDecoration(labelText:'Koşul / rozet')),const SizedBox(height:8),TextField(controller:start,decoration:const InputDecoration(labelText:'Başlangıç ISO')),const SizedBox(height:8),TextField(controller:end,decoration:const InputDecoration(labelText:'Bitiş ISO')),const SizedBox(height:8),TextField(controller:fee,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Platform komisyonu ₺')),const SizedBox(height:8),TextField(controller:note,maxLines:2,decoration:const InputDecoration(labelText:'Admin notu'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Kaydet'))]));if(ok==true)await onUpdate(x['id'].toString(),{'title':title.text.trim(),'description':desc.text.trim(),'badge':badge.text.trim(),'startsAt':start.text.trim(),'endsAt':end.text.trim(),'platformFee':double.tryParse(fee.text.replaceAll(',','.')),'adminNote':note.text.trim()});title.dispose();desc.dispose();badge.dispose();start.dispose();end.dispose();fee.dispose();note.dispose();}
}

class AdminOfferRevenuePage extends StatelessWidget{
  const AdminOfferRevenuePage({super.key,required this.data,required this.loading,required this.error,required this.days,required this.onDays,required this.onRefresh});
  final Map<String,dynamic> data;final bool loading;final String? error;final int days;final Future<void> Function(int) onDays;final Future<void> Function() onRefresh;
  @override Widget build(BuildContext context){final s=_map(data['summary']),businesses=_list(data['businesses']),items=_list(data['items']),daily=_list(data['daily']);if(loading&&data.isEmpty)return const Center(child:CircularProgressIndicator(color:_purple));final maxFee=daily.fold<double>(0,(m,x)=>_num(x['platform_fees'])>m?_num(x['platform_fees']):m);return RefreshIndicator(color:_purple,onRefresh:onRefresh,child:LayoutBuilder(builder:(context,c){final compact=c.maxWidth<760,pad=compact?12.0:18.0,width=c.maxWidth-pad*2,cols=compact?2:5,gap=9.0,mw=(width-gap*(cols-1))/cols;return ListView(physics:const AlwaysScrollableScrollPhysics(),padding:EdgeInsets.fromLTRB(pad,14,pad,28),children:[
    _hero('Fırsat Kullanım & Gelir','Kullanım ve Cepqar komisyon gelirini dönemsel takip et.',Icons.payments_rounded,_green),const SizedBox(height:11),
    Wrap(spacing:7,runSpacing:7,children:[for(final x in const [7,30,90,365])ChoiceChip(label:Text(x==365?'1 Yıl':x.toString()+' Gün'),selected:days==x,onSelected:(_)=>onDays(x))]),const SizedBox(height:10),
    Wrap(spacing:gap,runSpacing:gap,children:[SizedBox(width:mw,child:_metric((s['redeemed']??0).toString(),'Kullanım',Icons.verified_rounded,_green)),SizedBox(width:mw,child:_metric((s['pending']??0).toString(),'Bekleyen',Icons.hourglass_top_rounded,_amber)),SizedBox(width:mw,child:_metric((s['cancelled']??0).toString(),'İptal',Icons.cancel_outlined,Colors.redAccent)),SizedBox(width:mw,child:_metric(_money(s['platform_fees']),'Toplam komisyon',Icons.account_balance_wallet_rounded,_green)),SizedBox(width:mw,child:_metric((s['businesses_with_usage']??0).toString(),'İşletme',Icons.storefront_rounded,_blue))]),const SizedBox(height:12),
    Container(height:180,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(18),border:Border.all(color:_line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Dönemsel Komisyon',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),const SizedBox(height:8),Expanded(child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:daily.map((x){final v=_num(x['platform_fees']),h=maxFee<=0?2.0:(v/maxFee*120).clamp(2.0,120.0);return Expanded(child:Tooltip(message:_money(v),child:Container(height:h,margin:const EdgeInsets.symmetric(horizontal:1),decoration:BoxDecoration(color:_purple.withValues(alpha:.75),borderRadius:BorderRadius.circular(4)))));}).toList()))])),const SizedBox(height:12),
    const Text('İşletme Performansı',style:TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:7),
    if(businesses.isEmpty)_empty('Bu dönemde kullanım yok.')else ...businesses.take(40).map((b)=>Container(margin:const EdgeInsets.only(bottom:7),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(15),border:Border.all(color:_line)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((b['name']??'-').toString(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),Text((b['redeemed']??0).toString()+' kullanım • '+(b['pending']??0).toString()+' bekleyen',style:const TextStyle(color:_muted,fontSize:10.5))])),Text(_money(b['platform_fees']),style:const TextStyle(color:_green,fontWeight:FontWeight.w900))]))),const SizedBox(height:12),
    const Text('Son Kullanımlar',style:TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:7),
    if(items.isEmpty)_empty('Kullanım kaydı yok.')else ...items.take(100).map((r){final st=(r['status']??'').toString(),color=_statusColor(st);return Container(margin:const EdgeInsets.only(bottom:7),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(15),border:Border.all(color:_line)),child:Row(children:[Icon(Icons.local_offer_outlined,color:color,size:20),const SizedBox(width:8),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((r['business_name']??'-').toString()+' • '+(r['campaign_title']??'-').toString(),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:11.5,fontWeight:FontWeight.w800)),Text((r['plate']??'-').toString()+' • '+_date(r['redeemed_at']??r['created_at']),style:const TextStyle(color:_muted,fontSize:10))])),Text(st=='redeemed'?_money(r['platform_fee']):_status(st),style:TextStyle(color:color,fontSize:10.5,fontWeight:FontWeight.w900))]));}),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),
  ]);}));}
}

class AdminPremiumPage extends StatelessWidget{
  const AdminPremiumPage({super.key,required this.data,required this.loading,required this.error,required this.filter,required this.onFilter,required this.onAction,required this.onHistory,required this.onRefresh});
  final Map<String,dynamic> data;final bool loading;final String? error;final String filter;final Future<void> Function(String) onFilter;final Future<void> Function(String,Map<String,dynamic>) onAction;final Future<List<Map<String,dynamic>>> Function(String) onHistory;final Future<void> Function() onRefresh;
  @override Widget build(BuildContext context){final s=_map(data['summary']),items=_list(data['items']);if(loading&&data.isEmpty)return const Center(child:CircularProgressIndicator(color:_purple));return RefreshIndicator(color:_purple,onRefresh:onRefresh,child:LayoutBuilder(builder:(context,c){final compact=c.maxWidth<760,pad=compact?12.0:18.0,width=c.maxWidth-pad*2,cols=compact?2:4,gap=9.0,mw=(width-gap*(cols-1))/cols;return ListView(physics:const AlwaysScrollableScrollPhysics(),padding:EdgeInsets.fromLTRB(pad,14,pad,28),children:[
    _hero('Premium Yönetimi','Premium ver, süre belirle, uzat/iptal et ve geçmişi incele.',Icons.workspace_premium_rounded,_amber),const SizedBox(height:11),
    Wrap(spacing:gap,runSpacing:gap,children:[SizedBox(width:mw,child:_metric((s['total']??0).toString(),'Toplam',Icons.people_rounded,_blue)),SizedBox(width:mw,child:_metric((s['premium']??0).toString(),'Aktif Premium',Icons.workspace_premium_rounded,_amber)),SizedBox(width:mw,child:_metric((s['expired']??0).toString(),'Süresi Dolmuş',Icons.timer_off_rounded,Colors.redAccent)),SizedBox(width:mw,child:_metric((s['standard']??0).toString(),'Standart',Icons.person_outline_rounded,_muted))]),const SizedBox(height:11),
    Wrap(spacing:7,runSpacing:7,children:[for(final x in const [('all','Tümü'),('premium','Premium'),('expired','Süresi Dolmuş'),('standard','Standart')])ChoiceChip(label:Text(x.$2),selected:filter==x.$1,onSelected:(_)=>onFilter(x.$1))]),const SizedBox(height:9),
    if(items.isEmpty)_empty('Bu filtrede kullanıcı yok.')else ...items.map((u)=>_user(context,u)),if(error!=null)Text(error!,style:const TextStyle(color:Colors.redAccent)),
  ]);}));}
  Widget _user(BuildContext context,Map<String,dynamic> u){final premium=u['premium']==true,expired=u['premium_flag']==true&&!premium,color=premium?_amber:expired?Colors.redAccent:_muted;return Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:_card,borderRadius:BorderRadius.circular(16),border:Border.all(color:color.withValues(alpha:.27))),child:Column(children:[Row(children:[CircleAvatar(backgroundColor:color.withValues(alpha:.12),child:Icon(premium?Icons.workspace_premium_rounded:Icons.person_rounded,color:color)),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((u['display_name']??'İsimsiz').toString(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),Text((u['phone']??u['email']??'-').toString(),style:const TextStyle(color:_muted,fontSize:10.5))])),_pill(premium?'Premium':expired?'Süresi Dolmuş':'Standart',color)]),const SizedBox(height:7),Row(children:[Expanded(child:Text(premium?(u['premium_expires_at']==null?'Bitiş: Süresiz':'Bitiş: '+_date(u['premium_expires_at'])):'Premium aktif değil',style:const TextStyle(color:_muted,fontSize:10.5))),Text((u['history_count']??0).toString()+' işlem',style:const TextStyle(color:_muted,fontSize:10.5))]),const SizedBox(height:8),Wrap(spacing:7,runSpacing:7,children:[if(!premium)FilledButton.icon(onPressed:()=>_activate(context,u),icon:const Icon(Icons.workspace_premium_rounded),label:const Text('Premium Yap'),style:FilledButton.styleFrom(backgroundColor:_amber,foregroundColor:Colors.black)),if(premium)OutlinedButton.icon(onPressed:()=>_extend(context,u),icon:const Icon(Icons.add_alarm_rounded),label:const Text('Uzat')),if(premium)OutlinedButton.icon(onPressed:()=>onAction(u['id'].toString(),{'action':'cancel','note':'Admin tarafından iptal edildi'}),icon:const Icon(Icons.cancel_outlined),label:const Text('İptal'),style:OutlinedButton.styleFrom(foregroundColor:Colors.redAccent)),OutlinedButton.icon(onPressed:()=>_history(context,u),icon:const Icon(Icons.history_rounded),label:const Text('Geçmiş'))]) ]));}
  Future<void> _activate(BuildContext context,Map<String,dynamic> u)async{
    int days=30;
    bool unlimited=false,custom=false;
    DateTime? customDate;
    final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(
      title:Text((u['display_name']??'Kullanıcı').toString()+' • Premium'),
      content:Column(mainAxisSize:MainAxisSize.min,children:[
        SwitchListTile(
          contentPadding:EdgeInsets.zero,
          value:unlimited,
          onChanged:(v)=>setD((){unlimited=v;if(v)custom=false;}),
          title:const Text('Süresiz Premium'),
        ),
        if(!unlimited)...[
          SwitchListTile(
            contentPadding:EdgeInsets.zero,
            value:custom,
            onChanged:(v)=>setD(()=>custom=v),
            title:const Text('Özel bitiş tarihi'),
          ),
          if(custom)
            OutlinedButton.icon(
              onPressed:()async{
                final picked=await showDatePicker(
                  context:d,
                  initialDate:customDate??DateTime.now().add(const Duration(days:30)),
                  firstDate:DateTime.now(),
                  lastDate:DateTime.now().add(const Duration(days:3650)),
                );
                if(picked!=null)setD(()=>customDate=picked);
              },
              icon:const Icon(Icons.calendar_month_rounded),
              label:Text(customDate==null?'Tarih seç':_date(customDate!.toIso8601String())),
            )
          else
            DropdownButtonFormField<int>(
              value:days,
              decoration:const InputDecoration(labelText:'Süre'),
              items:const[
                DropdownMenuItem(value:7,child:Text('7 gün')),
                DropdownMenuItem(value:30,child:Text('30 gün')),
                DropdownMenuItem(value:90,child:Text('90 gün')),
                DropdownMenuItem(value:365,child:Text('1 yıl')),
              ],
              onChanged:(v)=>setD(()=>days=v??30),
            ),
        ],
      ]),
      actions:[
        TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),
        FilledButton(onPressed:custom&&customDate==null?null:()=>Navigator.pop(d,true),child:const Text('Premium Yap')),
      ],
    )));
    if(ok==true){
      final payload=<String,dynamic>{'action':'activate','note':'Admin manuel Premium'};
      if(unlimited){
        payload['expiresAt']=null;
      }else if(custom&&customDate!=null){
        payload['expiresAt']=DateTime(customDate!.year,customDate!.month,customDate!.day,23,59,59).toUtc().toIso8601String();
      }else{
        payload['days']=days;
      }
      await onAction(u['id'].toString(),payload);
    }
  }
  Future<void> _extend(BuildContext context,Map<String,dynamic> u)async{int days=30;final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(title:const Text('Premium Uzat'),content:DropdownButtonFormField<int>(value:days,decoration:const InputDecoration(labelText:'Eklenecek süre'),items:const [DropdownMenuItem(value:7,child:Text('7 gün')),DropdownMenuItem(value:30,child:Text('30 gün')),DropdownMenuItem(value:90,child:Text('90 gün')),DropdownMenuItem(value:365,child:Text('1 yıl'))],onChanged:(v)=>setD(()=>days=v??30)),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Uzat'))])));if(ok==true)await onAction(u['id'].toString(),{'action':'extend','days':days,'note':'Admin uzatma'});}
  Future<void> _history(BuildContext context,Map<String,dynamic> u)async{final rows=await onHistory(u['id'].toString());if(!context.mounted)return;await showDialog(context:context,builder:(d)=>AlertDialog(title:Text((u['display_name']??'Kullanıcı').toString()+' • Premium Geçmişi'),content:SizedBox(width:520,height:400,child:rows.isEmpty?const Center(child:Text('Geçmiş yok')):ListView(children:rows.map((x)=>ListTile(leading:Icon(x['action']=='cancelled'?Icons.cancel_outlined:Icons.workspace_premium_rounded,color:x['action']=='cancelled'?Colors.redAccent:_amber),title:Text((x['action']??'-').toString()),subtitle:Text(_date(x['created_at'])+'\n'+(x['note']??'').toString()),trailing:Text(x['new_premium']==true?(x['new_expires_at']==null?'Süresiz':_date(x['new_expires_at'])):'Kapalı',textAlign:TextAlign.right))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Kapat'))]));}
}
