import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

const _api='https://heycar-api-185-165-46-213.nip.io';
const _purple=Color(0xFFB100FF),_bg=Color(0xFF040714),_card=Color(0xFF090E22),_muted=Color(0xFFA9AFC4),_lime=Color(0xFFB6FF2A);

class AdminTowingPage extends StatefulWidget{
 const AdminTowingPage({super.key,required this.token,required this.admin});
 final String token;final Map<String,dynamic>? admin;
 @override State<AdminTowingPage> createState()=>_AdminTowingPage();
}
class _AdminTowingPage extends State<AdminTowingPage>{
 bool loading=true;String filter='all';List<Map<String,dynamic>> rows=[];
 Map<String,String> get h=>{'authorization':'Bearer ${widget.token}','content-type':'application/json',if((widget.admin?['id']??'').toString().isNotEmpty)'X-Admin-Id':'${widget.admin?['id']}'};
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState(()=>loading=true);try{final r=await http.get(Uri.parse('$_api/api/admin/manage/towing/providers?status=$filter'),headers:h);final d=jsonDecode(r.body);if(r.statusCode==200)rows=List<Map<String,dynamic>>.from((d['items']??[]).map((x)=>Map<String,dynamic>.from(x)));}finally{if(mounted)setState(()=>loading=false);}}
 Future<Map<String,dynamic>> detail(String id)async{final r=await http.get(Uri.parse('$_api/api/admin/manage/towing/providers/$id'),headers:h);return Map<String,dynamic>.from(jsonDecode(r.body));}
 Future<void> status(String id,String value,[String note=''])async{await http.patch(Uri.parse('$_api/api/admin/manage/towing/providers/$id/status'),headers:h,body:jsonEncode({'status':value,'note':note}));await load();}
 Future<void> remove(String id)async{await http.delete(Uri.parse('$_api/api/admin/manage/towing/providers/$id'),headers:h);await load();}
 Future<void> open(Map<String,dynamic> row)async{final d=await detail('${row['id']}');if(!mounted)return;await showDialog(context:context,builder:(_)=>ProviderDialog(data:d,headers:h,onStatus:(v,n)=>status('${row['id']}',v,n),onReload:()=>detail('${row['id']}')));await load();}
 @override Widget build(BuildContext c)=>Container(color:_bg,child:Column(children:[Padding(padding:const EdgeInsets.all(14),child:Row(children:[const Expanded(child:Text('Çekici Yönetimi',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))),DropdownButton<String>(value:filter,items:const [('all','Tümü'),('pending','Başvurular'),('active','Aktif'),('suspended','Askıda'),('rejected','Reddedilen'),('banned','Banlı')].map((x)=>DropdownMenuItem(value:x.$1,child:Text(x.$2))).toList(),onChanged:(v){if(v!=null){filter=v;load();}}),IconButton(onPressed:load,icon:const Icon(Icons.refresh))])),Expanded(child:loading?const Center(child:CircularProgressIndicator()):rows.isEmpty?const Center(child:Text('Kayıt yok',style:TextStyle(color:_muted))):ListView.builder(padding:const EdgeInsets.all(14),itemCount:rows.length,itemBuilder:(_,i){final x=rows[i];return Card(color:_card,child:ListTile(onTap:()=>open(x),leading:CircleAvatar(backgroundColor:_purple.withValues(alpha:.18),child:const Icon(Icons.fire_truck,color:_purple)),title:Text('${x['display_name']??'-'}',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${x['provider_type']=='company'?'Firma':'Bireysel'} • ${x['phone']??'-'}\n${x['document_count']??0} belge • ${x['vehicle_count']??0} araç • ${x['driver_count']??0} sürücü'),isThreeLine:true,trailing:Chip(label:Text('${x['status']}'))));}))]));}

class ProviderDialog extends StatefulWidget{const ProviderDialog({super.key,required this.data,required this.headers,required this.onStatus,required this.onReload});final Map<String,dynamic> data;final Map<String,String> headers;final Future<void> Function(String,String) onStatus;final Future<Map<String,dynamic>> Function() onReload;@override State<ProviderDialog> createState()=>_ProviderDialog();}
class _ProviderDialog extends State<ProviderDialog>{late Map<String,dynamic>d;bool busy=false;@override void initState(){super.initState();d=widget.data;}
 Future<void> act(String s)async{final note=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:Text(s=='active'?'Başvuruyu onayla':'İşlemi onayla'),content:TextField(controller:note,maxLines:3,decoration:const InputDecoration(labelText:'Admin notu')),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Onayla'))]));if(ok!=true)return;setState(()=>busy=true);await widget.onStatus(s,note.text);d=await widget.onReload();if(mounted)setState(()=>busy=false);}
 Future<void> reviewDoc(Map x,String status)async{await http.patch(Uri.parse('$_api/api/admin/manage/towing/documents/${x['id']}'),headers:widget.headers,body:jsonEncode({'status':status}));d=await widget.onReload();if(mounted)setState((){});}
 Future<void> preview(Map x)async{final r=await http.get(Uri.parse('$_api/api/admin/manage/towing/documents/${x['id']}/file'),headers:widget.headers);if(!mounted||r.statusCode!=200)return;await showDialog(context:context,builder:(_)=>Dialog(child:InteractiveViewer(child:Image.memory(Uint8List.fromList(r.bodyBytes),fit:BoxFit.contain))));}
 @override Widget build(BuildContext c){final p=Map<String,dynamic>.from(d['provider']??{}),docs=List<Map<String,dynamic>>.from((d['documents']??[]).map((x)=>Map<String,dynamic>.from(x)));return AlertDialog(title:Row(children:[const Icon(Icons.fire_truck,color:_purple),const SizedBox(width:8),Expanded(child:Text('${p['display_name']??'Çekici'}'))]),content:SizedBox(width:720,child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${p['provider_type']=='company'?'Firma':'Bireysel'} • ${p['phone']??'-'} • ${p['email']??'-'}',style:const TextStyle(color:_muted)),if((p['company_title']??'').toString().isNotEmpty)Text('Firma: ${p['company_title']} • Vergi No: ${p['tax_number']??'-'}'),const SizedBox(height:16),const Text('Belgeler',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900)),...docs.map((x)=>Card(child:ListTile(onTap:()=>preview(x),leading:const Icon(Icons.description,color:_purple),title:Text(label('${x['document_type']}')),subtitle:Text('${x['original_name']} • ${x['status']}'),trailing:Wrap(children:[IconButton(tooltip:'Onayla',onPressed:()=>reviewDoc(x,'approved'),icon:const Icon(Icons.check_circle,color:_lime)),IconButton(tooltip:'Reddet',onPressed:()=>reviewDoc(x,'rejected'),icon:const Icon(Icons.cancel,color:Colors.redAccent))])))),if(docs.isEmpty)const Text('Belge yüklenmemiş.',style:TextStyle(color:_muted)),const SizedBox(height:16),Text('Durum: ${p['status']}',style:const TextStyle(fontWeight:FontWeight.w900)),if((p['review_note']??'').toString().isNotEmpty)Text('Admin notu: ${p['review_note']}',style:const TextStyle(color:_muted))]))),actions:[TextButton(onPressed:busy?null:()=>act('banned'),child:const Text('Banla',style:TextStyle(color:Colors.redAccent))),TextButton(onPressed:busy?null:()=>act('suspended'),child:const Text('Askıya Al')),TextButton(onPressed:busy?null:()=>act('rejected'),child:const Text('Reddet')),FilledButton(onPressed:busy?null:()=>act('active'),child:const Text('Onayla')),TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Kapat'))]);}
 String label(String k)=>{'identity_license':'Kimlik / Ehliyet','vehicle_registration':'Çekici Ruhsatı','authorization_certificate':'Yetki Belgesi','tax_certificate':'Vergi Levhası'}[k]??k;
}
