import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _bg=Color(0xFF07111F),_panel=Color(0xFF101A30),_line=Color(0xFF27355D),_purple=Color(0xFF713BFF),_muted=Color(0xFFA7B0C7);

const _businessApi='https://heycar-api-185-165-46-213.nip.io';

class BusinessPanelPage extends StatefulWidget{const BusinessPanelPage({super.key});@override State<BusinessPanelPage> createState()=>_BusinessPanelPageState();}
class _BusinessPanelPageState extends State<BusinessPanelPage>{
 int tab=0; String token=''; bool loading=false; Map<String,dynamic>? business,stats; List<Map<String,dynamic>> liveCampaigns=[];
 @override void initState(){super.initState();_restore();}
 Future<void> _restore()async{final p=await SharedPreferences.getInstance();token=p.getString('business_token')??'';if(token.isNotEmpty)await _loadAll();else if(mounted)setState((){});}
 Future<Map<String,dynamic>?> _get(String path)async{final r=await http.get(Uri.parse('$_businessApi$path'),headers:{'Authorization':'Bearer $token'});if(r.statusCode==401){await _logout();return null;}if(r.statusCode<200||r.statusCode>=300)return null;return Map<String,dynamic>.from(jsonDecode(r.body));}
 Future<void> _loadAll()async{if(token.isEmpty)return;if(mounted)setState(()=>loading=true);final rs=await Future.wait([_get('/api/business/me'),_get('/api/business/campaigns'),_get('/api/business/stats')]);if(!mounted)return;setState((){business=rs[0]?['business'] is Map?Map<String,dynamic>.from(rs[0]!['business']):null;liveCampaigns=(rs[1]?['campaigns'] as List? ?? []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();stats=rs[2]?['stats'] is Map?Map<String,dynamic>.from(rs[2]!['stats']):null;loading=false;});}
 Future<void> _logout()async{if(token.isNotEmpty){try{await http.post(Uri.parse('$_businessApi/api/business/auth/logout'),headers:{'Authorization':'Bearer $token'});}catch(_){}}final p=await SharedPreferences.getInstance();await p.remove('business_token');if(mounted)setState((){token='';business=null;stats=null;liveCampaigns=[];});}

 final campaigns=const [
  ('%30 İndirim','Premium Oto Yıkama','1 Eyl - 30 Eyl','4.2K','320',true,Icons.local_car_wash_rounded),
  ('%25 İndirim','Detaylı İç Temizlik','5 Eyl - 30 Eyl','2.1K','156',true,Icons.auto_awesome_rounded),
  ('3 Al 2 Öde','Tüm Lastik Markalarında','1 Eyl - 15 Eyl','1.8K','98',false,Icons.tire_repair_rounded),
 ];
 @override
 Widget build(BuildContext context){
  final desktop=MediaQuery.sizeOf(context).width>=900;
  final home=Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
   _Header(desktop:desktop,onLogin:token.isEmpty?()=>_showAuth(context):_logout),
   const SizedBox(height:16),if(loading)const LinearProgressIndicator(color:_purple),if(loading)const SizedBox(height:10),_Hero(name:(business?['name']??'İşletmen').toString()),const SizedBox(height:16),_Stats(desktop:desktop),const SizedBox(height:16),
   SizedBox(width:double.infinity,height:48,child:FilledButton.icon(onPressed:()=>_showCampaign(context),style:FilledButton.styleFrom(backgroundColor:_purple,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(15))),icon:const Icon(Icons.add_circle_rounded),label:const Text('Yeni Kampanya Oluştur',style:TextStyle(fontWeight:FontWeight.w900)))),
   const SizedBox(height:16),
   if(!desktop)...[_Quick(),const SizedBox(height:16)],
   if(desktop) Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:2,child:_Campaigns(items:campaigns)),const SizedBox(width:16),Expanded(child:Column(children:[_Profile(),const SizedBox(height:16),_Quick()]))])
   else Column(children:[_Campaigns(items:campaigns),const SizedBox(height:16),_Profile()]),
   const SizedBox(height:20),
  ]);
  Widget page=home;
  if(tab==1) page=_StatsPage(stats:stats);
  if(tab==3) page=_SettingsPage(business:business,onEdit:()=>_editProfile(context),onLogout:_logout);
  if(desktop&&tab==4) page=_StatsPage(stats:stats);
  if(desktop&&tab==1) page=_SettingsPage(business:business,onEdit:()=>_editProfile(context),onLogout:_logout);
  if(desktop&&tab==2) page=Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_Header(desktop:true,onLogin:token.isEmpty?()=>_showAuth(context):_logout),const SizedBox(height:18),SizedBox(width:260,height:46,child:FilledButton.icon(onPressed:()=>_showCampaign(context),icon:const Icon(Icons.add),label:const Text('Yeni Kampanya'))),const SizedBox(height:16),_Campaigns(items:campaigns)]);
  return Scaffold(backgroundColor:_bg,bottomNavigationBar:desktop?null:_Bottom(tab:tab,onTap:(i){if(i==2){_showCampaign(context);}else{setState(()=>tab=i);}}),body:SafeArea(child:Row(children:[if(desktop)_Side(tab:tab,onTap:(i)=>setState(()=>tab=i)),Expanded(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1180),child:SingleChildScrollView(padding:EdgeInsets.all(desktop?28:16),child:page))))])));
 }
 }
 Future<void> _editProfile(BuildContext context)async{if(token.isEmpty){await _showAuth(context);return;}final n=TextEditingController(text:(business?['name']??'').toString()),cat=TextEditingController(text:(business?['category']??'').toString()),phone=TextEditingController(text:(business?['phone']??'').toString()),address=TextEditingController(text:(business?['address']??'').toString()),hours=TextEditingController(text:(business?['opening_hours']??'').toString()),desc=TextEditingController(text:(business?['description']??'').toString());await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_panel,title:const Text('İşletme Bilgileri',style:TextStyle(color:Colors.white)),content:SizedBox(width:430,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[_Field(n,'İşletme adı'),_Field(cat,'Kategori'),_Field(phone,'Telefon'),_Field(address,'Adres'),_Field(hours,'Çalışma saatleri'),_Field(desc,'Açıklama')]))),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{final r=await http.patch(Uri.parse('$_businessApi/api/business/me'),headers:{'Content-Type':'application/json','Authorization':'Bearer $token'},body:jsonEncode({'name':n.text,'category':cat.text,'phone':phone.text,'address':address.text,'openingHours':hours.text,'description':desc.text,'latitude':business?['latitude'],'longitude':business?['longitude']}));if(r.statusCode==200){if(d.mounted)Navigator.pop(d);await _loadAll();}},child:const Text('Kaydet'))]));}
 Future<void> _showCampaign(BuildContext context) async {final title=TextEditingController(),desc=TextEditingController(),badge=TextEditingController(),code=TextEditingController();DateTime start=DateTime.now(),end=DateTime.now().add(const Duration(days:30));await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_panel,title:const Text('Yeni Kampanya Oluştur',style:TextStyle(color:Colors.white)),content:SizedBox(width:430,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[_Field(title,'Kampanya başlığı'),_Field(desc,'Açıklama'),_Field(badge,'İndirim etiketi (%30 İndirim)'),_Field(code,'Kampanya kodu')]))),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{if(token.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Önce işletme hesabıyla giriş yapmalısın.')));return;}final r=await http.post(Uri.parse('$_businessApi/api/business/campaigns'),headers:{'Content-Type':'application/json','Authorization':'Bearer $token'},body:jsonEncode({'title':title.text,'description':desc.text,'badge':badge.text,'couponCode':code.text,'startsAt':start.toIso8601String(),'endsAt':end.toIso8601String()}));if(d.mounted&&r.statusCode==201){Navigator.pop(d);await _loadAll();}},child:const Text('Yayınla'))]));}
 Future<void> _showAuth(BuildContext context,{bool register=false}) async {
  final email=TextEditingController(),pw=TextEditingController(),name=TextEditingController(),cat=TextEditingController();
  await showDialog(context:context,builder:(d)=>AlertDialog(
   backgroundColor:_panel,
   title:Text(register?'İşletme Kaydı':'İşletme Girişi',style:const TextStyle(color:Colors.white)),
   content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[if(register)_Field(name,'İşletme adı'),if(register)_Field(cat,'Kategori'),_Field(email,'E-posta'),_Field(pw,'Şifre',secret:true)])),
   actions:[
    if(!register)TextButton(onPressed:(){Navigator.pop(d);_showAuth(context,register:true);},child:const Text('Kayıt Ol')),
    FilledButton(onPressed:()async{
     final path=register?'register':'login';
     final body=register?{'email':email.text,'password':pw.text,'name':name.text,'category':cat.text}:{'email':email.text,'password':pw.text};
     final r=await http.post(Uri.parse('$_businessApi/api/business/auth/$path'),headers:{'Content-Type':'application/json'},body:jsonEncode(body));
     if(r.statusCode==200||r.statusCode==201){final j=jsonDecode(r.body);token=(j['token'] ?? '').toString();final p=await SharedPreferences.getInstance();await p.setString('business_token',token);if(d.mounted)Navigator.pop(d);await _loadAll();}
     else if(d.mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Giriş/kayıt başarısız.')));}
    },child:Text(register?'Kayıt Ol':'Giriş Yap'))
   ],
  ));
 }
}
class _Field extends StatelessWidget{const _Field(this.c,this.label,{this.secret=false});final TextEditingController c;final String label;final bool secret;@override Widget build(BuildContext x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,obscureText:secret,style:const TextStyle(color:Colors.white),decoration:InputDecoration(labelText:label,labelStyle:const TextStyle(color:_muted),filled:true,fillColor:_bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))));}
class _Header extends StatelessWidget{const _Header({required this.desktop,required this.onLogin});final bool desktop;final VoidCallback onLogin;@override Widget build(BuildContext c){if(!desktop)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Image.asset('assets/Logoqr.png',height:32),const Spacer(),IconButton(onPressed:onLogin,icon:const Icon(Icons.login_rounded,color:_purple)),const Icon(Icons.notifications_none_rounded,color:_muted,size:23)]),const SizedBox(height:12),const Text('İşletme Paneli',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:3),const Text('İşletmeni yönet, daha fazla müşteriye ulaş.',style:TextStyle(color:_muted,fontSize:11))]);return Row(children:[Image.asset('assets/Logoqr.png',height:42),const SizedBox(width:16),Container(width:1,height:35,color:_line),const SizedBox(width:14),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('İşletme Paneli',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),Text('İşletmeni yönet, daha fazla müşteriye ulaş.',style:TextStyle(color:_muted,fontSize:10))])),IconButton(onPressed:onLogin,icon:const Icon(Icons.login_rounded,color:_purple)),const Icon(Icons.notifications_none_rounded,color:_muted),const SizedBox(width:12),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:8),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Row(children:[CircleAvatar(radius:13,backgroundColor:_purple,child:Icon(Icons.storefront,color:Colors.white,size:14)),SizedBox(width:7),Text('CleanDrive',style:TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w800)),Icon(Icons.keyboard_arrow_down,color:_muted,size:18)]))]);}}
class _Hero extends StatelessWidget{const _Hero({required this.name});final String name;@override Widget build(BuildContext c)=>Container(height:125,padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF25105D),Color(0xFF713BFF),Color(0xFF101A30)]),borderRadius:BorderRadius.circular(20),border:Border.all(color:_purple.withValues(alpha:.45))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('Merhaba, $name 👋',style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Bugün de harika fırsatlar paylaş!',style:TextStyle(color:Color(0xFFD6C8FF),fontSize:12))])),const Icon(Icons.directions_car_rounded,color:Colors.white,size:72)]));}
class _Stats extends StatelessWidget{const _Stats({required this.desktop});final bool desktop;@override Widget build(BuildContext c){final xs=[(Icons.groups_rounded,'Görüntülenme','12.5K','↑ %18'),(Icons.local_offer_rounded,'Kampanya Tıklama','842','↑ %27'),(Icons.location_on_rounded,'Profil Ziyareti','2.341','↑ %12'),(Icons.star_rounded,'Ortalama Puan','4.8','★★★★★')];return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:4,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:desktop?4:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:desktop?1.8:1.45),itemBuilder:(_,i){final x=xs[i];return _Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Icon(x.$1,color:i==3?Colors.amber:_purple,size:24),const SizedBox(height:6),Text(x.$2,style:const TextStyle(color:_muted,fontSize:10)),Text(x.$3,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(x.$4,style:TextStyle(color:i==3?Colors.amber:const Color(0xFF39D98A),fontSize:10,fontWeight:FontWeight.w800))]));});}}
class _Campaigns extends StatelessWidget{const _Campaigns({required this.items});final List<(String,String,String,String,String,bool,IconData)> items;@override Widget build(BuildContext c)=>_Box(child:Column(children:[const Row(children:[Expanded(child:Text('Aktif Kampanyalarım',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900))),Text('Tümünü Gör ›',style:TextStyle(color:_purple,fontSize:10,fontWeight:FontWeight.w800))]),const SizedBox(height:8),...items.map((x)=>Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:_line))),child:Row(children:[Container(width:72,height:62,decoration:BoxDecoration(color:_purple.withValues(alpha:.15),borderRadius:BorderRadius.circular(12)),child:Stack(children:[Center(child:Icon(x.$7,color:_purple,size:30)),Positioned(left:4,top:4,child:Container(padding:const EdgeInsets.symmetric(horizontal:5,vertical:3),decoration:BoxDecoration(color:const Color(0xFFFF416C),borderRadius:BorderRadius.circular(8)),child:Text(x.$1,style:const TextStyle(color:Colors.white,fontSize:7.5,fontWeight:FontWeight.w900))))])),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.$2,style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900)),Text(x.$3,style:const TextStyle(color:_muted,fontSize:9.5)),const SizedBox(height:4),Text('◉ ${x.$4}    ◇ ${x.$5}',style:const TextStyle(color:_muted,fontSize:9))])),Column(children:[Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:4),decoration:BoxDecoration(color:(x.$6?const Color(0xFF20C77A):_muted).withValues(alpha:.14),borderRadius:BorderRadius.circular(10)),child:Text(x.$6?'Aktif':'Pasif',style:TextStyle(color:x.$6?const Color(0xFF39D98A):_muted,fontSize:8.5,fontWeight:FontWeight.w900))),const SizedBox(height:6),OutlinedButton(onPressed:(){},style:OutlinedButton.styleFrom(minimumSize:const Size(68,30),padding:EdgeInsets.zero,side:const BorderSide(color:_purple)),child:const Text('Düzenle',style:TextStyle(color:_purple,fontSize:9)))])])))]));}
class _Profile extends StatelessWidget{@override Widget build(BuildContext c)=>_Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Expanded(child:Text('İşletme Profilim',style:TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900))),Text('Düzenle ›',style:TextStyle(color:_purple,fontSize:10,fontWeight:FontWeight.w800))]),const SizedBox(height:12),const Row(children:[CircleAvatar(radius:34,backgroundColor:Color(0xFF25105D),child:Icon(Icons.storefront,color:_purple,size:30)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CleanDrive Oto Yıkama',style:TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900)),Text('⭐ 4.8 (320 yorum)',style:TextStyle(color:_muted,fontSize:10)),Text('Oto Yıkama • İstanbul',style:TextStyle(color:_muted,fontSize:10))]))]),const SizedBox(height:12),SizedBox(width:double.infinity,child:OutlinedButton(onPressed:null,child:Text('Profili Gör',style:TextStyle(color:_purple))))]));}
class _Quick extends StatelessWidget{@override Widget build(BuildContext c){final xs=[(Icons.storefront_rounded,'İşletme Bilgilerim'),(Icons.local_offer_rounded,'Kampanyalar'),(Icons.qr_code_rounded,'Kullanım Kodları'),(Icons.bar_chart_rounded,'İstatistikler')];return _Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Hızlı İşlemler',style:TextStyle(color:Colors.white,fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:10),Row(children:xs.map((x)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:InkWell(borderRadius:BorderRadius.circular(12),onTap:()=>ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('${x.$2} açıldı'))),child:Container(height:72,decoration:BoxDecoration(border:Border.all(color:_line),borderRadius:BorderRadius.circular(12)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(x.$1,color:_purple,size:22),const SizedBox(height:5),Text(x.$2,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:8.5))])))))).toList())]));}}
class _Box extends StatelessWidget{const _Box({required this.child});final Widget child;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:_line)),child:child);}
class _Side extends StatelessWidget{const _Side({required this.tab,required this.onTap});final int tab;final ValueChanged<int> onTap;@override Widget build(BuildContext c)=>Container(width:210,color:const Color(0xFF091528),padding:const EdgeInsets.fromLTRB(14,28,14,14),child:Column(children:[Image.asset('assets/Logoqr.png',height:40),const SizedBox(height:30),...['Ana Sayfa','İşletme Bilgileri','Kampanyalar','Kullanım Kodları','İstatistikler','Müşteri Yorumları','Ayarlar'].asMap().entries.map((e)=>ListTile(onTap:()=>onTap(e.key),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12)),tileColor:e.key==tab?_purple:null,leading:Icon([Icons.home_rounded,Icons.storefront,Icons.local_offer,Icons.qr_code,Icons.bar_chart,Icons.chat,Icons.settings][e.key],color:e.key==tab?Colors.white:_muted,size:20),title:Text(e.value,style:TextStyle(color:e.key==tab?Colors.white:_muted,fontSize:11,fontWeight:FontWeight.w700))))]));}
class _Bottom extends StatelessWidget{const _Bottom({required this.tab,required this.onTap});final int tab;final ValueChanged<int> onTap;@override Widget build(BuildContext c)=>Container(height:74,decoration:const BoxDecoration(color:Color(0xFF0D192D),border:Border(top:BorderSide(color:_line))),child:SafeArea(top:false,child:Row(children:[(Icons.home_rounded,'Ana Sayfa'),(Icons.bar_chart_rounded,'İstatistikler'),(Icons.add_circle_rounded,'Kampanya'),(Icons.settings_rounded,'Ayarlar')].asMap().entries.map((e)=>Expanded(child:InkWell(onTap:()=>onTap(e.key),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(e.value.$1,color:e.key==tab?_purple:_muted,size:25),Text(e.value.$2,style:TextStyle(color:e.key==tab?_purple:_muted,fontSize:9.5,fontWeight:FontWeight.w700))])))).toList())));}

class _StatsPage extends StatelessWidget{const _StatsPage({required this.stats});final Map<String,dynamic>? stats;@override Widget build(BuildContext c){final s=stats??{};return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('İstatistikler',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Gerçek kampanya verilerin',style:TextStyle(color:_muted)),const SizedBox(height:18),_Metric('Toplam Kampanya','${s['campaigns']??0}',Icons.local_offer_rounded),const SizedBox(height:10),_Metric('Aktif Kampanya','${s['active_campaigns']??0}',Icons.campaign_rounded),const SizedBox(height:10),_Metric('Toplam Kullanım','${s['redemptions']??0}',Icons.qr_code_scanner_rounded)]);}}
class _Metric extends StatelessWidget{const _Metric(this.t,this.v,this.i);final String t,v;final IconData i;@override Widget build(BuildContext c)=>_Box(child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:_purple.withValues(alpha:.15),borderRadius:BorderRadius.circular(14)),child:Icon(i,color:_purple)),const SizedBox(width:13),Expanded(child:Text(t,style:const TextStyle(color:_muted,fontSize:13))),Text(v,style:const TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900))]));}
class _SettingsPage extends StatelessWidget{const _SettingsPage({required this.business,required this.onEdit,required this.onLogout});final Map<String,dynamic>? business;final VoidCallback onEdit,onLogout;@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Ayarlar',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:18),_Box(child:Column(children:[ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.storefront_rounded,color:_purple),title:Text((business?['name']??'İşletme Bilgileri').toString(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),subtitle:Text((business?['category']??'Profilini düzenle').toString(),style:const TextStyle(color:_muted)),trailing:const Icon(Icons.chevron_right,color:_muted),onTap:onEdit),const Divider(color:_line),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.logout_rounded,color:Colors.redAccent),title:const Text('Çıkış Yap',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),onTap:onLogout)]))]);}
