import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

const _vBg=Color(0xFF07111F),_vPanel=Color(0xFF101A30),_vLine=Color(0xFF27355D),_vPurple=Color(0xFF713BFF),_vLime=Color(0xFFB6FF2A),_vMuted=Color(0xFFA7B0C7);
const _vApi='https://heycar-api-185-165-46-213.nip.io';

class BusinessValetPage extends StatefulWidget{
 const BusinessValetPage({super.key,required this.token});
 final String token;
 @override State<BusinessValetPage> createState()=>_BusinessValetPageState();
}
class _BusinessValetPageState extends State<BusinessValetPage>{
 bool loading=true,enabled=true; String? error;
 List<Map<String,dynamic>> sessions=[],staff=[],areas=[];
 Map<String,String> get headers=>{'Content-Type':'application/json','Authorization':'Bearer '+widget.token};
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState((){loading=true;error=null;});try{final r=await http.get(Uri.parse(_vApi+'/api/business/valet/overview'),headers:headers);if(r.statusCode==403){setState((){enabled=false;loading=false;});return;}if(r.statusCode!=200)throw Exception();final j=jsonDecode(r.body);setState((){enabled=true;sessions=(j['sessions'] as List? ?? []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();staff=(j['staff'] as List? ?? []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();areas=(j['areas'] as List? ?? []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();loading=false;});}catch(_){setState((){loading=false;error='Vale verileri alınamadı.';});}}
 Future<bool> post(String path,Map<String,dynamic> body)async{try{final r=await http.post(Uri.parse(_vApi+path),headers:headers,body:jsonEncode(body));if(r.statusCode>=200&&r.statusCode<300){await load();return true;}if(mounted){String msg='İşlem başarısız.';try{final j=jsonDecode(r.body);final e=(j['error']??'').toString();if(e=='INVALID_STAFF')msg='PIN yalnızca 4-8 rakam olmalı.';else if(e=='VALET_NOT_ENABLED')msg='Bu işletmede Vale aktif değil.';else if(e=='AREA_NAME_REQUIRED')msg='Park alanı adı gerekli.';else if(e=='PLATE_REQUIRED')msg='Plaka gerekli.';else if(e.isNotEmpty)msg='İşlem başarısız: '+e;}catch(_){}ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(msg)));}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sunucuya ulaşılamadı.')));}return false;}
 Future<void> setStatus(String id,String value)async{try{final r=await http.patch(Uri.parse(_vApi+'/api/business/valet/sessions/'+id+'/status'),headers:headers,body:jsonEncode({'status':value}));if(r.statusCode==200)await load();}catch(_){}}
 Widget field(TextEditingController c,String label)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,style:const TextStyle(color:Colors.white),decoration:InputDecoration(labelText:label,labelStyle:const TextStyle(color:_vMuted),filled:true,fillColor:_vBg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:const BorderSide(color:_vLine)))));
 Future<void> addVehicle()async{final plate=TextEditingController(),slot=TextEditingController(),key=TextEditingController(),note=TextEditingController();String? area=areas.isEmpty?null:areas.first['name']?.toString();await showDialog(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(backgroundColor:_vPanel,title:const Text('Aracı Valeye Al',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:SizedBox(width:430,child:Column(mainAxisSize:MainAxisSize.min,children:[field(plate,'Plaka'),if(areas.isNotEmpty)DropdownButtonFormField<String>(initialValue:area,dropdownColor:_vPanel,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Park alanı'),items:areas.map((x)=>DropdownMenuItem(value:x['name'].toString(),child:Text(x['name'].toString()))).toList(),onChanged:(v)=>setD(()=>area=v)),const SizedBox(height:10),field(slot,'Park yeri / slot'),field(key,'Anahtar konumu'),field(note,'Not')])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{if(plate.text.trim().isEmpty)return;final ok=await post('/api/business/valet/accept',{'plate':plate.text,'parkingArea':area,'parkingSlot':slot.text,'keyLocation':key.text,'note':note.text});if(ok&&d.mounted)Navigator.pop(d);},child:const Text('Aracı Al'))])));}
 Future<void> addStaff()async{
  final name=TextEditingController(),phone=TextEditingController(),pin=TextEditingController();
  await showDialog(context:context,builder:(d)=>AlertDialog(
   backgroundColor:_vPanel,
   title:const Text('Vale Personeli Ekle',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),
   content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[field(name,'Ad soyad'),field(phone,'Telefon'),field(pin,'4-8 haneli PIN')])),
   actions:[
    TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),
    FilledButton(onPressed:()async{
     final n=name.text.trim(),p=pin.text.trim();
     if(n.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Personel adı gerekli.')));return;}
     if(!RegExp(r'^\d{4,8}$').hasMatch(p)){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('PIN yalnızca 4-8 rakam olmalı. Örnek: 1234')));return;}
     final ok=await post('/api/business/valet/staff',{'name':n,'phone':phone.text.trim(),'pin':p});
     if(ok&&d.mounted)Navigator.pop(d);
    },child:const Text('Ekle'))
   ]));
 }
 Future<void> addArea()async{final name=TextEditingController(),slots=TextEditingController();await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_vPanel,title:const Text('Park Alanı Ekle',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[field(name,'Alan adı (örn. B2 Katı)'),field(slots,'Kapasite')])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{final ok=await post('/api/business/valet/areas',{'name':name.text,'slots':int.tryParse(slots.text)});if(ok&&d.mounted)Navigator.pop(d);},child:const Text('Kaydet'))]));}
 @override Widget build(BuildContext context){
  if(loading)return const Center(child:Padding(padding:EdgeInsets.all(50),child:CircularProgressIndicator(color:_vPurple)));
  if(!enabled)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('CepQontag Vale',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:18),box(Column(children:[const Icon(Icons.local_parking_rounded,color:_vPurple,size:62),const SizedBox(height:12),const Text('Vale modülü henüz aktif değil',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('Bu işletme için Vale özelliği yönetici tarafından etkinleştirildiğinde araç kabulü, personel ve park alanı yönetimi burada açılır.',textAlign:TextAlign.center,style:TextStyle(color:_vMuted,height:1.4)),const SizedBox(height:14),OutlinedButton.icon(onPressed:load,icon:const Icon(Icons.refresh),label:const Text('Tekrar Kontrol Et'))]))]);
  final requested=sessions.where((x)=>x['status']=='requested'||x['status']=='retrieving').length;
  return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
   Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CepQontag Vale',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Araç teslim, park ve geri çağırma operasyonu',style:TextStyle(color:_vMuted))])),IconButton(onPressed:load,icon:const Icon(Icons.refresh_rounded,color:_vMuted))]),
   if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:Colors.redAccent))),
   const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[metric('Aktif Araç',sessions.length.toString(),Icons.directions_car_filled_rounded),metric('Araç İsteği',requested.toString(),Icons.notifications_active_rounded),metric('Vale Personeli',staff.where((x)=>x['is_active']!=false).length.toString(),Icons.badge_rounded),metric('Park Alanı',areas.where((x)=>x['is_active']!=false).length.toString(),Icons.local_parking_rounded)]),
   const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[FilledButton.icon(onPressed:addVehicle,style:FilledButton.styleFrom(backgroundColor:_vLime,foregroundColor:Colors.black),icon:const Icon(Icons.add_circle),label:const Text('Aracı Valeye Al')),OutlinedButton.icon(onPressed:addStaff,icon:const Icon(Icons.person_add_alt_1),label:const Text('Personel Ekle')),OutlinedButton.icon(onPressed:addArea,icon:const Icon(Icons.add_location_alt),label:const Text('Park Alanı Ekle'))]),
   const SizedBox(height:22),const Text('Aktif Araçlar',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),
   if(sessions.isEmpty)box(const Center(child:Padding(padding:EdgeInsets.all(20),child:Text('Şu anda valede araç yok.',style:TextStyle(color:_vMuted))))) else ...sessions.map((x)=>Padding(padding:const EdgeInsets.only(bottom:9),child:sessionCard(x))),
   const SizedBox(height:18),LayoutBuilder(builder:(c,k)=>k.maxWidth<720?Column(children:[listBox('Vale Personeli',staff,Icons.badge_rounded),const SizedBox(height:12),listBox('Park Alanları',areas,Icons.local_parking_rounded)]):Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:listBox('Vale Personeli',staff,Icons.badge_rounded)),const SizedBox(width:12),Expanded(child:listBox('Park Alanları',areas,Icons.local_parking_rounded))])),
   const SizedBox(height:18),box(const ListTile(contentPadding:EdgeInsets.zero,leading:Icon(Icons.android_rounded,color:_vLime,size:34),title:Text('Vale APK',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),subtitle:Text('Vale personel uygulaması hazır olduğunda güvenli indirme bağlantısı burada gösterilecek.',style:TextStyle(color:_vMuted)),trailing:Chip(label:Text('Hazırlanıyor'))))
  ]);
 }
 Widget metric(String t,String v,IconData i)=>SizedBox(width:190,child:box(Row(children:[Icon(i,color:_vPurple,size:27),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:_vMuted,fontSize:11))]))])));
 Widget sessionCard(Map<String,dynamic> x){final s=(x['status']??'parked').toString();final labels={'parked':'Parkta','requested':'Araç İsteniyor','retrieving':'Getiriliyor','ready':'Hazır','delivered':'Teslim Edildi'};final next={'parked':'requested','requested':'retrieving','retrieving':'ready','ready':'delivered'};final nextLabels={'parked':'Araç İstendi','requested':'Getiriliyor','retrieving':'Hazır','ready':'Teslim Et'};final n=next[s];return box(Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:_vPurple.withValues(alpha:.14),borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.directions_car,color:_vPurple)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((x['plate']??'-').toString(),style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),Text((x['parking_area']??'Alan yok').toString()+' • '+(x['parking_slot']??'Slot yok').toString()+' • Anahtar: '+(x['key_location']??'-').toString(),style:const TextStyle(color:_vMuted,fontSize:11)),Text(labels[s]??s,style:TextStyle(color:s=='requested'?Colors.orangeAccent:s=='ready'?_vLime:_vPurple,fontWeight:FontWeight.w800,fontSize:11))])),if(n!=null)FilledButton(onPressed:()=>setStatus(x['id'].toString(),n),child:Text(nextLabels[s]!))]));}
 Widget listBox(String title,List<Map<String,dynamic>> xs,IconData icon)=>box(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),const SizedBox(height:8),if(xs.isEmpty)const Text('Kayıt yok',style:TextStyle(color:_vMuted)) else ...xs.take(6).map((x)=>ListTile(dense:true,contentPadding:EdgeInsets.zero,leading:Icon(icon,color:_vPurple),title:Text((x['name']??'-').toString(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700)),subtitle:x['phone']!=null?Text(x['phone'].toString(),style:const TextStyle(color:_vMuted)):null))]));
 Widget box(Widget child)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_vPanel,borderRadius:BorderRadius.circular(18),border:Border.all(color:_vLine)),child:child);
}
).hasMatch(p)){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('PIN yalnızca 4-8 rakam olmalı. Örnek: 1234')));return;}final ok=await post('/api/business/valet/staff',{'name':n,'phone':phone.text.trim(),'pin':p});if(ok&&d.mounted)Navigator.pop(d);},child:const Text('Ekle'))]));}
 Future<void> addArea()async{final name=TextEditingController(),slots=TextEditingController();await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_vPanel,title:const Text('Park Alanı Ekle',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[field(name,'Alan adı (örn. B2 Katı)'),field(slots,'Kapasite')])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{final ok=await post('/api/business/valet/areas',{'name':name.text,'slots':int.tryParse(slots.text)});if(ok&&d.mounted)Navigator.pop(d);},child:const Text('Kaydet'))]));}
 @override Widget build(BuildContext context){
  if(loading)return const Center(child:Padding(padding:EdgeInsets.all(50),child:CircularProgressIndicator(color:_vPurple)));
  if(!enabled)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('CepQontag Vale',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:18),box(Column(children:[const Icon(Icons.local_parking_rounded,color:_vPurple,size:62),const SizedBox(height:12),const Text('Vale modülü henüz aktif değil',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:7),const Text('Bu işletme için Vale özelliği yönetici tarafından etkinleştirildiğinde araç kabulü, personel ve park alanı yönetimi burada açılır.',textAlign:TextAlign.center,style:TextStyle(color:_vMuted,height:1.4)),const SizedBox(height:14),OutlinedButton.icon(onPressed:load,icon:const Icon(Icons.refresh),label:const Text('Tekrar Kontrol Et'))]))]);
  final requested=sessions.where((x)=>x['status']=='requested'||x['status']=='retrieving').length;
  return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
   Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CepQontag Vale',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Araç teslim, park ve geri çağırma operasyonu',style:TextStyle(color:_vMuted))])),IconButton(onPressed:load,icon:const Icon(Icons.refresh_rounded,color:_vMuted))]),
   if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:Colors.redAccent))),
   const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[metric('Aktif Araç',sessions.length.toString(),Icons.directions_car_filled_rounded),metric('Araç İsteği',requested.toString(),Icons.notifications_active_rounded),metric('Vale Personeli',staff.where((x)=>x['is_active']!=false).length.toString(),Icons.badge_rounded),metric('Park Alanı',areas.where((x)=>x['is_active']!=false).length.toString(),Icons.local_parking_rounded)]),
   const SizedBox(height:18),Wrap(spacing:10,runSpacing:10,children:[FilledButton.icon(onPressed:addVehicle,style:FilledButton.styleFrom(backgroundColor:_vLime,foregroundColor:Colors.black),icon:const Icon(Icons.add_circle),label:const Text('Aracı Valeye Al')),OutlinedButton.icon(onPressed:addStaff,icon:const Icon(Icons.person_add_alt_1),label:const Text('Personel Ekle')),OutlinedButton.icon(onPressed:addArea,icon:const Icon(Icons.add_location_alt),label:const Text('Park Alanı Ekle'))]),
   const SizedBox(height:22),const Text('Aktif Araçlar',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),
   if(sessions.isEmpty)box(const Center(child:Padding(padding:EdgeInsets.all(20),child:Text('Şu anda valede araç yok.',style:TextStyle(color:_vMuted))))) else ...sessions.map((x)=>Padding(padding:const EdgeInsets.only(bottom:9),child:sessionCard(x))),
   const SizedBox(height:18),LayoutBuilder(builder:(c,k)=>k.maxWidth<720?Column(children:[listBox('Vale Personeli',staff,Icons.badge_rounded),const SizedBox(height:12),listBox('Park Alanları',areas,Icons.local_parking_rounded)]):Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:listBox('Vale Personeli',staff,Icons.badge_rounded)),const SizedBox(width:12),Expanded(child:listBox('Park Alanları',areas,Icons.local_parking_rounded))])),
   const SizedBox(height:18),box(const ListTile(contentPadding:EdgeInsets.zero,leading:Icon(Icons.android_rounded,color:_vLime,size:34),title:Text('Vale APK',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),subtitle:Text('Vale personel uygulaması hazır olduğunda güvenli indirme bağlantısı burada gösterilecek.',style:TextStyle(color:_vMuted)),trailing:Chip(label:Text('Hazırlanıyor'))))
  ]);
 }
 Widget metric(String t,String v,IconData i)=>SizedBox(width:190,child:box(Row(children:[Icon(i,color:_vPurple,size:27),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(t,style:const TextStyle(color:_vMuted,fontSize:11))]))])));
 Widget sessionCard(Map<String,dynamic> x){final s=(x['status']??'parked').toString();final labels={'parked':'Parkta','requested':'Araç İsteniyor','retrieving':'Getiriliyor','ready':'Hazır','delivered':'Teslim Edildi'};final next={'parked':'requested','requested':'retrieving','retrieving':'ready','ready':'delivered'};final nextLabels={'parked':'Araç İstendi','requested':'Getiriliyor','retrieving':'Hazır','ready':'Teslim Et'};final n=next[s];return box(Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:_vPurple.withValues(alpha:.14),borderRadius:BorderRadius.circular(13)),child:const Icon(Icons.directions_car,color:_vPurple)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text((x['plate']??'-').toString(),style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),Text((x['parking_area']??'Alan yok').toString()+' • '+(x['parking_slot']??'Slot yok').toString()+' • Anahtar: '+(x['key_location']??'-').toString(),style:const TextStyle(color:_vMuted,fontSize:11)),Text(labels[s]??s,style:TextStyle(color:s=='requested'?Colors.orangeAccent:s=='ready'?_vLime:_vPurple,fontWeight:FontWeight.w800,fontSize:11))])),if(n!=null)FilledButton(onPressed:()=>setStatus(x['id'].toString(),n),child:Text(nextLabels[s]!))]));}
 Widget listBox(String title,List<Map<String,dynamic>> xs,IconData icon)=>box(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),const SizedBox(height:8),if(xs.isEmpty)const Text('Kayıt yok',style:TextStyle(color:_vMuted)) else ...xs.take(6).map((x)=>ListTile(dense:true,contentPadding:EdgeInsets.zero,leading:Icon(icon,color:_vPurple),title:Text((x['name']??'-').toString(),style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700)),subtitle:x['phone']!=null?Text(x['phone'].toString(),style:const TextStyle(color:_vMuted)):null))]));
 Widget box(Widget child)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_vPanel,borderRadius:BorderRadius.circular(18),border:Border.all(color:_vLine)),child:child);
}
