import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';

const _bg=Color(0xFF07111F),_panel=Color(0xFF101A30),_line=Color(0xFF27355D),_purple=Color(0xFF713BFF),_muted=Color(0xFFA7B0C7);

const _businessApi='https://heycar-api-185-165-46-213.nip.io';

class BusinessPanelPage extends StatefulWidget{const BusinessPanelPage({super.key});@override State<BusinessPanelPage> createState()=>_BusinessPanelPageState();}
class _BusinessPanelPageState extends State<BusinessPanelPage>{
 int tab=0; String token='';
 final campaigns=const [
  ('%30 İndirim','Premium Oto Yıkama','1 Eyl - 30 Eyl','4.2K','320',true,Icons.local_car_wash_rounded),
  ('%25 İndirim','Detaylı İç Temizlik','5 Eyl - 30 Eyl','2.1K','156',true,Icons.auto_awesome_rounded),
  ('3 Al 2 Öde','Tüm Lastik Markalarında','1 Eyl - 15 Eyl','1.8K','98',false,Icons.tire_repair_rounded),
 ];
 @override Widget build(BuildContext context){final desktop=MediaQuery.sizeOf(context).width>=900;return Scaffold(backgroundColor:_bg,bottomNavigationBar:desktop?null:_Bottom(tab:tab,onTap:(i)=>setState(()=>tab=i)),body:SafeArea(child:Row(children:[if(desktop)_Side(tab:tab,onTap:(i)=>setState(()=>tab=i)),Expanded(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1180),child:SingleChildScrollView(padding:EdgeInsets.all(desktop?28:16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_Header(desktop:desktop,onLogin:()=>_showAuth(context)),const SizedBox(height:16),_Hero(),const SizedBox(height:16),_Stats(desktop:desktop),const SizedBox(height:16),SizedBox(width:double.infinity,height:48,child:FilledButton.icon(onPressed:()=>_showCampaign(context),style:FilledButton.styleFrom(backgroundColor:_purple,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(15))),icon:const Icon(Icons.add_circle_rounded),label:const Text('Yeni Kampanya Oluştur',style:TextStyle(fontWeight:FontWeight.w900)))),const SizedBox(height:16),if(!desktop)_Quick(),if(!desktop)const SizedBox(height:16),desktop?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:2,child:_Campaigns(items:campaigns)),const SizedBox(width:16),Expanded(child:Column(children:[_Profile(),const SizedBox(height:16),_Quick()]))]):Column(children:[_Campaigns(items:campaigns),const SizedBox(height:16),_Profile()]),const SizedBox(height:20)]))))]))));}
 Future<void> _showCampaign(BuildContext context) async {final title=TextEditingController(),desc=TextEditingController(),badge=TextEditingController(),code=TextEditingController();DateTime start=DateTime.now(),end=DateTime.now().add(const Duration(days:30));await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_panel,title:const Text('Yeni Kampanya Oluştur',style:TextStyle(color:Colors.white)),content:SizedBox(width:430,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[_Field(title,'Kampanya başlığı'),_Field(desc,'Açıklama'),_Field(badge,'İndirim etiketi (%30 İndirim)'),_Field(code,'Kampanya kodu')]))),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()async{if(token.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Önce işletme hesabıyla giriş yapmalısın.')));return;}final r=await http.post(Uri.parse('\$_businessApi/api/business/campaigns'),headers:{'Content-Type':'application/json','Authorization':'Bearer \$token'},body:jsonEncode({'title':title.text,'description':desc.text,'badge':badge.text,'couponCode':code.text,'startsAt':start.toIso8601String(),'endsAt':end.toIso8601String()}));if(d.mounted&&r.statusCode==201)Navigator.pop(d);},child:const Text('Yayınla'))]));}
 Future<void> _showAuth(BuildContext context,{bool register=false}) async {final email=TextEditingController(),pw=TextEditingController(),name=TextEditingController(),cat=TextEditingController();await showDialog(context:context,builder:(d)=>AlertDialog(backgroundColor:_panel,title:Text(register?'İşletme Kaydı':'İşletme Girişi',style:const TextStyle(color:Colors.white)),content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[if(register)_Field(name,'İşletme adı'),if(register)_Field(cat,'Kategori'),_Field(email,'E-posta'),_Field(pw,'Şifre',secret:true)])),actions:[if(!register)TextButton(onPressed:(){Navigator.pop(d);_showAuth(context,register:true);},child:const Text('Kayıt Ol')),FilledButton(onPressed:()async{final path=register?'register':'login';final body=register?{'email':email.text,'password':pw.text,'name':name.text,'category':cat.text}:{'email':email.text,'password':pw.text};final r=await http.post(Uri.parse('\$_businessApi/api/business/auth/\$path'),headers:{'Content-Type':'application/json'},body:jsonEncode(body));if(r.statusCode==200||r.statusCode==201){final j=jsonDecode(r.body);setState(()=>token=String(j['token']??''));if(d.mounted)Navigator.pop(d);}else if(d.mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Giriş/kayıt başarısız.')));}},child:Text(register?'Kayıt Ol':'Giriş Yap'))]));}
}
class _Field extends StatelessWidget{const _Field(this.c,this.label,{this.secret=false});final TextEditingController c;final String label;final bool secret;@override Widget build(BuildContext x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,obscureText:secret,style:const TextStyle(color:Colors.white),decoration:InputDecoration(labelText:label,labelStyle:const TextStyle(color:_muted),filled:true,fillColor:_bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))));}
class _Header extends StatelessWidget{const _Header({required this.desktop,required this.onLogin});final bool desktop;final VoidCallback onLogin;@override Widget build(BuildContext c)=>Row(children:[Image.asset('assets/Logoqr.png',height:desktop?42:32),const SizedBox(width:16),Container(width:1,height:35,color:_line),const SizedBox(width:14),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('İşletme Paneli',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),Text('İşletmeni yönet, daha fazla müşteriye ulaş.',style:TextStyle(color:_muted,fontSize:10))])),IconButton(onPressed:onLogin,icon:const Icon(Icons.login_rounded,color:_purple)),const Icon(Icons.notifications_none_rounded,color:_muted),const SizedBox(width:12),Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:8),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Row(children:[CircleAvatar(radius:13,backgroundColor:_purple,child:Icon(Icons.storefront,color:Colors.white,size:14)),SizedBox(width:7),Text('CleanDrive',style:TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w800)),Icon(Icons.keyboard_arrow_down,color:_muted,size:18)]))]);}
class _Hero extends StatelessWidget{@override Widget build(BuildContext c)=>Container(height:125,padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF25105D),Color(0xFF713BFF),Color(0xFF101A30)]),borderRadius:BorderRadius.circular(20),border:Border.all(color:_purple.withValues(alpha:.45))),child:const Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text('Merhaba, CleanDrive 👋',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),SizedBox(height:5),Text('Bugün de harika fırsatlar paylaş!',style:TextStyle(color:Color(0xFFD6C8FF),fontSize:12))])),Icon(Icons.directions_car_rounded,color:Colors.white,size:72)]));}
class _Stats extends StatelessWidget{const _Stats({required this.desktop});final bool desktop;@override Widget build(BuildContext c){final xs=[(Icons.groups_rounded,'Görüntülenme','12.5K','↑ %18'),(Icons.local_offer_rounded,'Kampanya Tıklama','842','↑ %27'),(Icons.location_on_rounded,'Profil Ziyareti','2.341','↑ %12'),(Icons.star_rounded,'Ortalama Puan','4.8','★★★★★')];return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:4,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:desktop?4:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:desktop?1.8:1.45),itemBuilder:(_,i){final x=xs[i];return _Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Icon(x.$1,color:i==3?Colors.amber:_purple,size:24),const SizedBox(height:6),Text(x.$2,style:const TextStyle(color:_muted,fontSize:10)),Text(x.$3,style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),Text(x.$4,style:TextStyle(color:i==3?Colors.amber:const Color(0xFF39D98A),fontSize:10,fontWeight:FontWeight.w800))]));});}}
class _Campaigns extends StatelessWidget{const _Campaigns({required this.items});final List<(String,String,String,String,String,bool,IconData)> items;@override Widget build(BuildContext c)=>_Box(child:Column(children:[const Row(children:[Expanded(child:Text('Aktif Kampanyalarım',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900))),Text('Tümünü Gör ›',style:TextStyle(color:_purple,fontSize:10,fontWeight:FontWeight.w800))]),const SizedBox(height:8),...items.map((x)=>Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:_line))),child:Row(children:[Container(width:72,height:62,decoration:BoxDecoration(color:_purple.withValues(alpha:.15),borderRadius:BorderRadius.circular(12)),child:Stack(children:[Center(child:Icon(x.$7,color:_purple,size:30)),Positioned(left:4,top:4,child:Container(padding:const EdgeInsets.symmetric(horizontal:5,vertical:3),decoration:BoxDecoration(color:const Color(0xFFFF416C),borderRadius:BorderRadius.circular(8)),child:Text(x.$1,style:const TextStyle(color:Colors.white,fontSize:7.5,fontWeight:FontWeight.w900))))])),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.$2,style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900)),Text(x.$3,style:const TextStyle(color:_muted,fontSize:9.5)),const SizedBox(height:4),Text('◉ ${x.$4}    ◇ ${x.$5}',style:const TextStyle(color:_muted,fontSize:9))])),Column(children:[Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:4),decoration:BoxDecoration(color:(x.$6?const Color(0xFF20C77A):_muted).withValues(alpha:.14),borderRadius:BorderRadius.circular(10)),child:Text(x.$6?'Aktif':'Pasif',style:TextStyle(color:x.$6?const Color(0xFF39D98A):_muted,fontSize:8.5,fontWeight:FontWeight.w900))),const SizedBox(height:6),OutlinedButton(onPressed:(){},style:OutlinedButton.styleFrom(minimumSize:const Size(68,30),padding:EdgeInsets.zero,side:const BorderSide(color:_purple)),child:const Text('Düzenle',style:TextStyle(color:_purple,fontSize:9)))])])))]));}
class _Profile extends StatelessWidget{@override Widget build(BuildContext c)=>_Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Expanded(child:Text('İşletme Profilim',style:TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900))),Text('Düzenle ›',style:TextStyle(color:_purple,fontSize:10,fontWeight:FontWeight.w800))]),const SizedBox(height:12),const Row(children:[CircleAvatar(radius:34,backgroundColor:Color(0xFF25105D),child:Icon(Icons.storefront,color:_purple,size:30)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('CleanDrive Oto Yıkama',style:TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900)),Text('⭐ 4.8 (320 yorum)',style:TextStyle(color:_muted,fontSize:10)),Text('Oto Yıkama • İstanbul',style:TextStyle(color:_muted,fontSize:10))]))]),const SizedBox(height:12),SizedBox(width:double.infinity,child:OutlinedButton(onPressed:null,child:Text('Profili Gör',style:TextStyle(color:_purple))))]));}
class _Quick extends StatelessWidget{@override Widget build(BuildContext c){final xs=[(Icons.storefront_rounded,'İşletme Bilgilerim'),(Icons.local_offer_rounded,'Kampanyalar'),(Icons.qr_code_rounded,'Kullanım Kodları'),(Icons.bar_chart_rounded,'İstatistikler')];return _Box(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Hızlı İşlemler',style:TextStyle(color:Colors.white,fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:10),Row(children:xs.map((x)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:Container(height:72,decoration:BoxDecoration(border:Border.all(color:_line),borderRadius:BorderRadius.circular(12)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(x.$1,color:_purple,size:22),const SizedBox(height:5),Text(x.$2,textAlign:TextAlign.center,style:const TextStyle(color:Colors.white,fontSize:8.5))]))))).toList())]));}}
class _Box extends StatelessWidget{const _Box({required this.child});final Widget child;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:_line)),child:child);}
class _Side extends StatelessWidget{const _Side({required this.tab,required this.onTap});final int tab;final ValueChanged<int> onTap;@override Widget build(BuildContext c)=>Container(width:210,color:const Color(0xFF091528),padding:const EdgeInsets.fromLTRB(14,28,14,14),child:Column(children:[Image.asset('assets/Logoqr.png',height:40),const SizedBox(height:30),...['Ana Sayfa','İşletme Bilgileri','Kampanyalar','Kullanım Kodları','İstatistikler','Müşteri Yorumları','Ayarlar'].asMap().entries.map((e)=>ListTile(onTap:()=>onTap(e.key),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12)),tileColor:e.key==tab?_purple:null,leading:Icon([Icons.home_rounded,Icons.storefront,Icons.local_offer,Icons.qr_code,Icons.bar_chart,Icons.chat,Icons.settings][e.key],color:e.key==tab?Colors.white:_muted,size:20),title:Text(e.value,style:TextStyle(color:e.key==tab?Colors.white:_muted,fontSize:11,fontWeight:FontWeight.w700))))]));}
class _Bottom extends StatelessWidget{const _Bottom({required this.tab,required this.onTap});final int tab;final ValueChanged<int> onTap;@override Widget build(BuildContext c)=>Container(height:74,decoration:const BoxDecoration(color:Color(0xFF0D192D),border:Border(top:BorderSide(color:_line))),child:SafeArea(top:false,child:Row(children:[(Icons.home_rounded,'Ana Sayfa'),(Icons.bar_chart_rounded,'İstatistikler'),(Icons.add_circle_rounded,'Kampanya'),(Icons.settings_rounded,'Ayarlar')].asMap().entries.map((e)=>Expanded(child:InkWell(onTap:()=>onTap(e.key),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(e.value.$1,color:e.key==tab?_purple:_muted,size:25),Text(e.value.$2,style:TextStyle(color:e.key==tab?_purple:_muted,fontSize:9.5,fontWeight:FontWeight.w700))])))).toList())));}
