import 'package:flutter/material.dart';
import 'cepqar_theme.dart';

class CepqarOffersPage extends StatefulWidget {
  const CepqarOffersPage({super.key});
  @override State<CepqarOffersPage> createState()=>_CepqarOffersPageState();
}
class _CepqarOffersPageState extends State<CepqarOffersPage>{
  String category='Tümü';
  final categories=const ['Tümü','Oto Yıkama','Detailing','Lastik','Otopark','Servis','Akaryakıt'];
  final offers=const [
    _Offer('Oto Yıkama','CleanDrive Oto Yıkama','Premium oto yıkamada %30 indirim','%30 İndirim','1.2 km','4.8','320',Icons.local_car_wash_rounded,['İç - Dış Temizlik']),
    _Offer('Detailing','AutoDetailing Studio','Detaylı iç temizlikte %25 indirim','%25 İndirim','2.4 km','4.9','156',Icons.auto_awesome_rounded,['Seramik Kaplama']),
    _Offer('Lastik','Lastikçim','Tüm lastik markalarında 3 al 2 öde','3 Al 2 Öde','3.1 km','4.7','189',Icons.tire_repair_rounded,['Montaj','Balans']),
    _Offer('Otopark','CityPark Otopark','İlk 2 saat %50 indirimli','%50 İndirim','800 m','4.6','412',Icons.local_parking_rounded,['AVM','Güvenli']),
    _Offer('Akaryakıt','Akaryakıt Fırsatı','Tüm yakıt türlerinde litre indirimi','₺1,5 İndirim','4.2 km','4.5','520',Icons.local_gas_station_rounded,['Market']),
    _Offer('Servis','AutoServis','Periyodik bakımda Cepqar indirimi','%20 İndirim','5.6 km','4.7','98',Icons.build_rounded,['Periyodik Bakım']),
  ];
  @override Widget build(BuildContext context){
    final visible=category=='Tümü'?offers:offers.where((o)=>o.category==category).toList();
    return Scaffold(backgroundColor:CepqarTheme.bg,appBar:AppBar(backgroundColor:CepqarTheme.bg,foregroundColor:CepqarTheme.text,elevation:0,title:Row(children:[Image.asset('assets/Logoqr.png',height:30),const SizedBox(width:7),Text('Fırsatlar',style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900))]),actions:[Container(margin:const EdgeInsets.only(right:12,top:8,bottom:8),padding:const EdgeInsets.symmetric(horizontal:10),decoration:BoxDecoration(border:Border.all(color:CepqarTheme.purple.withValues(alpha:.45)),borderRadius:BorderRadius.circular(20)),child:const Row(children:[Icon(Icons.location_on_rounded,color:CepqarTheme.purple,size:17),SizedBox(width:4),Text('İstanbul',style:TextStyle(fontWeight:FontWeight.w800)),Icon(Icons.keyboard_arrow_down_rounded,size:18)]))]),body:ListView(padding:const EdgeInsets.fromLTRB(16,4,16,30),children:[
      Text('Yakınındaki araç fırsatlarını keşfet',textAlign:TextAlign.center,style:TextStyle(color:CepqarTheme.muted,fontSize:13)),const SizedBox(height:4),
      Text('Oto yıkama • Detailing • Lastik • Otopark • Servis • Akaryakıt',textAlign:TextAlign.center,style:TextStyle(color:CepqarTheme.muted,fontSize:10.5)),const SizedBox(height:16),
      SizedBox(height:78,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:categories.length,separatorBuilder:(_,__)=>const SizedBox(width:8),itemBuilder:(_,i){final x=categories[i],a=x==category;final icon=x=='Tümü'?Icons.grid_view_rounded:offers.firstWhere((o)=>o.category==x).icon;return InkWell(onTap:()=>setState(()=>category=x),borderRadius:BorderRadius.circular(18),child:AnimatedContainer(duration:const Duration(milliseconds:180),width:82,padding:const EdgeInsets.all(8),decoration:BoxDecoration(gradient:a?const LinearGradient(colors:[Color(0xFF713BFF),Color(0xFF8A45FF)]):null,color:a?null:CepqarTheme.panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:a?CepqarTheme.purple:CepqarTheme.line)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:a?Colors.white:CepqarTheme.purple,size:25),const SizedBox(height:6),Text(x,textAlign:TextAlign.center,maxLines:1,style:TextStyle(color:a?Colors.white:CepqarTheme.text,fontSize:10,fontWeight:FontWeight.w800))]))); })),const SizedBox(height:16),
      Container(height:150,padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF351078),Color(0xFF713BFF),Color(0xFF171B56)]),borderRadius:BorderRadius.circular(22),border:Border.all(color:CepqarTheme.purple.withValues(alpha:.6))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[const Text('Aracına iyi bak,\ndaha fazlasını keşfet',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900,height:1.08)),const SizedBox(height:12),Text('Sana özel fırsatlar, şimdi cebinde.',style:TextStyle(color:Colors.white.withValues(alpha:.78),fontSize:11.5))])),const Icon(Icons.local_offer_rounded,color:Colors.white,size:70)])),const SizedBox(height:16),
      ...visible.map((o)=>_OfferCard(o:o)),
      Text('Kampanyalar işletmeler tarafından sağlanır. Fiyat ve koşullar işletmeye göre değişebilir.',style:TextStyle(color:CepqarTheme.muted,fontSize:9.5),textAlign:TextAlign.center),
    ]));
  }
}
class _Offer{const _Offer(this.category,this.name,this.description,this.badge,this.distance,this.rating,this.reviews,this.icon,this.tags);final String category,name,description,badge,distance,rating,reviews;final IconData icon;final List<String> tags;}
class _OfferCard extends StatelessWidget{
 const _OfferCard({required this.o});final _Offer o;
 @override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:11),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:CepqarTheme.line)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[
   Stack(children:[Container(width:94,height:108,decoration:BoxDecoration(color:CepqarTheme.purple.withValues(alpha:.12),borderRadius:BorderRadius.circular(15)),child:Icon(o.icon,color:CepqarTheme.purple,size:42)),Positioned(left:6,top:6,child:Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:5),decoration:BoxDecoration(color:const Color(0xFFFF416C),borderRadius:BorderRadius.circular(10)),child:Text(o.badge,style:const TextStyle(color:Colors.white,fontSize:9,fontWeight:FontWeight.w900))))]),const SizedBox(width:11),
   Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(o.name,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:CepqarTheme.text,fontSize:14,fontWeight:FontWeight.w900))),const Icon(Icons.location_on_outlined,color:CepqarTheme.purple,size:15),Text(o.distance,style:TextStyle(color:CepqarTheme.muted,fontSize:10))]),const SizedBox(height:3),Row(children:[const Icon(Icons.star_rounded,color:Color(0xFFFFB72B),size:16),const SizedBox(width:3),Text('${o.rating} (${o.reviews})',style:TextStyle(color:CepqarTheme.muted,fontSize:10))]),const SizedBox(height:5),Text(o.description,maxLines:2,overflow:TextOverflow.ellipsis,style:TextStyle(color:CepqarTheme.muted,fontSize:11,height:1.25)),const SizedBox(height:8),Row(children:[...([o.category,...o.tags].take(2)).map((x)=>Container(margin:const EdgeInsets.only(right:5),padding:const EdgeInsets.symmetric(horizontal:7,vertical:4),decoration:BoxDecoration(color:CepqarTheme.line.withValues(alpha:.6),borderRadius:BorderRadius.circular(9)),child:Text(x,style:TextStyle(color:CepqarTheme.text,fontSize:8.5)))),const Spacer(),SizedBox(height:32,child:FilledButton(onPressed:(){},style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple,padding:const EdgeInsets.symmetric(horizontal:11)),child:const Row(children:[Text('Detayları Gör',style:TextStyle(fontSize:9.5,fontWeight:FontWeight.w800)),SizedBox(width:2),Icon(Icons.chevron_right_rounded,size:15)])))])]))
 ]));}
