import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
const _api='https://heycar-api-185-165-46-213.nip.io';
class DriverInvitePage extends StatefulWidget{final String token;const DriverInvitePage({super.key,required this.token});@override State<DriverInvitePage> createState()=>_S();}
class _S extends State<DriverInvitePage>{final phone=TextEditingController(),name=TextEditingController(),pass=TextEditingController();Map<String,dynamic>? invite;bool busy=false;String? error;@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await http.get(Uri.parse('$_api/api/driver/invites/${widget.token}'));if(r.statusCode==200&&mounted)setState(()=>invite=jsonDecode(r.body)['invite']);else if(mounted)setState(()=>error='Davet geçersiz veya süresi dolmuş.');}catch(_){if(mounted)setState(()=>error='Davet yüklenemedi.');}}
Future<void> accept()async{setState(()=>busy=true);try{final r=await http.post(Uri.parse('$_api/api/driver/invites/${widget.token}/accept'),headers:{'Content-Type':'application/json'},body:jsonEncode({'phone':phone.text,'displayName':name.text,'password':pass.text}));final j=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300){final p=await SharedPreferences.getInstance();await p.setBool('driver_logged_in',true);await p.setString('driver_user_id',j['user']['id'].toString());await p.setString('driver_name',j['user']['displayName'].toString());if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>DriverHomePage(userId:j['user']['id'].toString())));}else if(mounted)setState(()=>error=j['error']=='PASSWORD_INVALID'?'Bu telefon kayıtlı. Şifreni kontrol et.':'Davet kabul edilemedi.');}catch(_){if(mounted)setState(()=>error='Bağlantı hatası.');}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Sürücü Daveti')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[if(invite!=null)...[const Icon(Icons.directions_car_rounded,size:64,color:Color(0xFF8B5CFF)),const SizedBox(height:14),Text('${invite!['plate']} • ${invite!['make']} ${invite!['model']??''}',textAlign:TextAlign.center,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Text('${invite!['owner_name']} seni bu araca yetkili sürücü olarak davet etti.',textAlign:TextAlign.center),const SizedBox(height:24),TextField(controller:name,decoration:const InputDecoration(labelText:'Ad Soyad')),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Telefon')),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Şifre (en az 6 karakter)')),const SizedBox(height:18),FilledButton(onPressed:busy?null:accept,child:Text(busy?'Bekle...':'Daveti Kabul Et'))],if(error!=null)Padding(padding:const EdgeInsets.only(top:16),child:Text(error!,textAlign:TextAlign.center,style:const TextStyle(color:Colors.redAccent)))])));}
class DriverHomePage extends StatefulWidget{final String userId;const DriverHomePage({super.key,required this.userId});@override State<DriverHomePage> createState()=>_DH();}
class _DH extends State<DriverHomePage>{List vehicles=[],notifications=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{final h={'x-user-id':widget.userId};final rs=await Future.wait([http.get(Uri.parse('$_api/api/driver/vehicles'),headers:h),http.get(Uri.parse('$_api/api/driver/notifications'),headers:h)]);if(mounted)setState((){vehicles=rs[0].statusCode==200?jsonDecode(rs[0].body)['vehicles']??[]:[];notifications=rs[1].statusCode==200?jsonDecode(rs[1].body)['notifications']??[]:[];loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Cepqar • Sürücü'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[const Text('Yetkili olduğun araçlar',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:12),for(final v in vehicles)Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.directions_car)),title:Text('${v['plate']} • ${v['make']} ${v['model']??''}'),subtitle:Text(v['active']==true?'Araç sahibi seni şu an aktif sürücü olarak seçti. QR bildirimleri sana gelir.':'Yetkili sürücüsün. Aktif sürücüyü araç sahibi belirler.'),trailing:v['active']==true?const Icon(Icons.check_circle,color:Colors.greenAccent):null)),const SizedBox(height:22),Row(children:[const Expanded(child:Text('Bana gelen bildirimler',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900))),Badge(label:Text('${notifications.length}'))]),const SizedBox(height:10),if(notifications.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('Henüz bildirim yok.'))),for(final n in notifications)Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.qr_code_rounded)),title:Text(n['message']?.toString().isNotEmpty==true?n['message'].toString():n['type'].toString()),subtitle:Text('${n['plate']??''} • ${n['created_at']??''}')))])));}
