import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';
import 'qr_activation.dart';
import 'vehicle_api.dart';
import 'active_driver_card.dart';
import 'vehicle_center_page.dart';

const _bg=Color(0xFF07111F),_panel=Color(0xFF101A30),_line=Color(0xFF27355D),_purple=Color(0xFF8B5CFF),_muted=Color(0xFFA7B0C7),_gold=Color(0xFFFFC857),_green=Color(0xFF38D178);
class OwnerVehiclesPage extends StatefulWidget{const OwnerVehiclesPage({super.key,this.onVehicleChanged});final VoidCallback? onVehicleChanged;@override State<OwnerVehiclesPage> createState()=>_S();}
class _S extends State<OwnerVehiclesPage>{List<Map<String,dynamic>> vehicles=[];bool loading=true,premium=false;int limit=1;String? error;String get selected=>QrDraft.vehicleId.trim().isNotEmpty?QrDraft.vehicleId.trim():OnboardingDraft.vehicleId.trim();@override void initState(){super.initState();_load();}
Future<void> _load()async{final owner=OnboardingDraft.userId.trim();if(owner.isEmpty){setState((){loading=false;error='Araç sahibi oturumu bulunamadı.';});return;}try{final r=await http.get(Uri.parse('${OnboardingBackend.baseUrl}/api/owner/vehicles'),headers:{'x-owner-id':owner}).timeout(const Duration(seconds:15));final d=jsonDecode(r.body);if(r.statusCode<200||r.statusCode>=300||d is! Map)throw Exception();final list=d['vehicles'];final next=list is List?list.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():<Map<String,dynamic>>[];if(next.isNotEmpty&&!next.any((v)=>'${v['id']}'==selected))_select(next.first,notify:false);if(!mounted)return;setState((){vehicles=next;premium=d['premium']==true;limit=int.tryParse('${d['limit']}')??1;loading=false;error=null;});}catch(_){if(mounted)setState((){loading=false;error='Araçlar yüklenemedi.';});}}
void _select(Map<String,dynamic> v,{bool notify=true}){final id='${v['id']??''}';QrDraft.vehicleId=id;OnboardingDraft.vehicleId=id;QrDraft.plate='${v['plate']??''}';QrDraft.make='${v['make']??''}';QrDraft.model='${v['model']??''}';QrDraft.token='${v['qr_token']??''}'.trim();if(notify){setState((){});widget.onVehicleChanged?.call();}}
Future<void> _qr(Map<String,dynamic> v)async{_select(v);if('${v['qr_token']??''}'.trim().isNotEmpty){_showQr(v);return;}await Navigator.push(context,MaterialPageRoute(builder:(c)=>RealQrScanPage(onBack:()=>Navigator.pop(c),onFound:(){Navigator.pop(c);_activate(v);})));}
Future<void> _activate(Map<String,dynamic> v)async{try{await QrBackend.activate(token:QrDraft.token,vehicleId:'${v['id']}',plate:'${v['plate']}',make:'${v['make']}',model:'${v['model']??''}');if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('${v['plate']} için QR aktif edildi.')));await _load();widget.onVehicleChanged?.call();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}}
void _showQr(Map<String,dynamic> v){final t='${v['qr_token']??''}'.trim(),u='https://queensho.github.io/HeyCar/?tag=${Uri.encodeComponent(t)}';showModalBottomSheet(context:context,backgroundColor:_panel,builder:(c)=>Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('${v['plate']} QR',style:const TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:14),Container(width:220,height:220,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Image.network('https://quickchart.io/qr?text=${Uri.encodeComponent(u)}&size=420',errorBuilder:(_,__,___)=>const Icon(Icons.qr_code_2,size:150,color:Colors.black))),const SizedBox(height:10),Text(t,style:const TextStyle(color:_muted,fontWeight:FontWeight.w700))])));}
void _open(Map<String,dynamic> v){_select(v);final make='${v['make']??''}',model='${v['model']??''}';Navigator.push(context,MaterialPageRoute(builder:(_)=>VehicleCenterPage(plate:'${v['plate']??''}',title:model.trim().isEmpty?make:'$make $model'))).then((_){widget.onVehicleChanged?.call();_load();});}
Future<void> _add()async{if(vehicles.length>=limit){_limit();return;}final x=await showDialog<_Form>(context:context,builder:(_)=>const _Dialog());if(x==null)return;try{final r=await http.post(Uri.parse('${OnboardingBackend.baseUrl}/api/owner/vehicles'),headers:{'Content-Type':'application/json','x-owner-id':OnboardingDraft.userId.trim()},body:jsonEncode({'plate':x.plate,'make':x.make,'model':x.model}));final d=r.body.isEmpty?{}:jsonDecode(r.body);if(r.statusCode==403){_limit();return;}if(r.statusCode==409&&d is Map&&d['error']=='PLATE_EXISTS')throw Exception('Bu plaka zaten kayıtlı.');if(r.statusCode<200||r.statusCode>=300)throw Exception('Araç eklenemedi.');await _load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}}
void _limit()=>showDialog<void>(context:context,builder:(c)=>AlertDialog(backgroundColor:_panel,title:Text(premium?'Premium araç limiti doldu':'Premium ile 3 araç ekle',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:Text(premium?'En fazla 3 araç ekleyebilirsin.':'Standart hesapta 1, Premium ile 3 araç ekleyebilirsin.',style:const TextStyle(color:_muted)),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Tamam'))]));
@override Widget build(BuildContext context){final top=MediaQuery.paddingOf(context).top;return Scaffold(backgroundColor:_bg,body:RefreshIndicator(onRefresh:_load,color:_purple,child:ListView(padding:EdgeInsets.fromLTRB(14,top+14,14,26),children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Araçlarım',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Kayıtlı araçlarını yönet.',style:TextStyle(color:_muted,fontSize:13))])),FilledButton.icon(onPressed:loading?null:_add,style:FilledButton.styleFrom(backgroundColor:_purple),icon:const Icon(Icons.add),label:const Text('Yeni Araç'))]),const SizedBox(height:12),Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(15),border:Border.all(color:premium?_gold:_line)),child:Text(premium?'Premium • ${vehicles.length}/3 araç':'Standart • ${vehicles.length}/1 araç',style:TextStyle(color:premium?_gold:_muted,fontWeight:FontWeight.w800))),const SizedBox(height:14),if(loading)const Center(child:Padding(padding:EdgeInsets.all(36),child:CircularProgressIndicator(color:_purple)))else if(error!=null)Center(child:Text(error!,style:const TextStyle(color:_muted)))else ...vehicles.map((v)=>Padding(padding:const EdgeInsets.only(bottom:12),child:_Card(v:v,selected:'${v['id']}'==selected,open:()=>_open(v),select:()=>_select(v),qr:()=>_qr(v)))),if(!loading&&vehicles.length<limit)OutlinedButton.icon(onPressed:_add,icon:const Icon(Icons.add_circle_outline),label:Text(premium?'Yeni araç ekle • ${limit-vehicles.length} hakkın kaldı':'Yeni araç ekle')),const SizedBox(height:16),const ActiveDriverCard(),const SizedBox(height:14),Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Text('Her aracın QR’ı, bildirimleri, bakım, sigorta, kasko ve park bilgileri birbirinden ayrıdır.',style:TextStyle(color:_muted,height:1.4)))])));}}
class _Card extends StatelessWidget{const _Card({required this.v,required this.selected,required this.open,required this.select,required this.qr});final Map<String,dynamic> v;final bool selected;final VoidCallback open,select,qr;@override Widget build(BuildContext context){final make='${v['make']??''}',model='${v['model']??''}',hasQr='${v['qr_token']??''}'.trim().isNotEmpty,logo=VehicleApi.brandLogoUrl(make);return Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(22),border:Border.all(color:selected?_purple:_line,width:selected?1.6:1)),child:Column(children:[InkWell(onTap:open,child:Row(children:[Container(width:68,height:60,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:_bg,borderRadius:BorderRadius.circular(16)),child:logo==null?const Icon(Icons.directions_car_filled_rounded,color:_purple,size:32):Image.network(logo,errorBuilder:(_,__,___)=>const Icon(Icons.directions_car_filled_rounded,color:_purple))),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(model.isEmpty?make:'$make $model',style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),Text('${v['plate']??''}',style:const TextStyle(color:_muted,fontSize:14,fontWeight:FontWeight.w800)),if(selected)const Padding(padding:EdgeInsets.only(top:4),child:Text('Seçili araç',style:TextStyle(color:_purple,fontSize:11,fontWeight:FontWeight.w900)))])),const Icon(Icons.chevron_right,color:_muted)])),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:selected?null:select,icon:Icon(selected?Icons.check_circle:Icons.swap_horiz),label:Text(selected?'Seçili':'Bu aracı seç'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:qr,style:FilledButton.styleFrom(backgroundColor:hasQr?_green:_purple),icon:Icon(hasQr?Icons.check_circle_rounded:Icons.qr_code_scanner),label:Text(hasQr?'QR Aktif':'QR Aktif Et')))] )]));}}
class _Form{const _Form(this.plate,this.make,this.model);final String plate,make,model;}
class _Dialog extends StatefulWidget{const _Dialog();@override State<_Dialog> createState()=>_D();}class _D extends State<_Dialog>{final p=TextEditingController();String? make,model;List<String> makes=[],models=[];bool loading=true;@override void initState(){super.initState();VehicleApi.getMakes().then((x){if(mounted)setState((){makes=x;loading=false;});});}@override Widget build(BuildContext c)=>AlertDialog(backgroundColor:_panel,title:const Text('Yeni Araç',style:TextStyle(color:Colors.white)),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:p,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Plaka')),const SizedBox(height:10),if(loading)const CircularProgressIndicator()else DropdownButtonFormField<String>(dropdownColor:_panel,items:makes.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)async{make=x;models=await VehicleApi.getModels(x!);if(mounted)setState((){});},decoration:const InputDecoration(labelText:'Marka')),const SizedBox(height:10),DropdownButtonFormField<String>(dropdownColor:_panel,items:models.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>model=x,decoration:const InputDecoration(labelText:'Model'))]),actions:[FilledButton(onPressed:(){if(p.text.trim().isNotEmpty&&make!=null)Navigator.pop(c,_Form(p.text.trim().toUpperCase(),make!,model??''));},child:const Text('Aracı Ekle'))]);}
