import 'dart:convert';
import 'package:flutter/material.dart';
import 'owner_auth.dart';
import 'onboarding_backend.dart';
class OwnerValetCard extends StatefulWidget{const OwnerValetCard({super.key,required this.vehicleId});final String vehicleId;@override State<OwnerValetCard> createState()=>_S();}
class _S extends State<OwnerValetCard>{Map<String,dynamic>? session;bool loading=true,busy=false;String deliveryCode='';@override void initState(){super.initState();load();}
Future<void> load()async{if(widget.vehicleId.isEmpty){if(mounted)setState(()=>loading=false);return;}try{final r=await OwnerHttp.get(Uri.parse(OnboardingBackend.baseUrl+'/api/owner/valet/'+widget.vehicleId),json:false);if(!mounted)return;if(r.statusCode==200){final j=jsonDecode(r.body);setState((){session=j['session'] is Map?Map<String,dynamic>.from(j['session']):null;loading=false;});}else setState(()=>loading=false);}catch(_){if(mounted)setState(()=>loading=false);}}
Future<void> request()async{setState(()=>busy=true);try{final r=await OwnerHttp.post(Uri.parse(OnboardingBackend.baseUrl+'/api/owner/valet/'+widget.vehicleId+'/request'));if(r.statusCode>=200&&r.statusCode<300){final j=jsonDecode(r.body);if(mounted)setState(()=>deliveryCode=(j['deliveryCode']??'').toString());await load();}else if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Araç isteği gönderilemedi.')));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Bağlantı hatası.')));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context){if(loading)return const SizedBox.shrink();final s=session;if(s==null)return const SizedBox.shrink();final st=(s!['status']??'parked').toString(),venue=(s['business_name']??'CepQontag Vale').toString();final labels={'parked':'Aracınız valede','requested':'Aracınız isteniyor','retrieving':'Valeniz aracınızı getiriyor','ready':'Aracınız hazır'};final area=(s['parking_area']??'').toString(),slot=(s['parking_slot']??'').toString();return Container(margin:const EdgeInsets.fromLTRB(16,8,16,8),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF101A30),borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFF713BFF).withValues(alpha:.45))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.local_parking_rounded,color:Color(0xFFB6FF2A)),SizedBox(width:8),Text('CepQontag Vale',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:16))]),const SizedBox(height:10),Text(labels[st]??'Vale işlemi devam ediyor',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:3),Text(venue,style:const TextStyle(color:Color(0xFFA7B0C7))),if(area.isNotEmpty)Padding(padding:const EdgeInsets.only(top:5),child:Text('Park: '+area+(slot.isEmpty?'':' / '+slot),style:const TextStyle(color:Color(0xFFA7B0C7),fontSize:12))),if(deliveryCode.isNotEmpty&&st!='parked')Container(margin:const EdgeInsets.only(top:13),width:double.infinity,padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFB6FF2A).withValues(alpha:.10),borderRadius:BorderRadius.circular(14),border:Border.all(color:const Color(0xFFB6FF2A).withValues(alpha:.35))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('TESLİM KODUNUZ',style:TextStyle(color:Color(0xFFA7B0C7),fontSize:11,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(deliveryCode,style:const TextStyle(color:Color(0xFFB6FF2A),fontSize:28,fontWeight:FontWeight.w900,letterSpacing:7)),const Text('Aracınız size getirildiğinde bu kodu vale personeline söyleyin.',style:TextStyle(color:Color(0xFFA7B0C7),fontSize:11))]),const SizedBox(height:13),if(st=='parked')SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:busy?null:request,style:FilledButton.styleFrom(backgroundColor:const Color(0xFFB6FF2A),foregroundColor:Colors.black,padding:const EdgeInsets.symmetric(vertical:14)),icon:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.directions_car_filled_rounded),label:const Text('Aracımı Getir',style:TextStyle(fontWeight:FontWeight.w900))))else Row(children:[const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Color(0xFF713BFF))),const SizedBox(width:9),Expanded(child:Text(labels[st]??'Vale işlemi sürüyor',style:const TextStyle(color:Color(0xFFB6FF2A),fontWeight:FontWeight.w800)))]) ]));}}
