import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:url_launcher/url_launcher.dart';
import 'onboarding_backend.dart';
import 'owner_chat_page.dart';
import 'cepqar_theme.dart';

const _purple=Color(0xFF8B5CFF);
Color get _bg=>CepqarTheme.bg;
Color get _panel=>CepqarTheme.panel;
Color get _panel2=>CepqarTheme.panel;
Color get _line=>CepqarTheme.line;
Color get _muted=>CepqarTheme.muted;
Color get _text=>CepqarTheme.text;
final ValueNotifier<int> ownerUnreadNotificationCount=ValueNotifier<int>(0);
class OwnerNotificationsPage extends StatefulWidget{const OwnerNotificationsPage({super.key,this.vehicleId='',this.plate=''});final String vehicleId,plate;@override State<OwnerNotificationsPage> createState()=>_S();}
class _S extends State<OwnerNotificationsPage>{static const base='https://heycar-api-185-165-46-213.nip.io';List<Map<String,dynamic>> items=[];bool loading=true;String? error;Timer? timer;int tab=0;@override void initState(){super.initState();_load();timer=Timer.periodic(const Duration(seconds:15),(_)=>_load(silent:true));}@override void dispose(){timer?.cancel();super.dispose();}
Future<void> _load({bool silent=false})async{final o=OnboardingDraft.userId.trim();if(o.isEmpty)return;if(!silent&&mounted)setState(()=>loading=true);try{final r=await http.get(Uri.parse('$base/api/owner/notifications'),headers:{'x-owner-id':o});final d=jsonDecode(r.body);if(r.statusCode<200||r.statusCode>=300||d is! Map||d['notifications'] is! List)throw Exception();var next=(d['notifications'] as List).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();if(widget.vehicleId.isNotEmpty)next=next.where((e)=>'${e['vehicle_id']}'==widget.vehicleId).toList();ownerUnreadNotificationCount.value=next.where((e)=>e['status']=='new').length;if(mounted)setState((){items=next;loading=false;error=null;});}catch(_){if(mounted&&!silent)setState((){loading=false;error='Bildirimler alınamadı. Tekrar dene.';});}}
Future<void> _status(Map<String,dynamic> n,String s)async{final id='${n['id']??''}';if(id.isEmpty)return;try{await http.patch(Uri.parse('$base/api/owner/notifications/$id'),headers:{'Content-Type':'application/json','x-owner-id':OnboardingDraft.userId.trim()},body:jsonEncode({'status':s}));await _load(silent:true);}catch(_){}}
void _reply(Map<String,dynamic> n){if(n['status']=='new')_status(n,'read');Navigator.push(context,MaterialPageRoute(builder:(_)=>OwnerChatPage(notificationId:'${n['id']}',plate:'${n['plate']??''}')));}
String title(String t)=>{'move_vehicle':'Araç Çekme Talebi','lights_on':'Far Uyarısı','damage':'Hasar Bildirimi','call_request':'Gizli Arama Talebi'}[t]??'Mesaj';IconData icon(String t)=>{'lights_on':Icons.lightbulb_rounded,'damage':Icons.warning_amber_rounded,'call_request':Icons.phone_rounded,'move_vehicle':Icons.directions_car_filled_rounded}[t]??Icons.chat_bubble_rounded;String time(dynamic x){final d=DateTime.tryParse('$x')?.toLocal();if(d==null)return'';final q=DateTime.now().difference(d);if(q.inMinutes<1)return'Şimdi';if(q.inMinutes<60)return'${q.inMinutes} dk önce';if(q.inHours<24)return'${q.inHours} sa önce';return'${d.day}.${d.month}';}
List<Map<String,dynamic>> get filtered=>tab==0?items:items.where((e)=>tab==1?e['status']=='new':tab==2?(e['status']=='read'||e['status']=='arriving'):e['status']=='resolved').toList();
@override Widget build(BuildContext c){final unread=items.where((e)=>e['status']=='new').length;return ColoredBox(color:_bg,child:SafeArea(bottom:false,child:RefreshIndicator(onRefresh:_load,color:_purple,child:ListView(padding:const EdgeInsets.all(18),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Bildirimler',style:TextStyle(color:_text,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(widget.plate.isEmpty?'Seçili aracın bildirimleri':'${widget.plate} • seçili araç',style:TextStyle(color:_muted,fontSize:13.5))])),IconButton(onPressed:_load,icon:Icon(Icons.refresh,color:_text))]),const SizedBox(height:18),Row(children:[for(final x in [(0,'Tümü'),(1,'Yeni'),(2,'Okundu'),(3,'Çözüldü')])...[_Tab(x.$2,tab==x.$1,badge:x.$1<2&&unread>0?unread:null,tap:()=>setState(()=>tab=x.$1)),if(x.$1<3)const SizedBox(width:7)]]),const SizedBox(height:18),if(loading)const Padding(padding:EdgeInsets.all(44),child:Center(child:CircularProgressIndicator(color:_purple)))else if(error!=null)_state(Icons.error_outline,error!)else if(filtered.isEmpty)_state(Icons.notifications_none,'Bu araç için bildirim yok.')else ...filtered.map(card)]))));}
Widget _state(IconData i,String t)=>Container(padding:const EdgeInsets.all(36),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:Column(children:[Icon(i,color:_muted,size:40),const SizedBox(height:10),Text(t,style:TextStyle(color:_muted,fontWeight:FontWeight.w700))]));
Widget card(Map<String,dynamic> n){final t='${n['type']??'message'}',fresh=n['status']=='new',trackable=t!='message'&&t!='call_request',photo='${n['photo_path']??''}',lat=double.tryParse('${n['latitude']??''}'),lng=double.tryParse('${n['longitude']??''}');return InkWell(onTap:trackable&&fresh?()=>_status(n,'read'):null,borderRadius:BorderRadius.circular(20),child:Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:Column(children:[Row(children:[Container(width:58,height:58,decoration:BoxDecoration(color:_purple.withValues(alpha:.15),borderRadius:BorderRadius.circular(14)),child:Icon(icon(t),color:_purple)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title(t),style:TextStyle(color:_text,fontWeight:FontWeight.w900))),Text(time(n['created_at']),style:TextStyle(color:_muted,fontSize:11)),if(fresh)const Padding(padding:EdgeInsets.only(left:6),child:CircleAvatar(radius:4,backgroundColor:Color(0xFFFF4D63)))]),if('${n['message']??''}'.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Text('${n['message']}',style:TextStyle(color:_muted))),Padding(padding:const EdgeInsets.only(top:5),child:Text('${n['plate']??''}',style:TextStyle(color:_muted,fontSize:12))) ]))]),if(photo.isNotEmpty||(lat!=null&&lng!=null))Padding(padding:const EdgeInsets.only(top:10),child:Row(children:[if(photo.isNotEmpty)Expanded(child:TextButton.icon(onPressed:()=>launchUrl(Uri.parse(photo.startsWith('http')?photo:'$base$photo')),icon:const Icon(Icons.image),label:const Text('Fotoğraf'))),if(lat!=null&&lng!=null)Expanded(child:TextButton.icon(onPressed:()=>launchUrl(Uri.parse('https://www.google.com/maps/search/?api=1&query=$lat,$lng')),icon:const Icon(Icons.location_on),label:const Text('Konum')))])),const SizedBox(height:8),Row(children:[Expanded(child:trackable?FilledButton.icon(onPressed:n['status']=='new'?()=>_status(n,'read'):n['status']=='read'?()=>_status(n,'arriving'):null,style:FilledButton.styleFrom(backgroundColor:n['status']=='arriving'?const Color(0xFF38D178):_purple,foregroundColor:Colors.white),icon:Icon(n['status']=='new'?Icons.visibility_rounded:Icons.directions_walk_rounded,size:18),label:Text(n['status']=='new'?'Gördüm':n['status']=='read'?'Geliyorum':'Geliyorum ✓')):FilledButton.icon(onPressed:()=>_reply(n),style:FilledButton.styleFrom(backgroundColor:_purple,foregroundColor:Colors.white),icon:const Icon(Icons.reply,size:18),label:const Text('Cevapla'))),const SizedBox(width:8),Expanded(child:TextButton(onPressed:n['status']=='resolved'?null:()=>_status(n,'resolved'),child:Text(n['status']=='resolved'?'Çözüldü ✓':'Çözüldü',style:TextStyle(color:_muted))))]) ])));}}
class _Tab extends StatelessWidget{const _Tab(this.text,this.active,{required this.tap,this.badge});final String text;final bool active;final VoidCallback tap;final int? badge;@override Widget build(BuildContext c)=>Expanded(child:InkWell(onTap:tap,borderRadius:BorderRadius.circular(16),child:Container(height:46,alignment:Alignment.center,decoration:BoxDecoration(color:active?_purple:_panel2,borderRadius:BorderRadius.circular(16),border:Border.all(color:active?_purple:_line)),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Flexible(child:Text(text,overflow:TextOverflow.ellipsis,style:TextStyle(color:active?Colors.white:_muted,fontSize:11.5,fontWeight:FontWeight.w800))),if(badge!=null)...[const SizedBox(width:4),CircleAvatar(radius:9,backgroundColor:const Color(0xFFFF4D63),child:Text('$badge',style:const TextStyle(color:Colors.white,fontSize:9)))]]))));}
