import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';
import 'vehicle_api.dart';
import 'active_driver_card.dart';
import 'vehicle_center_page.dart';

const _bg=Color(0xFF07111F),_panel=Color(0xFF101A30),_line=Color(0xFF27355D),_purple=Color(0xFF8B5CFF),_muted=Color(0xFFA7B0C7),_red=Color(0xFFFF4D63),_gold=Color(0xFFFFC857);
class OwnerVehiclesPage extends StatefulWidget{const OwnerVehiclesPage({super.key});@override State<OwnerVehiclesPage> createState()=>_OwnerVehiclesPageState();}
class _OwnerVehiclesPageState extends State<OwnerVehiclesPage>{
 List<Map<String,dynamic>> vehicles=[];bool loading=true,premium=false;int limit=1;String? error;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final owner=OnboardingDraft.userId.trim();if(owner.isEmpty){setState((){loading=false;error='Araç sahibi oturumu bulunamadı.';});return;}try{final r=await http.get(Uri.parse('${OnboardingBackend.baseUrl}/api/owner/vehicles'),headers:{'x-owner-id':owner}).timeout(const Duration(seconds:15));final d=jsonDecode(r.body);if(r.statusCode<200||r.statusCode>=300||d is! Map)throw Exception();final list=d['vehicles'];if(!mounted)return;setState((){vehicles=list is List?list.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():[];premium=d['premium']==true;limit=int.tryParse('${d['limit']}')??1;loading=false;error=null;});}catch(_){if(mounted)setState((){loading=false;error='Araçlar yüklenemedi.';});}}
 Future<void> _addVehicle()async{if(vehicles.length>=limit){_showLimit();return;}final result=await showDialog<_VehicleFormResult>(context:context,barrierColor:Colors.black.withValues(alpha:.72),builder:(_)=>const _VehicleFormDialog());if(result==null)return;try{final r=await http.post(Uri.parse('${OnboardingBackend.baseUrl}/api/owner/vehicles'),headers:{'Content-Type':'application/json','x-owner-id':OnboardingDraft.userId.trim()},body:jsonEncode({'plate':result.plate,'make':result.make,'model':result.model})).timeout(const Duration(seconds:15));final d=r.body.isEmpty?{}:jsonDecode(r.body);if(r.statusCode==403&&d is Map&&d['error']=='VEHICLE_LIMIT_REACHED'){if(mounted)_showLimit();return;}if(r.statusCode==409&&d is Map&&d['error']=='PLATE_EXISTS')throw Exception('Bu plaka zaten kayıtlı.');if(r.statusCode<200||r.statusCode>=300)throw Exception('Araç eklenemedi.');await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Araç eklendi.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}}
 void _showLimit(){showDialog<void>(context:context,builder:(c)=>AlertDialog(backgroundColor:_panel,title:Text(premium?'Premium araç limiti doldu':'Premium ile 3 araç ekle',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),content:Text(premium?'Premium hesabında en fazla 3 araç ekleyebilirsin.':'Standart hesapta 1 araç kullanabilirsin. Premium ile toplam 3 araç ekleyebilirsin.',style:const TextStyle(color:_muted)),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Tamam'))]));}
 void _openVehicle(Map<String,dynamic> v){final plate='${v['plate']??''}',make='${v['make']??''}',model='${v['model']??''}',id='${v['id']??''}';QrDraft.vehicleId=id;OnboardingDraft.vehicleId=id;QrDraft.plate=plate;QrDraft.make=make;QrDraft.model=model;Navigator.push(context,MaterialPageRoute(builder:(_)=>VehicleCenterPage(plate:plate,title:model.trim().isEmpty?make:'$make $model')));}
 @override Widget build(BuildContext context){final top=MediaQuery.paddingOf(context).top;return Scaffold(backgroundColor:_bg,body:RefreshIndicator(onRefresh:_load,color:_purple,child:ListView(padding:EdgeInsets.fromLTRB(14,top+14,14,26),children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Araçlarım',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Kayıtlı araçlarını yönet.',style:TextStyle(color:_muted,fontSize:13))])),FilledButton.icon(onPressed:loading?null:_addVehicle,style:FilledButton.styleFrom(backgroundColor:_purple),icon:const Icon(Icons.add_rounded),label:const Text('Yeni Araç'))]),const SizedBox(height:12),Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:10),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(15),border:Border.all(color:premium?_gold:_line)),child:Row(children:[Icon(premium?Icons.workspace_premium_rounded:Icons.directions_car_outlined,color:premium?_gold:_muted,size:20),const SizedBox(width:9),Expanded(child:Text(premium?'Premium • ${vehicles.length}/3 araç':'Standart • ${vehicles.length}/1 araç',style:TextStyle(color:premium?_gold:_muted,fontWeight:FontWeight.w800))),Text('${vehicles.length}/$limit',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900))])),const SizedBox(height:14),if(loading)const Padding(padding:EdgeInsets.all(36),child:Center(child:CircularProgressIndicator(color:_purple)))else if(error!=null)Center(child:Column(children:[Text(error!,style:const TextStyle(color:_muted)),TextButton(onPressed:_load,child:const Text('Tekrar dene'))]))else if(vehicles.isEmpty)const _EmptyVehicles()else ...vehicles.map((v)=>Padding(padding:const EdgeInsets.only(bottom:12),child:_VehicleCard(vehicle:v,onTap:()=>_openVehicle(v)))),if(!loading&&vehicles.length<limit)Padding(padding:const EdgeInsets.only(bottom:14),child:OutlinedButton.icon(onPressed:_addVehicle,style:OutlinedButton.styleFrom(foregroundColor:_purple,side:const BorderSide(color:_purple),padding:const EdgeInsets.symmetric(vertical:14)),icon:const Icon(Icons.add_circle_outline_rounded),label:Text(premium?'Yeni araç ekle • ${limit-vehicles.length} hakkın kaldı':'Yeni araç ekle'))),const ActiveDriverCard(),const SizedBox(height:14),Container(width:double.infinity,padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Row(children:[Icon(Icons.notifications_active_outlined,color:_purple),SizedBox(width:11),Expanded(child:Text('Her araç için bakım, muayene, sigorta, kasko ve park bilgilerini ayrı takip edebilirsin.',style:TextStyle(color:_muted,fontSize:12.5)))]))])));}
}
class _VehicleCard extends StatelessWidget{const _VehicleCard({required this.vehicle,required this.onTap});final Map<String,dynamic> vehicle;final VoidCallback onTap;@override Widget build(BuildContext context){final make='${vehicle['make']??''}',model='${vehicle['model']??''}',plate='${vehicle['plate']??''}',title=model.trim().isEmpty?make:'$make $model',logo=VehicleApi.brandLogoUrl(make);return InkWell(onTap:onTap,borderRadius:BorderRadius.circular(22),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(22),border:Border.all(color:_line)),child:Row(children:[Container(width:68,height:60,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:_bg,borderRadius:BorderRadius.circular(16)),child:logo==null?const Icon(Icons.directions_car_filled_rounded,color:_purple,size:32):Image.network(logo,errorBuilder:(_,__,___)=>const Icon(Icons.directions_car_filled_rounded,color:_purple))),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(plate,style:const TextStyle(color:_muted,fontSize:14,fontWeight:FontWeight.w800))])),const Icon(Icons.chevron_right_rounded,color:_muted)])));}}
class _EmptyVehicles extends StatelessWidget{const _EmptyVehicles();@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Column(children:[Icon(Icons.directions_car_outlined,color:_muted,size:40),SizedBox(height:8),Text('Kayıtlı araç bulunamadı',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800))]));}
class _VehicleFormResult{const _VehicleFormResult(this.plate,this.make,this.model);final String plate,make,model;}
class _VehicleFormDialog extends StatefulWidget{const _VehicleFormDialog();@override State<_VehicleFormDialog> createState()=>_VehicleFormDialogState();}
class _VehicleFormDialogState extends State<_VehicleFormDialog>{final plate=TextEditingController();String? make,model;List<String> makes=const[],models=const[];bool loading=true,loadingModels=false;@override void initState(){super.initState();_loadMakes();}Future<void> _loadMakes()async{final m=await VehicleApi.getMakes();if(mounted)setState((){makes=m;loading=false;});}Future<void> _changeMake(String? v)async{if(v==null)return;setState((){make=v;model=null;loadingModels=true;});final m=await VehicleApi.getModels(v);if(mounted)setState((){models=m;loadingModels=false;});}@override void dispose(){plate.dispose();super.dispose();}@override Widget build(BuildContext context)=>Dialog(backgroundColor:_panel,insetPadding:const EdgeInsets.symmetric(horizontal:20),child:Padding(padding:const EdgeInsets.all(18),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Yeni Araç',style:TextStyle(color:Colors.white,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('Aracını ekle, daha sonra QR etiketini bağlayabilirsin.',style:TextStyle(color:_muted,fontSize:12)),const SizedBox(height:16),TextField(controller:plate,textCapitalization:TextCapitalization.characters,style:const TextStyle(color:Colors.white),decoration=InputDecoration(labelText:'Plaka',prefixIcon:const Icon(Icons.pin_outlined,color:_purple),filled:true,fillColor:_bg)),const SizedBox(height:11),if(loading)const Center(child:CircularProgressIndicator(color:_purple))else DropdownButtonFormField<String>(initialValue:make,isExpanded:true,dropdownColor:_panel,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Marka',prefixIcon:Icon(Icons.directions_car_outlined,color:_purple),filled:true,fillColor:_bg),items:makes.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:_changeMake),const SizedBox(height:11),if(loadingModels)const Center(child:CircularProgressIndicator(color:_purple))else DropdownButtonFormField<String>(initialValue:model,isExpanded:true,dropdownColor:_panel,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Model',prefixIcon:Icon(Icons.car_rental_outlined,color:_purple),filled:true,fillColor:_bg),items:models.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>model=v)),const SizedBox(height:17),FilledButton(style:FilledButton.styleFrom(backgroundColor:_purple,padding:const EdgeInsets.symmetric(vertical:14)),onPressed:(){final p=plate.text.trim().toUpperCase();if(p.isEmpty||make==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Plaka ve marka zorunlu.')));return;}Navigator.pop(context,_VehicleFormResult(p,make!,model??''));},child:const Text('Aracı Ekle',style:TextStyle(fontWeight:FontWeight.w900)))])));}
