import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'qr_backend.dart';
import 'onboarding_backend.dart';
import 'cepqar_theme.dart';
import 'street_parking_card.dart';

class ParkingLocationCard extends StatefulWidget{const ParkingLocationCard({super.key,required this.vehicleId});final String vehicleId;@override State<ParkingLocationCard> createState()=>_ParkingLocationCardState();}
class _ParkingLocationCardState extends State<ParkingLocationCard>{
  int? selected;
  @override Widget build(BuildContext context){if(selected==0)return _back(StreetParkingCard(vehicleId:widget.vehicleId));if(selected==1)return _back(_GarageParkingCard(vehicleId:widget.vehicleId));return Container(padding:const EdgeInsets.fromLTRB(18,10,18,22),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(24)),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:44,height:4,decoration:BoxDecoration(color:CepqarTheme.line,borderRadius:BorderRadius.circular(9)))),const SizedBox(height:16),Text('Park',style:TextStyle(color:CepqarTheme.text,fontSize:23,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('Aracını nerede bıraktın?',style:TextStyle(color:CepqarTheme.muted,fontSize:14)),const SizedBox(height:16),_choice(Icons.location_on_rounded,'Sokakta Park Ettim','GPS konumunu kaydet • Park süresini gör',true,()=>setState(()=>selected=0)),const SizedBox(height:10),_choice(Icons.local_parking_rounded,'Park Yerim','AVM • Katlı otopark • Kat / alan / park no',false,()=>setState(()=>selected=1))]));}
  Widget _back(Widget child)=>Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[TextButton.icon(onPressed:()=>setState(()=>selected=null),icon:const Icon(Icons.arrow_back_rounded),label:const Text('Park seçenekleri')),child]);
  Widget _choice(IconData icon,String title,String sub,bool premium,VoidCallback tap)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(18),child:Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:CepqarTheme.bg,borderRadius:BorderRadius.circular(18),border:Border.all(color:CepqarTheme.line)),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:CepqarTheme.purple.withValues(alpha:.13),borderRadius:BorderRadius.circular(15)),child:Icon(icon,color:CepqarTheme.purple,size:28)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Flexible(child:Text(title,style:TextStyle(color:CepqarTheme.text,fontSize:15.5,fontWeight:FontWeight.w900))),if(premium)...[const SizedBox(width:7),Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:3),decoration:BoxDecoration(color:const Color(0xFFFFC64D).withValues(alpha:.15),borderRadius:BorderRadius.circular(8)),child:const Text('PREMIUM',style:TextStyle(color:Color(0xFFFFB800),fontSize:8.5,fontWeight:FontWeight.w900)))]]),const SizedBox(height:4),Text(sub,style:TextStyle(color:CepqarTheme.muted,fontSize:11.5,height:1.25))])),Icon(Icons.chevron_right_rounded,color:CepqarTheme.muted)])));
}

class _GarageParkingCard extends StatefulWidget{const _GarageParkingCard({required this.vehicleId});final String vehicleId;@override State<_GarageParkingCard> createState()=>_GarageParkingCardState();}
class _GarageParkingCardState extends State<_GarageParkingCard>{Map<String,dynamic>? parking;bool loading=true;String get owner=>OnboardingDraft.userId.trim();Map<String,String> get headers=>{'Content-Type':'application/json','x-owner-id':owner};@override void initState(){super.initState();load();}
Future<void> load()async{try{final r=await http.get(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/parking'),headers:headers);final x=jsonDecode(r.body);if(mounted)setState((){parking=x['parking'] is Map?Map<String,dynamic>.from(x['parking']):null;loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
Future<void> edit()async{final result=await showModalBottomSheet<Map<String,String>>(context:context,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(_)=>_ParkingSheet(initial:parking));if(result==null)return;final r=await http.put(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/parking'),headers:headers,body:jsonEncode(result));if(r.statusCode==200)await load();}
Future<void> clear()async{final r=await http.delete(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/parking'),headers:headers);if(r.statusCode==200&&mounted)setState(()=>parking=null);}
@override Widget build(BuildContext context){if(loading)return const SizedBox(height:120,child:Center(child:CircularProgressIndicator()));final has=parking!=null;return Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:CepqarTheme.line)),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.local_parking_rounded,color:CepqarTheme.purple,size:30),const SizedBox(width:10),Expanded(child:Text('Park Yerim',style:TextStyle(color:CepqarTheme.text,fontSize:18,fontWeight:FontWeight.w900)))]),const SizedBox(height:12),if(!has)...[Text('AVM ve katlı otoparklarda kat, alan ve park numaranı kaydet.',style:TextStyle(color:CepqarTheme.muted,height:1.4)),const SizedBox(height:14),SizedBox(width:double.infinity,height:50,child:FilledButton.icon(onPressed:edit,style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple,foregroundColor:Colors.white),icon:const Icon(Icons.add),label:const Text('Park Yerini Kaydet',style:TextStyle(fontWeight:FontWeight.w900))))]else...[Text('${parking!['area']??''}',style:TextStyle(color:CepqarTheme.text,fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text([if('${parking!['floor']??''}'.isNotEmpty)'Kat ${parking!['floor']}',if('${parking!['spot']??''}'.isNotEmpty)'No: ${parking!['spot']}'].join(' • '),style:TextStyle(color:CepqarTheme.muted,fontWeight:FontWeight.w700)),if('${parking!['note']??''}'.trim().isNotEmpty)...[const SizedBox(height:8),Text('${parking!['note']}',style:TextStyle(color:CepqarTheme.muted))],const SizedBox(height:13),Row(children:[Expanded(child:OutlinedButton(onPressed:edit,child:const Text('Düzenle'))),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:clear,style:OutlinedButton.styleFrom(foregroundColor:const Color(0xFFFF4D63)),child:const Text('Parktan çıktım')))])]]));}}

class _ParkingSheet extends StatefulWidget{const _ParkingSheet({this.initial});final Map<String,dynamic>? initial;@override State<_ParkingSheet> createState()=>_ParkingSheetState();}
class _ParkingSheetState extends State<_ParkingSheet>{late final area=TextEditingController(text:'${widget.initial?['area']??''}'),floor=TextEditingController(text:'${widget.initial?['floor']??''}'),spot=TextEditingController(text:'${widget.initial?['spot']??''}'),note=TextEditingController(text:'${widget.initial?['note']??''}');@override void dispose(){area.dispose();floor.dispose();spot.dispose();note.dispose();super.dispose();}@override Widget build(BuildContext context)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.of(context).viewInsets.bottom),child:Container(padding:const EdgeInsets.fromLTRB(20,14,20,24),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:const BorderRadius.vertical(top:Radius.circular(25))),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Park Yerini Kaydet',style:TextStyle(color:CepqarTheme.text,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text('AVM / katlı otopark bilgilerini gir.',style:TextStyle(color:CepqarTheme.muted)),const SizedBox(height:16),field(area,'Alan / Blok','A3'),const SizedBox(height:10),field(floor,'Kat','-2'),const SizedBox(height:10),field(spot,'Park No','148'),const SizedBox(height:10),field(note,'Not','Asansörün karşısı'),const SizedBox(height:15),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:(){if(area.text.trim().isEmpty&&floor.text.trim().isEmpty&&spot.text.trim().isEmpty)return;Navigator.pop(context,{'area':area.text.trim(),'floor':floor.text.trim(),'spot':spot.text.trim(),'note':note.text.trim()});},style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple,foregroundColor:Colors.white),child:const Text('Kaydet',style:TextStyle(fontWeight:FontWeight.w900))))]))));Widget field(TextEditingController c,String label,String hint)=>TextField(controller:c,style:TextStyle(color:CepqarTheme.text),decoration:InputDecoration(labelText:label,hintText:hint,filled:true,fillColor:CepqarTheme.bg,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide(color:CepqarTheme.line))));}
