import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geolocator/geolocator.dart';
import 'package:latlong2/latlong.dart';
import 'cepqar_theme.dart';
import 'owner_auth.dart';
import 'onboarding_backend.dart';
import 'qr_backend.dart';
class TowingFlowPage extends StatefulWidget{const TowingFlowPage({super.key});@override State<TowingFlowPage> createState()=>_S();}
class _S extends State<TowingFlowPage>{int step=0;bool busy=false;String issue='Arıza',truck='platform';double? a,b,x,y;Map<String,dynamic>? quote;final dest=TextEditingController();String get api=>OnboardingBackend.baseUrl;@override void dispose(){dest.dispose();super.dispose();}
void msg(String s){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
Future<void> locate()async{setState(()=>busy=true);try{var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever)throw Exception();final z=await Geolocator.getCurrentPosition();setState((){a=z.latitude;b=z.longitude;});}catch(_){msg('Konum alınamadı.');}finally{if(mounted)setState(()=>busy=false);}}
double get km=>(a==null||x==null)?0:Geolocator.distanceBetween(a!,b!,x!,y!)/1000;
Future<void> price()async{if(a==null||x==null){msg('Başlangıç ve hedef seç.');return;}setState(()=>busy=true);try{final r=await OwnerHttp.post(Uri.parse('$api/api/owner/towing/quote'),body:jsonEncode({'distanceKm':km,'vehicleType':'car','truckType':truck}));final d=jsonDecode(r.body);if(r.statusCode==200)setState(()=>quote=Map<String,dynamic>.from(d['quote']));else msg('Fiyat hesaplanamadı.');}catch(_){msg('Fiyat hesaplanamadı.');}finally{if(mounted)setState(()=>busy=false);}}
Future<void> call()async{if(quote==null)return;setState(()=>busy=true);try{final r=await OwnerHttp.post(Uri.parse('$api/api/owner/towing/requests'),body:jsonEncode({'vehicleId':QrDraft.vehicleId,'vehicleType':'car','truckType':truck,'issueType':issue,'pickupLat':a,'pickupLng':b,'pickupAddress':'Mevcut konum','destinationLat':x,'destinationLng':y,'destinationAddress':dest.text.trim().isEmpty?'Haritada seçilen hedef':dest.text.trim(),'distanceKm':km}));final d=jsonDecode(r.body);if(r.statusCode>=200&&r.statusCode<300){final id='${d['request']['id']}';if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>TowingTrackingPage(id:id)));}else msg(d['error']=='ACTIVE_TOWING_REQUEST_EXISTS'?'Aktif çekici çağrın zaten var.':'Çağrı oluşturulamadı.');}catch(_){msg('Çağrı oluşturulamadı.');}finally{if(mounted)setState(()=>busy=false);}}
Widget card(Widget z)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:CepqarTheme.line)),child:z);
@override Widget build(BuildContext c){final titles=['Araç ve sorun','Konum ve hedef','Çekici tipi','Fiyat ve çağrı'];return Scaffold(backgroundColor:CepqarTheme.bg,appBar:AppBar(backgroundColor:CepqarTheme.bg,foregroundColor:CepqarTheme.text,title:const Text('Çekici')),body:busy?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[Text(titles[step],style:TextStyle(color:CepqarTheme.text,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:14),
if(step==0)...[card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(QrDraft.plate.isEmpty?'Seçili araç':QrDraft.plate,style:TextStyle(color:CepqarTheme.text,fontSize:18,fontWeight:FontWeight.w900)),Text('${QrDraft.make} ${QrDraft.model}',style:TextStyle(color:CepqarTheme.muted))])),...['Arıza','Kaza','Araç çalışmıyor','Diğer'].map((v)=>RadioListTile<String>(value:v,groupValue:issue,onChanged:(q)=>setState(()=>issue=q!),title:Text(v,style:TextStyle(color:CepqarTheme.text))))],
if(step==1)card(Column(children:[ListTile(leading:Icon(Icons.my_location,color:CepqarTheme.purple),title:Text(a==null?'Bulunduğum konumu al':'Başlangıç konumu alındı',style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900)),onTap:locate),TextField(controller:dest,style:TextStyle(color:CepqarTheme.text),decoration:const InputDecoration(labelText:'Hedef adres')),const SizedBox(height:8),SizedBox(height:230,child:FlutterMap(options:MapOptions(initialCenter:LatLng(a??41.02,b??28.9),initialZoom:12,onTap:(_,p)=>setState((){x=p.latitude;y=p.longitude;})),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.cepqar.app'),MarkerLayer(markers:[if(a!=null)Marker(point:LatLng(a!,b!),width:40,height:40,child:Icon(Icons.my_location,color:CepqarTheme.purple,size:30)),if(x!=null)Marker(point:LatLng(x!,y!),width:45,height:45,child:const Icon(Icons.location_on,color:Colors.red,size:38))])])),Text(x==null?'Haritada hedefe dokun':'Yaklaşık ${km.toStringAsFixed(1)} km',style:TextStyle(color:CepqarTheme.muted))])),
if(step==2)...[('platform','Platform / Kayar Kasa'),('akrep','Akrep')].map((v)=>card(RadioListTile<String>(value:v.$1,groupValue:truck,onChanged:(q)=>setState(()=>truck=q!),title:Text(v.$2,style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900)),secondary:Icon(Icons.fire_truck_rounded,color:CepqarTheme.purple)))),
if(step==3)card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(quote==null)SizedBox(width:double.infinity,child:FilledButton(onPressed:price,child:const Text('Fiyatı Hesapla')))else...[Text('${quote!['total']} ${quote!['currency']}',style:TextStyle(color:CepqarTheme.text,fontSize:30,fontWeight:FontWeight.w900)),Text('${quote!['truckTypeName']} • ${quote!['distanceKm']} km',style:TextStyle(color:CepqarTheme.muted)),const SizedBox(height:16),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:call,style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple),child:const Text('Çekici Ara',style:TextStyle(fontWeight:FontWeight.w900))))]])),
const SizedBox(height:16),if(step<3)SizedBox(height:52,child:FilledButton(onPressed:(){if(step==1&&(a==null||x==null)){msg('Başlangıç ve hedef seç.');return;}setState(()=>step++);},style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple),child:const Text('Devam'))),if(step>0)TextButton(onPressed:()=>setState(()=>step--),child:const Text('Geri'))]));}}
class TowingTrackingPage extends StatefulWidget{const TowingTrackingPage({super.key,required this.id});final String id;@override State<TowingTrackingPage> createState()=>_T();}
class _T extends State<TowingTrackingPage>{Map<String,dynamic>? d;Timer? t;@override void initState(){super.initState();load();t=Timer.periodic(const Duration(seconds:5),(_)=>load());}@override void dispose(){t?.cancel();super.dispose();}Future<void> load()async{try{final r=await OwnerHttp.get(Uri.parse('${OnboardingBackend.baseUrl}/api/owner/towing/requests/${widget.id}/tracking'));if(r.statusCode==200&&mounted)setState(()=>d=Map<String,dynamic>.from(jsonDecode(r.body)['tracking']));}catch(_){}}String label(String s)=>{'searching':'Yakındaki çekiciler aranıyor','accepted':'Çekici bulundu','arriving':'Çekici size geliyor','arrived':'Çekici geldi','vehicle_loaded':'Aracınız yüklendi','in_transit':'Aracınız yolda','delivered':'Teslim edildi','cancelled':'İptal edildi'}[s]??s;
@override Widget build(BuildContext c){final lat=double.tryParse('${d?['driver_lat']??''}'),lng=double.tryParse('${d?['driver_lng']??''}');return Scaffold(backgroundColor:CepqarTheme.bg,appBar:AppBar(backgroundColor:CepqarTheme.bg,foregroundColor:CepqarTheme.text,title:const Text('Çekici Takibi')),body:d==null?const Center(child:CircularProgressIndicator()):ListView(children:[SizedBox(height:330,child:lat==null?Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.radar_rounded,color:CepqarTheme.purple,size:65),const SizedBox(height:12),Text(label('${d!['status']}'),style:TextStyle(color:CepqarTheme.text,fontSize:20,fontWeight:FontWeight.w900))])):FlutterMap(options:MapOptions(initialCenter:LatLng(lat,lng!),initialZoom:14),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.cepqar.app'),MarkerLayer(markers:[Marker(point:LatLng(lat,lng),width:55,height:55,child:Icon(Icons.fire_truck_rounded,color:CepqarTheme.purple,size:42))])])),Padding(padding:const EdgeInsets.all(16),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:CepqarTheme.line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label('${d!['status']}'),style:TextStyle(color:CepqarTheme.text,fontSize:20,fontWeight:FontWeight.w900)),if(d!['pickup_eta_minutes']!=null)Text('${d!['pickup_eta_minutes']} dk • ${d!['pickup_distance_km']??'-'} km',style:TextStyle(color:CepqarTheme.purple,fontWeight:FontWeight.w900)),if(d!['provider_name']!=null)...[const SizedBox(height:12),Text('${d!['provider_name']}',style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900))],if(d!['driver_name']!=null)Text('Sürücü: ${d!['driver_name']}',style:TextStyle(color:CepqarTheme.muted)),if(d!['towing_plate']!=null)Text('Çekici: ${d!['towing_plate']}',style:TextStyle(color:CepqarTheme.muted))])))]));}}