import 'package:flutter/material.dart';
import 'cepqar_theme.dart';

class TowingFlowPage extends StatefulWidget{const TowingFlowPage({super.key});@override State<TowingFlowPage> createState()=>_S();}
class _S extends State<TowingFlowPage>{
 int step=0;String issue='Arıza',truck='Platform / Kayar Kasa';
 final dest=TextEditingController();
 @override void dispose(){dest.dispose();super.dispose();}
 Widget card(Widget x)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:CepqarTheme.panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:CepqarTheme.line)),child:x);
 @override Widget build(BuildContext c){final titles=['Araç ve sorun','Konum ve hedef','Çekici tipi','Fiyat ve çağrı'];return Scaffold(backgroundColor:CepqarTheme.bg,appBar:AppBar(backgroundColor:CepqarTheme.bg,foregroundColor:CepqarTheme.text,title:const Text('Çekici')),body:ListView(padding:const EdgeInsets.all(16),children:[
 Text(titles[step],style:TextStyle(color:CepqarTheme.text,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:14),
 if(step==0)...[card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Seçili aracın',style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900)),Text('CepQontag araç kaydı kullanılacak',style:TextStyle(color:CepqarTheme.muted))])),...['Arıza','Kaza','Araç çalışmıyor','Diğer'].map((x)=>RadioListTile<String>(value:x,groupValue:issue,onChanged:(v)=>setState(()=>issue=v!),title:Text(x,style:TextStyle(color:CepqarTheme.text))))],
 if(step==1)...[card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(Icons.my_location,color:CepqarTheme.purple),const SizedBox(width:8),Text('Bulunduğum konum',style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900))]),const SizedBox(height:12),TextField(controller:dest,style:TextStyle(color:CepqarTheme.text),decoration:const InputDecoration(labelText:'Nereye götürülsün?')),const SizedBox(height:12),Text('Harita üzerinden başlangıç ve hedef seçimi bu adımda kullanılacak.',style:TextStyle(color:CepqarTheme.muted))]))],
 if(step==2)...['Platform / Kayar Kasa','Akrep'].map((x)=>card(RadioListTile<String>(contentPadding:EdgeInsets.zero,value:x,groupValue:truck,onChanged:(v)=>setState(()=>truck=v!),secondary:Icon(x.startsWith('Platform')?Icons.fire_truck_rounded:Icons.car_repair_rounded,color:CepqarTheme.purple),title:Text(x,style:TextStyle(color:CepqarTheme.text,fontWeight:FontWeight.w900))))),
 if(step==3)card(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Tahmini fiyat',style:TextStyle(color:CepqarTheme.muted)),const SizedBox(height:4),Text('Rota ve tarifeye göre hesaplanacak',style:TextStyle(color:CepqarTheme.text,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('$issue • $truck',style:TextStyle(color:CepqarTheme.muted)),const SizedBox(height:16),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:(){Navigator.push(c,MaterialPageRoute(builder:(_)=>const TowingSearchingPage()));},style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple),child:const Text('Çekici Ara',style:TextStyle(fontWeight:FontWeight.w900))))])),
 const SizedBox(height:16),if(step<3)SizedBox(height:52,child:FilledButton(onPressed:()=>setState(()=>step++),style:FilledButton.styleFrom(backgroundColor:CepqarTheme.purple),child:const Text('Devam'))),if(step>0)TextButton(onPressed:()=>setState(()=>step--),child:const Text('Geri'))
 ]));}
}

class TowingSearchingPage extends StatelessWidget{const TowingSearchingPage({super.key});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:CepqarTheme.bg,appBar:AppBar(backgroundColor:CepqarTheme.bg,foregroundColor:CepqarTheme.text,title:const Text('Çekici Takibi')),body:Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.radar_rounded,color:CepqarTheme.purple,size:74),const SizedBox(height:18),Text('Yakındaki çekiciler aranıyor',textAlign:TextAlign.center,style:TextStyle(color:CepqarTheme.text,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('Bir çekici kabul ettiğinde sürücü, araç bilgisi, tahmini varış süresi ve canlı harita burada görünecek.',textAlign:TextAlign.center,style:TextStyle(color:CepqarTheme.muted))]))));}