import 'dart:math';
import 'dart:async';
// Build marker: duplicate-session guard
import 'dart:convert';import 'package:flutter/material.dart';import 'package:http/http.dart' as http;import 'package:shared_preferences/shared_preferences.dart';import 'package:mobile_scanner/mobile_scanner.dart';import 'package:firebase_core/firebase_core.dart';import 'package:firebase_messaging/firebase_messaging.dart';import 'package:flutter_local_notifications/flutter_local_notifications.dart';
const api='https://heycar-api-185-165-46-213.nip.io',purple=Color(0xFF713BFF),lime=Color(0xFFB6FF2A),bg=Color(0xFF07111F),panel=Color(0xFF101A30),muted=Color(0xFFA7B0C7);
Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();try{await Firebase.initializeApp();}catch(e){debugPrint('Vale Firebase init failed: $e');}runApp(const ValetApp());}
class ValetApp extends StatelessWidget{const ValetApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:purple,brightness:Brightness.dark)),home:const Gate());}
class Gate extends StatefulWidget{const Gate({super.key});@override State<Gate> createState()=>_Gate();}
class _Gate extends State<Gate>{String? token;@override void initState(){super.initState();SharedPreferences.getInstance().then((p){if(mounted)setState(()=>token=p.getString('valet_token'));});}@override Widget build(BuildContext c)=>token==null?Login(onLogin:(t)=>setState(()=>token=t)):Home(token:token!,logout:()async{final t=token;try{if(t!=null&&t.isNotEmpty)await http.post(Uri.parse(api+'/api/valet/logout'),headers:{'authorization':'Bearer $t'}).timeout(const Duration(seconds:8));}catch(_){}await (await SharedPreferences.getInstance()).remove('valet_token');if(mounted)setState(()=>token=null);});}
class Login extends StatefulWidget{const Login({super.key,required this.onLogin});final ValueChanged<String> onLogin;@override State<Login> createState()=>_Login();}
class _Login extends State<Login>{final phone=TextEditingController(),pin=TextEditingController();bool busy=false;Future<void> go()async{setState(()=>busy=true);try{final r=await http.post(Uri.parse(api+'/api/valet/login'),headers:{'content-type':'application/json'},body:jsonEncode({'phone':phone.text.trim(),'pin':pin.text.trim()}));if(r.statusCode==200){final t=jsonDecode(r.body)['token'].toString();await (await SharedPreferences.getInstance()).setString('valet_token',t);widget.onLogin(t);}else if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Telefon numarası veya PIN hatalı.')));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(children:[Container(width:72,height:72,decoration:BoxDecoration(color:purple,borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.local_parking_rounded,size:42,color:Colors.white)),const SizedBox(height:18),const Text('CepQontag Vale',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Personel Girişi',style:TextStyle(color:muted)),const SizedBox(height:28),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Telefon numarası',hintText:'05xx xxx xx xx',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pin,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Vale PIN',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,style:FilledButton.styleFrom(backgroundColor:lime,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),child:Text(busy?'Giriş yapılıyor...':'Giriş Yap',style:const TextStyle(fontWeight:FontWeight.w900))))])))));}
String _uuid(){final r=Random.secure(),b=List<int>.generate(16,(_)=>r.nextInt(256));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;String h(int x)=>x.toRadixString(16).padLeft(2,'0');final s=b.map(h).join();return '${s.substring(0,8)}-${s.substring(8,12)}-${s.substring(12,16)}-${s.substring(16,20)}-${s.substring(20)}';}
class Home extends StatefulWidget{const Home({super.key,required this.token,required this.logout});final String token;final VoidCallback logout;@override State<Home> createState()=>_Home();}
class _Home extends State<Home>{final FlutterLocalNotificationsPlugin _local=FlutterLocalNotificationsPlugin();StreamSubscription<RemoteMessage>? _foregroundPush;List data=[];List areas=[];String business='',staff='';bool loading=true,onShift=false,shiftBusy=false;Timer? timer;Map<String,String> get h=>{'content-type':'application/json','authorization':'Bearer '+widget.token};@override void initState(){super.initState();load();_push();timer=Timer.periodic(const Duration(seconds:5),(_)=>load());}@override void dispose(){timer?.cancel();_foregroundPush?.cancel();super.dispose();}Future<void> _push()async{try{if(Firebase.apps.isEmpty)return;await FirebaseMessaging.instance.requestPermission();await _local.initialize(const InitializationSettings(android:AndroidInitializationSettings('@mipmap/ic_launcher')));const channel=AndroidNotificationChannel('cepqontag_valet','CepQontag Vale',description:'Vale iş ve araç bildirimleri',importance:Importance.high);await _local.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.createNotificationChannel(channel);_foregroundPush?.cancel();_foregroundPush=FirebaseMessaging.onMessage.listen((m){if(!mounted)return;load();final title=m.notification?.title??(m.data['title']??'CepQontag Vale').toString();final body=m.notification?.body??(m.data['body']??'Yeni vale bildirimi').toString();_local.show(DateTime.now().millisecondsSinceEpoch.remainder(2147483647),title,body,const NotificationDetails(android:AndroidNotificationDetails('cepqontag_valet','CepQontag Vale',channelDescription:'Vale iş ve araç bildirimleri',importance:Importance.high,priority:Priority.high)));});final t=await FirebaseMessaging.instance.getToken();if(t==null)return;final p=await SharedPreferences.getInstance();var d=p.getString('valet_device_id');if(d==null){d=DateTime.now().microsecondsSinceEpoch.toString();await p.setString('valet_device_id',d);}await http.post(Uri.parse(api+'/api/valet/push-token'),headers:h,body:jsonEncode({'token':t,'deviceId':d}));FirebaseMessaging.instance.onTokenRefresh.listen((n){http.post(Uri.parse(api+'/api/valet/push-token'),headers:h,body:jsonEncode({'token':n,'deviceId':d}));});}catch(_){}}
Future<List<Map<String,dynamic>>> _offlineOps()async{final p=await SharedPreferences.getInstance();final raw=p.getString('valet_offline_ops');if(raw==null)return [];try{return (jsonDecode(raw) as List).map((e)=>Map<String,dynamic>.from(e)).toList();}catch(_){return [];}}
Future<void> _saveOffline(List<Map<String,dynamic>> ops)async{final p=await SharedPreferences.getInstance();await p.setString('valet_offline_ops',jsonEncode(ops));}
Future<void> _queueStatus(String id,String st)async{final ops=await _offlineOps();ops.add({'id':_uuid(),'type':'status','createdAt':DateTime.now().toUtc().toIso8601String(),'payload':{'sessionId':id,'status':st}});await _saveOffline(ops);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('İnternet yok. İşlem sıraya alındı; bağlantı gelince gönderilecek.')));}
Future<void> _syncOffline()async{final ops=await _offlineOps();if(ops.isEmpty)return;try{final r=await http.post(Uri.parse(api+'/api/valet/offline/sync'),headers:h,body:jsonEncode({'operations':ops}));if(r.statusCode==200){final j=jsonDecode(r.body);final results=(j['results'] as List? ?? []);final done=results.where((x)=>x['ok']==true).map((x)=>x['id'].toString()).toSet();await _saveOffline(ops.where((x)=>!done.contains(x['id'].toString())).toList());}}catch(_){}}
Future<void> load()async{try{await _syncOffline();final r=await http.get(Uri.parse(api+'/api/valet/sessions'),headers:h);if(r.statusCode==401){widget.logout();return;}final j=jsonDecode(r.body);if(mounted)setState((){data=j['sessions']??[];areas=j['areas']??[];business=j['businessName']??'';staff=j['staffName']??'';onShift=j['onShift']==true;loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
Future<void> shift(bool active)async{if(shiftBusy)return;setState(()=>shiftBusy=true);try{final r=await http.post(Uri.parse(api+'/api/valet/shift'),headers:h,body:jsonEncode({'active':active}));if(r.statusCode==409){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Aktif araç görevi bitmeden mesai kapatılamaz.')));}else if(r.statusCode>=200&&r.statusCode<300){if(mounted)setState(()=>onShift=active);await load();}}finally{if(mounted)setState(()=>shiftBusy=false);}}
Future<void> status(String id,String s)async{String? code;if(s=='delivered'){final ctl=TextEditingController();code=await showDialog<String>(context:context,builder:(d)=>AlertDialog(backgroundColor:panel,title:const Text('Güvenli Teslim',style:TextStyle(fontWeight:FontWeight.w900)),content:TextField(controller:ctl,autofocus:true,maxLength:4,keyboardType:TextInputType.number,obscureText:true,decoration:const InputDecoration(labelText:'Araç sahibinin 4 haneli kodu',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,ctl.text.trim()),child:const Text('Teslim Et'))]));if(code==null||code.length!=4)return;}http.Response r;try{r=await http.patch(Uri.parse(api+'/api/valet/sessions/'+id+'/status'),headers:h,body:jsonEncode({'status':s,'deliveryCode':code}));}catch(_){if(s!='delivered')await _queueStatus(id,s);return;}if(r.statusCode>=300&&mounted){String msg='İşlem tamamlanamadı.';try{final e=jsonDecode(r.body)['error'];if(e=='INVALID_DELIVERY_CODE')msg='Teslim kodu hatalı.';if(e=='DELIVERY_CODE_LOCKED')msg='Çok fazla hatalı deneme. Kod kilitlendi.';if(e=='DELIVERY_CODE_EXPIRED')msg='Teslim kodunun süresi dolmuş.';}catch(_){}ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(msg)));}await load();}
 String qrToken(String raw){try{final u=Uri.parse(raw);final t=u.queryParameters['tag'];if(t!=null&&t.trim().isNotEmpty)return t.trim().toUpperCase();}catch(_){}final v=raw.trim().toUpperCase();return RegExp(r'^[A-Z0-9-]{4,80}$').hasMatch(v)?v:'';}
 Future<void> scan()async{final raw=await Navigator.push<String>(context,MaterialPageRoute(builder:(_)=>const ValetQrScanner()));if(raw==null)return;final token=qrToken(raw);if(token.isEmpty){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Geçerli CepQontag QR bulunamadı.')));return;}await add(qrCode:token);}
 Future<void> add({String? qrCode})async{
  Map<String,dynamic>? vehicle;
  if(qrCode!=null){
   final vr=await http.get(Uri.parse(api+'/api/valet/vehicle-by-qr/'+Uri.encodeComponent(qrCode)),headers:h);
   if(vr.statusCode!=200){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Araç bu CepQontag QR ile eşleştirilemedi.')));return;}
   vehicle=Map<String,dynamic>.from(jsonDecode(vr.body)['vehicle']);
  }
  final p=TextEditingController(text:vehicle?['plate']?.toString()??'');final tag=TextEditingController();String? selectedArea=areas.isNotEmpty?areas.first['name']?.toString():null;
  await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:panel,builder:(c)=>StatefulBuilder(builder:(c,setSheet)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,MediaQuery.viewInsetsOf(c).bottom+20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[
   Text(qrCode==null?'Araç Kabul':'QR ile Araç Kabul',textAlign:TextAlign.center,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),
   if(vehicle!=null)Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(vehicle!['plate']?.toString()??'',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),if((vehicle!['owner_name']??'').toString().isNotEmpty)Text('Araç sahibi: '+vehicle!['owner_name'].toString(),style:const TextStyle(color:muted)),if(((vehicle!['brand']??'').toString()+' '+(vehicle!['model']??'').toString()).trim().isNotEmpty)Text(((vehicle!['brand']??'').toString()+' '+(vehicle!['model']??'').toString()).trim(),style:const TextStyle(color:muted))])),
   if(qrCode==null)...[const SizedBox(height:12),TextField(controller:tag,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Etiket kodu',hintText:'CP-QAR-001',border:OutlineInputBorder()))],
   const SizedBox(height:12),
   if(areas.isEmpty)const Text('İşletme panelinden önce bir park alanı eklenmeli.',style:TextStyle(color:Colors.orangeAccent)) else DropdownButtonFormField<String>(initialValue:selectedArea,decoration:const InputDecoration(labelText:'Park alanı',border:OutlineInputBorder()),items:areas.map<DropdownMenuItem<String>>((x)=>DropdownMenuItem(value:x['name'].toString(),child:Text(x['name'].toString()))).toList(),onChanged:(v)=>setSheet(()=>selectedArea=v)),
   const SizedBox(height:16),FilledButton(onPressed:areas.isEmpty?null:()async{var code=qrCode??tag.text.trim().toUpperCase();if(code.isEmpty)return;Map<String,dynamic>? manualVehicle=vehicle;if(manualVehicle==null){final vr=await http.get(Uri.parse(api+'/api/valet/vehicle-by-qr/'+Uri.encodeComponent(code)),headers:h);if(vr.statusCode!=200){if(c.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Etiket kodu bulunamadı.')));return;}manualVehicle=Map<String,dynamic>.from(jsonDecode(vr.body)['vehicle']);p.text=manualVehicle['plate']?.toString()??'';}final r=await http.post(Uri.parse(api+'/api/valet/accept'),headers:h,body:jsonEncode({'plate':p.text.trim(),'qrCode':code,'parkingArea':selectedArea}));if(r.statusCode<300&&c.mounted)Navigator.pop(c);await load();},style:FilledButton.styleFrom(backgroundColor:lime,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),child:const Text('Aracı Valeye Al',style:TextStyle(fontWeight:FontWeight.w900)))
  ]))));
 }
@override Widget build(BuildContext c){
 final all=data.length,parked=data.where((x)=>x['status'].toString()=='parked').length,retrieving=data.where((x)=>x['status'].toString()=='retrieving').length,requested=data.where((x)=>x['status'].toString()=='requested').length;
 Widget chip(String t,int n,bool active)=>Container(padding:const EdgeInsets.symmetric(horizontal:14,vertical:11),decoration:BoxDecoration(color:active?lime:panel,borderRadius:BorderRadius.circular(15)),child:Text('$t  $n',style:TextStyle(color:active?Colors.black:Colors.white,fontWeight:FontWeight.w900,fontSize:14)));
 return Scaffold(
  appBar:AppBar(toolbarHeight:72,backgroundColor:bg,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(business.isEmpty?'CepQontag VALE':business,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text('$staff • ${onShift?'Mesaide':'Mesai dışı'}',style:TextStyle(fontSize:11,color:onShift?lime:muted))]),actions:[TextButton(onPressed:shiftBusy?null:()=>shift(!onShift),child:Text(onShift?'Mesaiyi Bitir':'Mesaiye Başla')),IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:widget.logout,icon:const Icon(Icons.logout))]),
  floatingActionButton:Row(mainAxisSize:MainAxisSize.min,children:[FloatingActionButton.extended(heroTag:'manual',backgroundColor:panel,foregroundColor:Colors.white,onPressed:()=>add(),icon:const Icon(Icons.edit),label:const Text('Manuel')),const SizedBox(width:8),FloatingActionButton.extended(heroTag:'scan',backgroundColor:lime,foregroundColor:Colors.black,onPressed:scan,icon:const Icon(Icons.qr_code_scanner),label:const Text('QR Okut',style:TextStyle(fontWeight:FontWeight.w900)))]),
  body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:CustomScrollView(slivers:[
   SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(14,10,14,8),child:Column(children:[
    SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[chip('Tümü',all,true),const SizedBox(width:8),chip('Parkta',parked,false),const SizedBox(width:8),chip('Getiriliyor',retrieving,false),if(requested>0)...[const SizedBox(width:8),chip('İstek',requested,false)]])),
    const SizedBox(height:10),
    TextField(decoration:InputDecoration(hintText:'Plaka, marka veya park yeri ara...',prefixIcon:const Icon(Icons.search),filled:true,fillColor:panel,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none),isDense:true))
   ]))),
   if(data.isEmpty)const SliverFillRemaining(child:Center(child:Text('Aktif vale aracı yok',style:TextStyle(color:muted)))) else SliverPadding(padding:const EdgeInsets.fromLTRB(14,4,14,100),sliver:SliverList.builder(itemCount:data.length,itemBuilder:(_,i){
    final x=data[i],st=x['status'].toString();final requested=st=='requested';final label={'accepted':'Teslim Alındı','parked':'Parkta','requested':'Araç İsteniyor','retrieving':'Getiriliyor','ready':'Hazır'}[st]??st;final next={'accepted':'parked','requested':'retrieving','retrieving':'ready','ready':'delivered'}[st],btn={'accepted':'Park Edildi','requested':'Aracı Getir','retrieving':'Hazır','ready':'Teslim Et'}[st];
    final model=((x['brand']??x['make']??'').toString()+' '+(x['model']??'').toString()).trim(),area=(x['parking_area']??'-').toString(),slot=(x['parking_slot']??'-').toString();
    return Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:requested?const Color(0xFF35131A):panel,borderRadius:BorderRadius.circular(18),border:requested?Border.all(color:Colors.redAccent.withValues(alpha:.65)):null),child:Row(crossAxisAlignment:CrossAxisAlignment.center,children:[
     Container(width:58,height:58,decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(14)),child:Icon(Icons.directions_car_filled,size:34,color:requested?Colors.redAccent:purple)),
     const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x['plate'].toString(),style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),if(model.isNotEmpty)Padding(padding:const EdgeInsets.only(top:3),child:Text(model,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:muted,fontSize:13))),Padding(padding:const EdgeInsets.only(top:5),child:Text('Park: $area  •  $slot',style:const TextStyle(color:muted,fontSize:12)))])),
     const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:7),decoration:BoxDecoration(color:requested?Colors.redAccent:st=='parked'?const Color(0xFF087A50):st=='accepted'?Colors.orange:st=='retrieving'?const Color(0xFF2767D8):purple,borderRadius:BorderRadius.circular(10)),child:Text(label,style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900))),if(next!=null)...[const SizedBox(height:7),SizedBox(height:34,child:FilledButton(onPressed:()=>status(x['id'].toString(),next),style:FilledButton.styleFrom(backgroundColor:requested?Colors.redAccent:purple,padding:const EdgeInsets.symmetric(horizontal:12)),child:Text(btn!,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900))))]])
    ]));
   }))
  ]))
 );
}
}
class ValetQrScanner extends StatefulWidget{const ValetQrScanner({super.key});@override State<ValetQrScanner> createState()=>_ValetQrScanner();}
class _ValetQrScanner extends State<ValetQrScanner>{bool done=false;@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,title:const Text('CepQontag QR Okut',style:TextStyle(fontWeight:FontWeight.w900))),body:Stack(children:[MobileScanner(onDetect:(capture){if(done)return;for(final b in capture.barcodes){final raw=b.rawValue;if(raw!=null&&raw.trim().isNotEmpty){done=true;Navigator.pop(context,raw);break;}}}),Center(child:Container(width:260,height:260,decoration:BoxDecoration(border:Border.all(color:lime,width:3),borderRadius:BorderRadius.circular(24)))),const Positioned(left:24,right:24,bottom:55,child:Text('Araç camındaki CepQontag etiketini çerçevenin içine getir.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,fontSize:15))) ]));}
