import 'dart:convert';import 'package:flutter/material.dart';import 'package:http/http.dart' as http;import 'package:shared_preferences/shared_preferences.dart';
const api='https://heycar-api-185-165-46-213.nip.io',purple=Color(0xFF713BFF),lime=Color(0xFFB6FF2A),bg=Color(0xFF07111F),panel=Color(0xFF101A30),muted=Color(0xFFA7B0C7);
Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();runApp(const ValetApp());}
class ValetApp extends StatelessWidget{const ValetApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:purple,brightness:Brightness.dark)),home:const Gate());}
class Gate extends StatefulWidget{const Gate({super.key});@override State<Gate> createState()=>_Gate();}
class _Gate extends State<Gate>{String? token;@override void initState(){super.initState();SharedPreferences.getInstance().then((p){if(mounted)setState(()=>token=p.getString('valet_token'));});}@override Widget build(BuildContext c)=>token==null?Login(onLogin:(t)=>setState(()=>token=t)):Home(token:token!,logout:()async{await (await SharedPreferences.getInstance()).remove('valet_token');setState(()=>token=null);});}
class Login extends StatefulWidget{const Login({super.key,required this.onLogin});final ValueChanged<String> onLogin;@override State<Login> createState()=>_Login();}
class _Login extends State<Login>{final business=TextEditingController(),pin=TextEditingController();bool busy=false;Future<void> go()async{setState(()=>busy=true);try{final r=await http.post(Uri.parse(api+'/api/valet/login'),headers:{'content-type':'application/json'},body:jsonEncode({'businessCode':business.text.trim(),'pin':pin.text.trim()}));if(r.statusCode==200){final t=jsonDecode(r.body)['token'].toString();await (await SharedPreferences.getInstance()).setString('valet_token',t);widget.onLogin(t);}else if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('İşletme veya PIN hatalı.')));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(children:[Container(width:72,height:72,decoration:BoxDecoration(color:purple,borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.local_parking_rounded,size:42,color:Colors.white)),const SizedBox(height:18),const Text('CepQontag Vale',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Personel Girişi',style:TextStyle(color:muted)),const SizedBox(height:28),TextField(controller:business,decoration:const InputDecoration(labelText:'İşletme adı veya kodu',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pin,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Vale PIN',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,style:FilledButton.styleFrom(backgroundColor:lime,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),child:Text(busy?'Giriş yapılıyor...':'Giriş Yap',style:const TextStyle(fontWeight:FontWeight.w900))))])))));}
class Home extends StatefulWidget{const Home({super.key,required this.token,required this.logout});final String token;final VoidCallback logout;@override State<Home> createState()=>_Home();}
class _Home extends State<Home>{List data=[];String business='',staff='';bool loading=true;Map<String,String> get h=>{'content-type':'application/json','authorization':'Bearer '+widget.token};@override void initState(){super.initState();load();}
Future<void> load()async{try{final r=await http.get(Uri.parse(api+'/api/valet/sessions'),headers:h);if(r.statusCode==401){widget.logout();return;}final j=jsonDecode(r.body);if(mounted)setState((){data=j['sessions']??[];business=j['businessName']??'';staff=j['staffName']??'';loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
Future<void> status(String id,String s)async{await http.patch(Uri.parse(api+'/api/valet/sessions/'+id+'/status'),headers:h,body:jsonEncode({'status':s}));await load();}
Future<void> add()async{final p=TextEditingController(),a=TextEditingController(),s=TextEditingController(),k=TextEditingController();await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:panel,builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,MediaQuery.viewInsetsOf(c).bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Araç Kabul',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),for(final x in [[p,'Plaka'],[a,'Park alanı'],[s,'Park slotu'],[k,'Anahtar yeri']])Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:x[0] as TextEditingController,decoration:InputDecoration(labelText:x[1] as String,border:const OutlineInputBorder()))),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{if(p.text.trim().isEmpty)return;final r=await http.post(Uri.parse(api+'/api/valet/accept'),headers:h,body:jsonEncode({'plate':p.text,'parkingArea':a.text,'parkingSlot':s.text,'keyLocation':k.text}));if(r.statusCode<300&&c.mounted)Navigator.pop(c);await load();},child:const Text('Aracı Valeye Al')))]));}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:bg,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(business.isEmpty?'CepQontag Vale':business,style:const TextStyle(fontWeight:FontWeight.w900)),Text(staff,style:const TextStyle(fontSize:11,color:muted))]),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:widget.logout,icon:const Icon(Icons.logout))]),floatingActionButton:FloatingActionButton.extended(backgroundColor:lime,foregroundColor:Colors.black,onPressed:add,icon:const Icon(Icons.add),label:const Text('Araç Al',style:TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):data.isEmpty?const Center(child:Text('Aktif vale aracı yok',style:TextStyle(color:muted))):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(14,12,14,100),itemCount:data.length,itemBuilder:(_,i){final x=data[i],st=x['status'].toString();final label={'parked':'Parkta','requested':'ARAÇ İSTENİYOR','retrieving':'Getiriliyor','ready':'Hazır'}[st]??st;final next={'requested':'retrieving','retrieving':'ready','ready':'delivered'}[st],btn={'requested':'Getiriyorum','retrieving':'Hazır','ready':'Teslim Et'}[st];return Card(color:st=='requested'?const Color(0xFF2A1E13):panel,child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.directions_car_filled,color:purple),const SizedBox(width:9),Expanded(child:Text(x['plate'].toString(),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))),Text(label,style:TextStyle(color:st=='requested'?Colors.orangeAccent:st=='ready'?lime:muted,fontWeight:FontWeight.w900))]),const SizedBox(height:7),Text('Park: '+(x['parking_area']??'-').toString()+' / '+(x['parking_slot']??'-').toString()+'   •   Anahtar: '+(x['key_location']??'-').toString(),style:const TextStyle(color:muted)),if(next!=null)...[const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>status(x['id'].toString(),next),style:FilledButton.styleFrom(backgroundColor:st=='requested'?lime:purple,foregroundColor:st=='requested'?Colors.black:Colors.white),child:Text(btn!,style:const TextStyle(fontWeight:FontWeight.w900))))]])));})));}
