import 'dart:async';import 'dart:convert';import 'package:flutter/material.dart';import 'package:http/http.dart' as http;import 'package:shared_preferences/shared_preferences.dart';import 'package:mobile_scanner/mobile_scanner.dart';import 'package:firebase_core/firebase_core.dart';import 'package:firebase_messaging/firebase_messaging.dart';
const api='https://heycar-api-185-165-46-213.nip.io',purple=Color(0xFF713BFF),lime=Color(0xFFB6FF2A),bg=Color(0xFF07111F),panel=Color(0xFF101A30),muted=Color(0xFFA7B0C7);
Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();try{await Firebase.initializeApp();}catch(e){debugPrint('Vale Firebase init failed: $e');}runApp(const ValetApp());}
class ValetApp extends StatelessWidget{const ValetApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:purple,brightness:Brightness.dark)),home:const Gate());}
class Gate extends StatefulWidget{const Gate({super.key});@override State<Gate> createState()=>_Gate();}
class _Gate extends State<Gate>{String? token;@override void initState(){super.initState();SharedPreferences.getInstance().then((p){if(mounted)setState(()=>token=p.getString('valet_token'));});}@override Widget build(BuildContext c)=>token==null?Login(onLogin:(t)=>setState(()=>token=t)):Home(token:token!,logout:()async{await (await SharedPreferences.getInstance()).remove('valet_token');setState(()=>token=null);});}
class Login extends StatefulWidget{const Login({super.key,required this.onLogin});final ValueChanged<String> onLogin;@override State<Login> createState()=>_Login();}
class _Login extends State<Login>{final business=TextEditingController(),pin=TextEditingController();bool busy=false;Future<void> go()async{setState(()=>busy=true);try{final r=await http.post(Uri.parse(api+'/api/valet/login'),headers:{'content-type':'application/json'},body:jsonEncode({'businessCode':business.text.trim(),'pin':pin.text.trim()}));if(r.statusCode==200){final t=jsonDecode(r.body)['token'].toString();await (await SharedPreferences.getInstance()).setString('valet_token',t);widget.onLogin(t);}else if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('İşletme veya PIN hatalı.')));}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(children:[Container(width:72,height:72,decoration:BoxDecoration(color:purple,borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.local_parking_rounded,size:42,color:Colors.white)),const SizedBox(height:18),const Text('CepQontag Vale',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const Text('Personel Girişi',style:TextStyle(color:muted)),const SizedBox(height:28),TextField(controller:business,decoration:const InputDecoration(labelText:'İşletme adı veya kodu',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pin,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Vale PIN',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:go,style:FilledButton.styleFrom(backgroundColor:lime,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),child:Text(busy?'Giriş yapılıyor...':'Giriş Yap',style:const TextStyle(fontWeight:FontWeight.w900))))])))));}
class Home extends StatefulWidget{const Home({super.key,required this.token,required this.logout});final String token;final VoidCallback logout;@override State<Home> createState()=>_Home();}
class _Home extends State<Home>{List data=[];List areas=[];String business='',staff='';bool loading=true;Timer? timer;Map<String,String> get h=>{'content-type':'application/json','authorization':'Bearer '+widget.token};@override void initState(){super.initState();load();_push();timer=Timer.periodic(const Duration(seconds:5),(_)=>load());}@override void dispose(){timer?.cancel();super.dispose();}Future<void> _push()async{try{if(Firebase.apps.isEmpty)return;await FirebaseMessaging.instance.requestPermission();final t=await FirebaseMessaging.instance.getToken();if(t==null)return;final p=await SharedPreferences.getInstance();var d=p.getString('valet_device_id');if(d==null){d=DateTime.now().microsecondsSinceEpoch.toString();await p.setString('valet_device_id',d);}await http.post(Uri.parse(api+'/api/valet/push-token'),headers:h,body:jsonEncode({'token':t,'deviceId':d}));FirebaseMessaging.instance.onTokenRefresh.listen((n){http.post(Uri.parse(api+'/api/valet/push-token'),headers:h,body:jsonEncode({'token':n,'deviceId':d}));});}catch(_){}}
Future<void> load()async{try{final r=await http.get(Uri.parse(api+'/api/valet/sessions'),headers:h);if(r.statusCode==401){widget.logout();return;}final j=jsonDecode(r.body);if(mounted)setState((){data=j['sessions']??[];areas=j['areas']??[];business=j['businessName']??'';staff=j['staffName']??'';loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
Future<void> status(String id,String s)async{String? code;if(s=='delivered'){final ctl=TextEditingController();code=await showDialog<String>(context:context,builder:(d)=>AlertDialog(backgroundColor:panel,title:const Text('Güvenli Teslim',style:TextStyle(fontWeight:FontWeight.w900)),content:TextField(controller:ctl,autofocus:true,maxLength:4,keyboardType:TextInputType.number,obscureText:true,decoration:const InputDecoration(labelText:'Araç sahibinin 4 haneli kodu',border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Vazgeç')),FilledButton(onPressed:()=>Navigator.pop(d,ctl.text.trim()),child:const Text('Teslim Et'))]));if(code==null||code.length!=4)return;}final r=await http.patch(Uri.parse(api+'/api/valet/sessions/'+id+'/status'),headers:h,body:jsonEncode({'status':s,'deliveryCode':code}));if(r.statusCode>=300&&mounted){String msg='İşlem tamamlanamadı.';try{final e=jsonDecode(r.body)['error'];if(e=='INVALID_DELIVERY_CODE')msg='Teslim kodu hatalı.';if(e=='DELIVERY_CODE_LOCKED')msg='Çok fazla hatalı deneme. Kod kilitlendi.';if(e=='DELIVERY_CODE_EXPIRED')msg='Teslim kodunun süresi dolmuş.';}catch(_){}ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(msg)));}await load();}
 String qrToken(String raw){try{final u=Uri.parse(raw);final t=u.queryParameters['tag'];if(t!=null&&t.trim().isNotEmpty)return t.trim().toUpperCase();}catch(_){}final v=raw.trim().toUpperCase();return RegExp(r'^[A-Z0-9-]{4,80}$').hasMatch(v)?v:'';}
 Future<void> scan()async{final raw=await Navigator.push<String>(context,MaterialPageRoute(builder:(_)=>const ValetQrScanner()));if(raw==null)return;final token=qrToken(raw);if(token.isEmpty){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Geçerli CepQontag QR bulunamadı.')));return;}await add(qrCode:token);}
 Future<void> add({String? qrCode})async{
  Map<String,dynamic>? vehicle;
  if(qrCode!=null){
   final vr=await http.get(Uri.parse(api+'/api/valet/vehicle-by-qr/'+Uri.encodeComponent(qrCode)),headers:h);
   if(vr.statusCode!=200){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Araç bu CepQontag QR ile eşleştirilemedi.')));return;}
   vehicle=Map<String,dynamic>.from(jsonDecode(vr.body)['vehicle']);
  }
  final p=TextEditingController(text:vehicle?['plate']?.toString()??'');String? selectedArea=areas.isNotEmpty?areas.first['name']?.toString():null;
  await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:panel,builder:(c)=>StatefulBuilder(builder:(c,setSheet)=>Padding(padding:EdgeInsets.fromLTRB(20,20,20,MediaQuery.viewInsetsOf(c).bottom+20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[
   Text(qrCode==null?'Araç Kabul':'QR ile Araç Kabul',textAlign:TextAlign.center,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:14),
   if(vehicle!=null)Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(vehicle!['plate']?.toString()??'',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),if((vehicle!['owner_name']??'').toString().isNotEmpty)Text('Araç sahibi: '+vehicle!['owner_name'].toString(),style:const TextStyle(color:muted)),if(((vehicle!['brand']??'').toString()+' '+(vehicle!['model']??'').toString()).trim().isNotEmpty)Text(((vehicle!['brand']??'').toString()+' '+(vehicle!['model']??'').toString()).trim(),style:const TextStyle(color:muted))])),
   if(qrCode==null)...[const SizedBox(height:12),TextField(controller:p,decoration:const InputDecoration(labelText:'Plaka',border:OutlineInputBorder()))],
   const SizedBox(height:12),
   if(areas.isEmpty)const Text('İşletme panelinden önce bir park alanı eklenmeli.',style:TextStyle(color:Colors.orangeAccent)) else DropdownButtonFormField<String>(initialValue:selectedArea,decoration:const InputDecoration(labelText:'Park alanı',border:OutlineInputBorder()),items:areas.map<DropdownMenuItem<String>>((x)=>DropdownMenuItem(value:x['name'].toString(),child:Text(x['name'].toString()))).toList(),onChanged:(v)=>setSheet(()=>selectedArea=v)),
   const SizedBox(height:16),FilledButton(onPressed:areas.isEmpty?null:()async{if(p.text.trim().isEmpty)return;final r=await http.post(Uri.parse(api+'/api/valet/accept'),headers:h,body:jsonEncode({'plate':p.text.trim(),'qrCode':qrCode,'parkingArea':selectedArea}));if(r.statusCode<300&&c.mounted)Navigator.pop(c);await load();},style:FilledButton.styleFrom(backgroundColor:lime,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),child:const Text('Aracı Valeye Al',style:TextStyle(fontWeight:FontWeight.w900)))
  ]))));
 }
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:bg,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(business.isEmpty?'CepQontag Vale':business,style:const TextStyle(fontWeight:FontWeight.w900)),Text(staff,style:const TextStyle(fontSize:11,color:muted))]),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:widget.logout,icon:const Icon(Icons.logout))]),floatingActionButton:Row(mainAxisSize:MainAxisSize.min,children:[FloatingActionButton.extended(heroTag:'manual',backgroundColor:panel,foregroundColor:Colors.white,onPressed:()=>add(),icon:const Icon(Icons.edit),label:const Text('Manuel')),const SizedBox(width:10),FloatingActionButton.extended(heroTag:'scan',backgroundColor:lime,foregroundColor:Colors.black,onPressed:scan,icon:const Icon(Icons.qr_code_scanner),label:const Text('QR Okut',style:TextStyle(fontWeight:FontWeight.w900)))]),body:loading?const Center(child:CircularProgressIndicator()):data.isEmpty?const Center(child:Text('Aktif vale aracı yok',style:TextStyle(color:muted))):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(14,12,14,100),itemCount:data.length,itemBuilder:(_,i){final x=data[i],st=x['status'].toString();final label={'parked':'Parkta','requested':'ARAÇ İSTENİYOR','retrieving':'Getiriliyor','ready':'Hazır'}[st]??st;final next={'parked':'parked','requested':'retrieving','retrieving':'ready','ready':'delivered'}[st],btn={'parked':'Park Edildi','requested':'Getiriyorum','retrieving':'Hazır','ready':'Teslim Et'}[st];return Card(color:st=='requested'?const Color(0xFF2A1E13):panel,child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.directions_car_filled,color:purple),const SizedBox(width:9),Expanded(child:Text(x['plate'].toString(),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))),Text(label,style:TextStyle(color:st=='requested'?Colors.orangeAccent:st=='ready'?lime:muted,fontWeight:FontWeight.w900))]),const SizedBox(height:7),Text('Park: '+(x['parking_area']??'-').toString()+' / '+(x['parking_slot']??'-').toString()+'   •   Anahtar: '+(x['key_location']??'-').toString(),style:const TextStyle(color:muted)),if(next!=null)...[const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>status(x['id'].toString(),next),style:FilledButton.styleFrom(backgroundColor:st=='requested'?lime:purple,foregroundColor:st=='requested'?Colors.black:Colors.white),child:Text(btn!,style:const TextStyle(fontWeight:FontWeight.w900))))]])));})));}
class ValetQrScanner extends StatefulWidget{const ValetQrScanner({super.key});@override State<ValetQrScanner> createState()=>_ValetQrScanner();}
class _ValetQrScanner extends State<ValetQrScanner>{bool done=false;@override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.black,appBar:AppBar(backgroundColor:Colors.black,title:const Text('CepQontag QR Okut',style:TextStyle(fontWeight:FontWeight.w900))),body:Stack(children:[MobileScanner(onDetect:(capture){if(done)return;for(final b in capture.barcodes){final raw=b.rawValue;if(raw!=null&&raw.trim().isNotEmpty){done=true;Navigator.pop(context,raw);break;}}}),Center(child:Container(width:260,height:260,decoration:BoxDecoration(border:Border.all(color:lime,width:3),borderRadius:BorderRadius.circular(24)))),const Positioned(left:24,right:24,bottom:55,child:Text('Araç camındaki CepQontag etiketini çerçevenin içine getir.',textAlign:TextAlign.center,style:TextStyle(color:Colors.white,fontWeight:FontWeight.w800,fontSize:15))) ]));}
