import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'onboarding_backend.dart';
import 'qr_backend.dart';
const _bg=Color(0xFF07111F),_panel=Color(0xFF101A30),_line=Color(0xFF27355D),_purple=Color(0xFF8B5CFF),_muted=Color(0xFFA7B0C7),_lime=Color(0xFF79FF45),_amber=Color(0xFFFFB548);
class VehicleRemindersPage extends StatefulWidget{const VehicleRemindersPage({super.key,required this.vehicleId});final String vehicleId;@override State<VehicleRemindersPage> createState()=>_VehicleRemindersPageState();}
class _VehicleRemindersPageState extends State<VehicleRemindersPage>{bool loading=true,premium=false,saving=false;DateTime? inspection,trafficInsurance,casco;String get owner=>OnboardingDraft.userId.trim();Map<String,String> get headers=>{'Content-Type':'application/json','x-owner-id':owner};@override void initState(){super.initState();load();}
Future<void> load()async{try{final r=await http.get(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/reminders'),headers:{'x-owner-id':owner}).timeout(const Duration(seconds:12));if(r.statusCode==200){final d=jsonDecode(r.body);premium=d['premium']==true;for(final x in (d['reminders'] as List? ?? const [])){final m=Map<String,dynamic>.from(x as Map),dt=DateTime.tryParse('${m['due_date']}'.split('T').first);switch(m['reminder_type']){case'inspection':inspection=dt;case'traffic_insurance':trafficInsurance=dt;case'casco':casco=dt;}}}}catch(_){}if(mounted)setState(()=>loading=false);}
void locked(){showDialog(context:context,builder:(_)=>AlertDialog(backgroundColor:_panel,title:const Row(children:[Icon(Icons.lock_rounded,color:_purple),SizedBox(width:8),Text('Premium özellik',style:TextStyle(color:Colors.white))]),content:const Text('Muayene, trafik sigortası ve kasko hatırlatmaları Premium üyeler için kullanılabilir.',style:TextStyle(color:_muted)),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Tamam'))]));}
String apiType(String type)=>type=='traffic'?'traffic_insurance':type;Future<void> pick(String type,DateTime? current)async{if(!premium){locked();return;}final now=DateTime.now(),d=await showDatePicker(context:context,initialDate:current??now.add(const Duration(days:30)),firstDate:DateTime(now.year-2),lastDate:DateTime(now.year+10));if(d==null)return;setState(()=>saving=true);try{final ds='${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';final r=await http.put(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/reminders'),headers:headers,body:jsonEncode({'type':apiType(type),'dueDate':ds})).timeout(const Duration(seconds:12));if(r.statusCode==200){setState((){if(type=='inspection')inspection=d;if(type=='traffic')trafficInsurance=d;if(type=='casco')casco=d;});}else if(r.statusCode==403){premium=false;locked();}else{throw Exception();}}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Hatırlatma kaydedilemedi.')));}if(mounted)setState(()=>saving=false);}
Future<void> clear(String type)async{if(!premium){locked();return;}setState(()=>saving=true);try{final r=await http.delete(Uri.parse('${QrBackend.baseUrl}/api/vehicles/${widget.vehicleId}/reminders/${apiType(type)}'),headers:{'x-owner-id':owner}).timeout(const Duration(seconds:12));if(r.statusCode==200)setState((){if(type=='inspection')inspection=null;if(type=='traffic')trafficInsurance=null;if(type=='casco')casco=null;});else throw Exception();}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Hatırlatma silinemedi.')));}if(mounted)setState(()=>saving=false);}
String date(DateTime d)=>'${d.day.toString().padLeft(2,'0')}.${d.month.toString().padLeft(2,'0')}.${d.year}';String status(DateTime? d){if(d==null)return'Tarih eklenmedi';final days=DateTime(d.year,d.month,d.day).difference(DateTime(DateTime.now().year,DateTime.now().month,DateTime.now().day)).inDays;if(days<0)return'${-days} gün geçti';if(days==0)return'Bugün son gün';return'$days gün kaldı';}Color accent(DateTime? d){if(d==null)return _muted;final days=d.difference(DateTime.now()).inDays;if(days<0)return Colors.redAccent;if(days<=30)return _amber;return _lime;}
Widget card(String type,String title,String subtitle,IconData icon,DateTime? value)=>InkWell(onTap:saving?null:(premium?()=>pick(type,value):locked),borderRadius:BorderRadius.circular(20),child:Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:Row(children:[Container(width:52,height:52,decoration:BoxDecoration(color:_purple.withValues(alpha:.13),borderRadius:BorderRadius.circular(16)),child:Icon(premium?icon:Icons.lock_rounded,color:_purple,size:28)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(color:Colors.white,fontSize:16,fontWeight:FontWeight.w900))),if(!premium)const Text('Premium',style:TextStyle(color:_purple,fontSize:11,fontWeight:FontWeight.w900))]),const SizedBox(height:4),Text(value==null?subtitle:date(value),style:const TextStyle(color:_muted,fontSize:13,fontWeight:FontWeight.w600)),if(value!=null)...[const SizedBox(height:4),Text(status(value),style:TextStyle(color:accent(value),fontSize:12.5,fontWeight:FontWeight.w900))]])),if(premium&&value!=null)IconButton(onPressed:saving?null:()=>clear(type),icon:const Icon(Icons.close_rounded,color:_muted))else const Icon(Icons.chevron_right_rounded,color:_muted)]));
@override Widget build(BuildContext context)=>Scaffold(backgroundColor:_bg,appBar:AppBar(backgroundColor:_bg,foregroundColor:Colors.white,elevation:0,title:const Text('Araç Hatırlatmaları',style:TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(18,10,18,28),children:[const Text('Önemli araç tarihlerini tek yerde takip et.',style:TextStyle(color:_muted,fontSize:14,fontWeight:FontWeight.w600)),const SizedBox(height:18),card('inspection','Araç Muayenesi','Son geçerlilik tarihini ekle',Icons.fact_check_outlined,inspection),card('traffic','Trafik Sigortası','Poliçe bitiş tarihini ekle',Icons.shield_outlined,trafficInsurance),card('casco','Kasko','Poliçe bitiş tarihini ekle',Icons.verified_user_outlined,casco),if(premium)Container(margin:const EdgeInsets.only(top:5),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:const Color(0xFF102A25),borderRadius:BorderRadius.circular(17),border:Border.all(color:const Color(0xFF23523E))),child:const Row(children:[Icon(Icons.notifications_active_outlined,color:_lime),SizedBox(width:11),Expanded(child:Text('Muayene 30/7/1 gün; sigorta ve kasko 15/7/1 gün kala bildirim oluşturur.',style:TextStyle(color:Colors.white,fontSize:13,fontWeight:FontWeight.w700)))]]))])));}
