import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'qr_backend.dart';
import 'onboarding_backend.dart';
import 'maintenance_page.dart';
import 'upcoming_maintenance_page.dart';
const _bg=Color(0xFF060D1B),_panel=Color(0xFF0E172A),_line=Color(0xFF202D47),_purple=Color(0xFF813CFF),_muted=Color(0xFF9CA8BE),_lime=Color(0xFF68FF8B);
class VehicleCenterPage extends StatefulWidget{const VehicleCenterPage({super.key,required this.plate,required this.title});final String plate,title;@override State<VehicleCenterPage> createState()=>_S();}
class _S extends State<VehicleCenterPage>{bool loading=true;int km=0;List<dynamic> records=[],upcoming=[];String get vid=>QrDraft.vehicleId.trim().isNotEmpty?QrDraft.vehicleId.trim():OnboardingDraft.vehicleId.trim();String get owner=>OnboardingDraft.userId.trim();Map<String,String> get h=>{'x-owner-id':owner};@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await http.get(Uri.parse('${QrBackend.baseUrl}/api/vehicles/$vid/maintenance'),headers:h),x=jsonDecode(r.body);if(mounted)setState((){km=int.tryParse('${x['currentKm']}')??0;records=x['records']??[];upcoming=x['upcoming']??[];loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
void maintenance()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>MaintenancePage(plate:widget.plate,title:widget.title))).then((_)=>load());
void upcomingPage()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>UpcomingMaintenancePage(upcoming:upcoming,records:records,currentKm:km,onEditIntervals:maintenance))).then((_)=>load());
@override Widget build(BuildContext c){if(loading)return const Scaffold(backgroundColor:_bg,body:Center(child:CircularProgressIndicator()));final next=upcoming.isEmpty?null:Map<String,dynamic>.from(upcoming.first);final last=records.isEmpty?null:Map<String,dynamic>.from(records.first);return Scaffold(backgroundColor:_bg,body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(22,18,22,30),children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Flexible(child:Text(widget.plate,style:const TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900))),const SizedBox(width:9),const Icon(Icons.edit_outlined,color:Colors.white,size:25)]),const SizedBox(height:5),Text(widget.title,style:const TextStyle(color:_muted,fontSize:18,fontWeight:FontWeight.w700)),const SizedBox(height:5),Text(km>0?'$km km':'Kilometre girilmedi',style:const TextStyle(color:_muted,fontSize:16,fontWeight:FontWeight.w700))]))]),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[_Tab(Icons.directions_car_outlined,'Genel',false,()=>{}),_Tab(Icons.build_outlined,'Bakım Geçmişi',true,maintenance),_Tab(Icons.description_outlined,'Belgeler',false,()=>{}),_Tab(Icons.settings_outlined,'Ayarlar',false,()=>{})]),const SizedBox(height:25),InkWell(onTap:upcomingPage,borderRadius:BorderRadius.circular(22),child:_Next(data:next,last:last,currentKm:km)),const SizedBox(height:16),SizedBox(height:58,child:FilledButton.icon(onPressed:maintenance,style:FilledButton.styleFrom(backgroundColor:_purple,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(17))),icon:const Icon(Icons.add,size:29),label:const Text('Bakım Kaydı Ekle',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)))),const SizedBox(height:27),Row(children:[const Expanded(child:Text('Son Kayıtlar',style:TextStyle(color:Colors.white,fontSize:23,fontWeight:FontWeight.w900))),TextButton(onPressed:maintenance,child:const Text('Tümü  ›',style:TextStyle(color:Color(0xFFB653FF),fontSize:17,fontWeight:FontWeight.w900)))]),const SizedBox(height:7),if(last==null)_Empty(onTap:maintenance)else _Record(data:last,onTap:maintenance)]))));}}
class _Tab extends StatelessWidget{const _Tab(this.icon,this.text,this.active,this.tap);final IconData icon;final String text;final bool active;final VoidCallback tap;@override Widget build(BuildContext c)=>InkWell(onTap:tap,borderRadius:BorderRadius.circular(15),child:SizedBox(width:76,child:Column(children:[Container(width:62,height:62,decoration:BoxDecoration(color:active?_purple:_panel,borderRadius:BorderRadius.circular(17),boxShadow:active?[BoxShadow(color:_purple.withValues(alpha:.35),blurRadius:15)]:null),child:Icon(icon,color:Colors.white,size:29)),const SizedBox(height:7),Text(text,textAlign:TextAlign.center,maxLines:1,style:TextStyle(color:Colors.white,fontSize:active?12.5:12,fontWeight:FontWeight.w800))])));}
class _Next extends StatelessWidget{const _Next({required this.data,required this.last,required this.currentKm});final Map<String,dynamic>? data,last;final int currentKm;@override Widget build(BuildContext c){final remaining=int.tryParse('${data?['remainingKm']}')??0,label=data?['label']?.toString()??'Bakım':'Bakım';final due=int.tryParse('${data?['dueKm']}')??0,interval=due>0&&last!=null?due-(int.tryParse('${last!['mileage']}')??0):0;return Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:const Color(0xFF082321),borderRadius:BorderRadius.circular(22),border:Border.all(color:const Color(0xFF12543D))),child:Column(children:[Row(children:[Container(width:76,height:76,decoration:BoxDecoration(color:const Color(0xFF173D25),borderRadius:BorderRadius.circular(22)),child:const Icon(Icons.build_rounded,color:_lime,size:44)),const SizedBox(width:18),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Sonraki Bakım',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(data==null?'Henüz bakım planı oluşturulmadı.':'$label için yaklaşık\n${remaining<=0?'bakım zamanı': '$remaining km kaldı.'}',style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900,height:1.18))]))]),const SizedBox(height:18),ClipRRect(borderRadius:BorderRadius.circular(10),child:LinearProgressIndicator(minHeight:11,value:data==null?0:(remaining<=0?1:.82),backgroundColor:const Color(0xFF26334C),valueColor:const AlwaysStoppedAnimation(_lime))),const SizedBox(height:17),Align(alignment:Alignment.centerLeft,child:Text('Son kayıt: ${currentKm>0?'$currentKm km':'—'}\nÖnerilen aralık: ${interval>0?'$interval km':'—'}',style:const TextStyle(color:_muted,fontSize:15,fontWeight:FontWeight.w700,height:1.55))) ]));}}
class _Record extends StatelessWidget{const _Record({required this.data,required this.onTap});final Map<String,dynamic> data;final VoidCallback onTap;@override Widget build(BuildContext c){final items=data['items'] is List?(data['items'] as List).join(' + '):'Bakım';return InkWell(onTap:onTap,borderRadius:BorderRadius.circular(20),child:Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:Row(children:[Container(width:58,height:58,decoration:BoxDecoration(color:const Color(0xFF123D2D),borderRadius:BorderRadius.circular(17)),child:const Icon(Icons.build_rounded,color:_lime,size:34)),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${data['mileage']??'—'} km',style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:3),Text('${data['service_date']??''}',style:const TextStyle(color:_muted,fontSize:14)),const SizedBox(height:4),Text(items,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:15,fontWeight:FontWeight.w700))])),const Icon(Icons.chevron_right,color:Colors.white,size:32)])));}
class _Empty extends StatelessWidget{const _Empty({required this.onTap});final VoidCallback onTap;@override Widget build(BuildContext c)=>InkWell(onTap:onTap,child:Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:_panel,borderRadius:BorderRadius.circular(20),border:Border.all(color:_line)),child:const Text('Henüz bakım kaydı yok. İlk bakım kaydını ekle.',style:TextStyle(color:_muted,fontSize:15))));}
